Repository litmuschaos/litmus, pull requests merged in 2020-12, with the labels that each got.

#2367 Added annotation and app info check and fixed the namespace issue in custom workflow creation
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/L

#2375 Fixed an edge case where appinfo is not present in custom workflows
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/M

#2376 Delete cluster permission fixed
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
Labels: READY TO MERGE, merge, size/M

#2378 Adding Litmus Portal API docs
  litmus-portal/frontend/.eslintignore
  litmus-portal/frontend/public/api-doc/config.yml
  litmus-portal/frontend/public/api-doc/images/logo.png
  litmus-portal/frontend/public/api-doc/index.html
  litmus-portal/frontend/public/api-doc/javascripts/spectacle.js
  litmus-portal/frontend/public/api-doc/javascripts/spectacle.min.js
  litmus-portal/frontend/public/api-doc/logo.png
  litmus-portal/frontend/public/api-doc/stylesheets/foundation.css
  litmus-portal/frontend/public/api-doc/stylesheets/foundation.min.css
  litmus-portal/frontend/public/api-doc/stylesheets/spectacle.css
  litmus-portal/frontend/public/api-doc/stylesheets/spectacle.min.css
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/QuickActionCard/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
Labels: READY TO MERGE, size/M

#2381 Upgrading litmus portal to v1.11.0
  .circleci/config.yml
  litmus-portal/README.md
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/litmus-portal-crds.yml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/XL

#2382 Changing the image tag of litmus portal from ci to 1.11.0
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/S

#2383 Analytics loading and data bug fixed
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, size/S

#2385 (chore)chaos-runner: update chaos-runner to 1.11.1 patch version
  docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  docs/litmus-operator-v1.11.0.yaml
Labels: READY TO MERGE, size/XS

#2317 Create README-pt-br.md
  translations/README-pt-br.md
Labels: size/L

#2264 Add brazilian portuguese README translation
  README.md
  translations/README-pt-br.md
  translations/TRANSLATIONS.md
Labels: READY TO MERGE, size/L

#2271 russian language readme
  translations/README-ru.md
  translations/TRANSLATIONS.md
Labels: READY TO MERGE, size/M

#2252 Translated readme.md in Hindi (हिंदी) language
  README.md
  translations/README-hi.md
Labels: size/L

#2384 Added BugFixes for Editor.
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/utils/yamlUtils.ts
Labels: READY TO MERGE, kind/bug-fix, size/M

#2387 Updated workflow Representation
  litmus-portal/frontend/.eslintrc.json
  litmus-portal/frontend/src/ReduxRoot.tsx
  litmus-portal/frontend/src/components/Button/ButtonFilled/index.tsx
  litmus-portal/frontend/src/components/Button/ButtonOutline/index.tsx
  litmus-portal/frontend/src/components/DagreGraph/index.tsx
  litmus-portal/frontend/src/utils/createApolloClient.ts
  litmus-portal/frontend/src/utils/createSVGNode.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/createLabel.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/icons.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
Labels: READY TO MERGE, size/L
