Repository litmuschaos/litmus, pull requests merged in 2020-01, with the labels that each got.

#1039 (refactor): fix container kill experiment
  chaoslib/pumba/pod_failure_by_sigkill.yaml
  experiments/generic/container_kill/README.md
  experiments/generic/container_kill/chaosutil.j2
  experiments/generic/container_kill/container_kill_ansible_logic.yml
  experiments/generic/container_kill/container_kill_ansible_prerequisites.yml
  experiments/generic/container_kill/container_kill_k8s_job.yml
Labels: area/litmus, state/review-in-progress

#1053 (fix):Added selector in powerfulseal deployment spec
  chaoslib/powerfulseal/powerfulseal.j2
Labels: area/litmus, kind/chaos-experiment

#1058 (refactor): update readme & change pumba image
  experiments/generic/pod_network_loss/README.md
  experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml
Labels: area/litmus, area/litmus-docs

#1057 (fix): changed apiversion for daemonset
  chaoslib/litmus/platform/gke/cpu-hog-daemonset.yml
Labels: area/chaos-chart, area/chaos-runner

#1043 (feat) Added pumba container health check status
  chaoslib/pumba/pod_failure_by_sigkill.yaml
  experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
  experiments/generic/container_kill/container_kill_ansible_logic.yml
  experiments/generic/cpu_hog/cpu_hog_ansible_logic.yml
  experiments/generic/disk_fill/disk_fill_ansible_logic.yml
  experiments/generic/disk_loss/disk_loss_ansible_logic.yml
  experiments/generic/drain_node/drain_node_ansible_logic.yml
  experiments/generic/pod_delete/pod_delete_ansible_logic.yml
  experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
  experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
  experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
  experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
  experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
  experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
  experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
  experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
  experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
  experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
  experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
  experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
  experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
  utils/apps/kafka/kafka_cluster_health.yml
  utils/common/status_app_pod.yml
Labels: area/litmus, kind/enhancement

#1044 (feat): Added cpu-hog container status, delete cpu-hog ds always and failed the playbook if task failed
  chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
  experiments/generic/cpu_hog/README.md
  experiments/generic/cpu_hog/cpu_hog_ansible_logic.yml
  experiments/generic/cpu_hog/cpu_hog_k8s_job.yml
Labels: area/litmus, area/litmus-docs, kind/enhancement

#1054 (feat): Ability to derive the container name, fail playbook if task fail
  chaoslib/pumba/network_chaos/network_chaos.yml
  experiments/generic/pod_network_latency/README.md
Labels: area/litmus, kind/chaos-experiment, kind/enhancement

#1062 (refactor): update readme of disk-loss experiment
  experiments/generic/disk_loss/README.md
Labels: area/litmus-docs, kind/refactor

#1051 (feat): Add disk-fill container status check & delete ds
  chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
  experiments/generic/disk_fill/README.md
Labels: area/litmus, kind/chaos-experiment, kind/enhancement

#1061 (refactor): Update the drain node readme
  experiments/generic/drain_node/README.md
Labels: area/litmus-docs, kind/refactor

#1074 (doc): adding coredns pod delete docs
  experiments/coredns/pod_delete/README.md
  experiments/generic/disk_loss/README.md
Labels: area/litmus-docs

#1076 (fix):Delete Daemonsets after completion of task
  chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
Labels: area/chaos-runner, area/litmus, kind/bug

#1078 Removed typo
  chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
Labels: kind/bug

#1079 (Fix):Check availablity of daemonset after deletion in cpu-hog and disk-fill
  chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
  chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
Labels: area/chaos-runner, area/litmus

#1085 (feat): Adding rescue block in pod-delete by powerseal lib
  chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
Labels: area/litmus, kind/chaos-experiment

#1093 (fix): changing mount path from mnt to tmp
  utils/cloud/aws/aws_configure.yml
Labels: kind/bug

#1108 Refactored readme for openebs experiments
  experiments/generic/container_kill/README.md
  experiments/generic/pod_network_corruption/README.md
  experiments/openebs/openebs-pool-container-failure/README.md
  experiments/openebs/openebs-pool-pod-failure/README.md
  experiments/openebs/openebs-target-container-failure/README.md
  experiments/openebs/openebs-target-network-delay/README.md
  experiments/openebs/openebs-target-network-loss/README.md
  experiments/openebs/openebs-target-pod-failure/README.md
Labels: kind/refactor

#1110 Added readme.md for kafka experiments
  experiments/kafka/kafka-broker-disk-failure/README.md
  experiments/kafka/kafka-broker-pod-failure/README.md
Labels: kind/refactor

#1128 (feat): Add the baseline stage in gitlab-ci to record the latest commit in baseline file
  .gitlab-ci.yml
Labels: kind/enhancement

#1129 (feat): Add ability to provide cmap/secret in engine
  executor/engine_configmap_getter.yml
  executor/engine_env_getter.yml
  executor/engine_secret_getter.yml
  executor/executor.yml
  executor/experiment_configmap_getter.yml
  executor/experiment_secret_getter.yml
  executor/experiment_volumes.yml
Labels: area/chaos-runner

#1082 (feat): Adding coredns experiment's activity diagram
  experiments/coredns/pod_delete/README.md
  experiments/coredns/pod_delete/activity_diagram_coredns.png
  experiments/coredns/pod_delete/pod_delete_ansible_prerequisites.yml
  experiments/coredns/pod_delete/pod_delete_k8s_job.yml
Labels: area/diagram

#1138 (refactor): fix openebs-target-container-failure experiment to support containerd runtime
  chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
  chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
  experiments/openebs/openebs-target-container-failure/cstor_target_container_kill.yml
  experiments/openebs/openebs-target-container-failure/jiva_controller_container_kill.yml
Labels: kind/chaos-experiment

#1143 (refactor): Update openebs-target-pod-failure experiment
  experiments/openebs/openebs-target-pod-failure/chaosutil.j2
  experiments/openebs/openebs-target-pod-failure/cstor_target_pod_failure.yaml
  experiments/openebs/openebs-target-pod-failure/jiva_controller_pod_failure.yaml
  experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
  experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_prerequisites.yml
Labels: kind/refactor

#1139 (feat): Adding rescue block in pod-failure-by sigkill lib
  chaoslib/pumba/pod_failure_by_sigkill.yaml
  experiments/generic/container_kill/container_kill_ansible_logic.yml
  experiments/openebs/openebs-pool-container-failure/cstor_kill_and_verify_pool.yml
Labels: artifact/litmusbook

#1151 (bug-fix): Fixing a naming bug in the openebs target network loss experiment (network delay ---> network loss)
  experiments/coredns/pod_delete/README.md
  experiments/openebs/openebs-target-network-loss/README.md
  experiments/openebs/openebs-target-network-loss/chaosutil.j2
  experiments/openebs/openebs-target-network-loss/cstor_target_network_loss.yaml
  experiments/openebs/openebs-target-network-loss/data_persistence.j2
  experiments/openebs/openebs-target-network-loss/jiva_controller_network_loss.yaml
  experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
  experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_k8s_job.yml
Labels: kind/bug
