Repository litmuschaos/litmus, pull requests merged in 2020-06, with the labels that each got.

#1542 chore(feat): Add kubelet service kill experiment in generic experiment list
  chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.j2
  chaoslib/litmus/kubelet_service_kill/kubelet_service_kill.yml
  experiments/generic/kubelet_service_kill/README.md
  experiments/generic/kubelet_service_kill/chaosutil.j2
  experiments/generic/kubelet_service_kill/kubelet_service_kill_ansible_logic.yml
  experiments/generic/kubelet_service_kill/kubelet_service_kill_ansible_prerequisites.yml
  experiments/generic/kubelet_service_kill/kubelet_service_kill_k8s_job.yml
Labels: kind/chaos-experiment, kind/enhancement

#1540 chore(feat): Add Github Action bot for litmus e2e runs on PR comment basis
  .github/workflows/main.yml
Labels: kind/bdd, kind/ci, kind/enhancement, kind/feature

#1556 feat(actions): Add merge label and auto-merge feature in GitHub Actions
  .github/auto-merge.yml
  .github/workflows/main.yml
Labels: kind/enhancement

#1555 refactor(readme): Add more details in pod network corruption readme
  experiments/generic/pod_network_corruption/README.md
Labels: merge

#1576 refactor(experiment): Add pod memory hog default memory consumption
  experiments/generic/pod_memory_hog/pod_memory_hog_k8s_job.yml
Labels: merge

#1581 Bug(indentation): Fix the indentation in kubelet service kill experiment j2 file
  chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.j2
Labels: merge

#1589 (chore): update schematic representation of litmus arch
  README.md
  images/litmus-schematic.png
Labels: merge

#1597 chore(Graphql-server): Adding graphql server to the litmus portal (backend)
  litmus-portal/backend/graphql-server/build/Dockerfile
  litmus-portal/backend/graphql-server/go.mod
  litmus-portal/backend/graphql-server/go.sum
  litmus-portal/backend/graphql-server/gqlgen.yml
  litmus-portal/backend/graphql-server/graph/generated/generated.go
  litmus-portal/backend/graphql-server/graph/model/models_gen.go
  litmus-portal/backend/graphql-server/graph/resolver.go
  litmus-portal/backend/graphql-server/graph/schema.graphqls
  litmus-portal/backend/graphql-server/graph/schema.resolvers.go
  litmus-portal/backend/graphql-server/server.go
  litmus-portal/build_docker.sh
  litmus-portal/deploy_production.sh
  litmus-portal/remove_k8s.sh
  litmus-portal/start_k8s.sh
Labels: area/litmus-portal

#1599 (chore)governance: update maintainer email IDs
  MAINTAINERS
Labels: merge

#1603 Changes made according to the base layout and added new components
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/icons/Cloud.png
  litmus-portal/frontend/public/icons/Fail.png
  litmus-portal/frontend/public/icons/Folder.png
  litmus-portal/frontend/public/icons/NotFail.png
  litmus-portal/frontend/public/icons/NotPass.png
  litmus-portal/frontend/public/icons/Pass.png
  litmus-portal/frontend/public/icons/Server.png
  litmus-portal/frontend/public/icons/arrow.png
  litmus-portal/frontend/public/icons/cluster.png
  litmus-portal/frontend/public/icons/community.png
  litmus-portal/frontend/public/icons/docs.png
  litmus-portal/frontend/public/icons/hub.png
  litmus-portal/frontend/public/icons/setting.png
  litmus-portal/frontend/public/icons/settings.png
  litmus-portal/frontend/public/icons/survey.png
  litmus-portal/frontend/public/icons/team.png
  litmus-portal/frontend/src/components/ButtonFilled/index.tsx
  litmus-portal/frontend/src/components/ButtonFilled/styles.ts
  litmus-portal/frontend/src/components/ButtonOutline/index.tsx
  litmus-portal/frontend/src/components/ButtonOutline/styles.ts
  litmus-portal/frontend/src/components/CustomInfoFilled/index.tsx
  litmus-portal/frontend/src/components/CustomInfoFilled/styles.ts
  litmus-portal/frontend/src/components/CustomResultModal/index.tsx
  litmus-portal/frontend/src/components/CustomResultModal/styles.ts
  litmus-portal/frontend/src/components/CustomSlider/index.tsx
  litmus-portal/frontend/src/components/CustomSlider/styles.ts
  litmus-portal/frontend/src/components/CustomStepper/index.tsx
  litmus-portal/frontend/src/components/CustomStepper/styles.ts
  litmus-portal/frontend/src/components/LinearProgressBar/index.tsx
  litmus-portal/frontend/src/components/QuickActionCard/index.tsx
  litmus-portal/frontend/src/components/QuickActionCard/style.ts
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/ToggleComponent/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/HomePage/style.ts
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/pages/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/pages/ReliabilityScore/styles.ts
  litmus-portal/frontend/src/theme/index.tsx
Labels: area/litmus-portal
