Repository litmuschaos/litmus, pull requests merged in 2020-11, with the labels that each got.

#2307 Refactoring manifest parser function for the fields(agent-namespace and service account)
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/graphql-server/utils/misc.go
Labels: READY TO MERGE, size/M

#2306 chore(litmus-portal): Added custom workflow feature with public hub and myhub and minor fixes
  litmus-portal/frontend/public/icons/tick.svg
  litmus-portal/frontend/public/icons/yaml.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/PredifinedWorkflows/index.tsx
  litmus-portal/frontend/src/components/PredifinedWorkflows/styles.ts
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/models/redux/customyaml.ts
  litmus-portal/frontend/src/models/redux/myhub.ts
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/CreateCustomWorkflow/index.tsx
  litmus-portal/frontend/src/pages/CreateCustomWorkflow/styles.ts
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/redux/actions/myhub.ts
  litmus-portal/frontend/src/redux/actions/workflow.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/redux/reducers/publicHub.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/BackButton/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/BackButton/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/YamlEditor/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/YamlEditor/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, merge, size/XXL

#2311 Agent scope for litmus-portal frontend
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-K8s-template.yml
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, size/S

#2312 Added Patch to handle duplicate workflow events
  litmus-portal/cluster-agents/subscriber/pkg/gql/mutations.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
Labels: PR: Changes Requested, size/M

#2309 Bug fixes in custom workflow section and added autocomplete search for experiment selection
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/models/graphql/clusterData.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/Home/PassedVsFailed/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Labels: READY TO MERGE, area/litmus-portal, merge, size/L

#2322 (chore)roadmap: update roadmap
  ROADMAP.md
Labels: size/XS

#2318 Moving self deployer functionalities to graphql server
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/k8s/client.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: READY TO MERGE, area/litmus-portal, merge, size/L

#2326 Enhancing workflow delete operation
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/queries/query.go
  litmus-portal/graphql-server/pkg/graphql/subscriptions/subscription.go
  litmus-portal/graphql-server/pkg/graphql/types.go
Labels: size/L

#2324 Added API Endpoint for fetching yamls for Engine/Experiment/RBAC.
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: size/L

#2327 chore(litmus-portal): Adding update workflow operation to graphql server
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/subscriptions/subscription.go
Labels: PR: Changes Requested, area/litmus-portal, size/L

#2319 Adding delete cluster mutation
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
Labels: PR: Changes Requested, size/L

#2325 chore(litmus-portal): Added upload YAML feature in litmus-portal
  litmus-portal/frontend/public/icons/upload-success.svg
  litmus-portal/frontend/public/icons/upload-yaml.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
Labels: READY TO MERGE, area/litmus-portal, project/community, size/L

#2329 Refactoring update workflow function
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
Labels: READY TO MERGE, size/S

#2330 Removing self-deployer code and its dependencies
  .betterci/ci-k8s-manifest.yml
  .circleci/config.yml
  litmus-portal/Makefile
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/server.go
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/README.md
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
  litmus-portal/tools/self-deployer/build/Dockerfile
  litmus-portal/tools/self-deployer/deployer.go
  litmus-portal/tools/self-deployer/go.mod
  litmus-portal/tools/self-deployer/go.sum
Labels: READY TO MERGE

#2331 chore(litmus-portal): Patch to keep the workflow runs when schedules are deleted
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/queries/query.go
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/L

#2328 Added RBAC for Custom Workflows and My Hubs + Bug Fixes + Refactoring
  litmus-portal/frontend/public/icons/myhub-litmus.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Header/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/quries.ts
  litmus-portal/frontend/src/models/redux/myhub.ts
  litmus-portal/frontend/src/models/redux/user.ts
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/CreateCustomWorkflow/index.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/redux/actions/myhub.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/redux/reducers/publicHub.ts
  litmus-portal/frontend/src/redux/reducers/user.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/BackButton/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/YamlEditor/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
Labels: READY TO MERGE, area/litmus-portal, merge, size/XL

#2332 Replacing agent namespace with workflow manifest namespace
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/subscriptions/subscription.go
  litmus-portal/graphql-server/pkg/graphql/types.go
Labels: size/S

#2320 Added go-routine for syncing of hubs.
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/pkg/synchandler/sync-handler.go
  litmus-portal/graphql-server/server.go
Labels: READY TO MERGE, size/M

#2336 (litmus-portal): Minor bug fixes for analytics on litmus portal.
  litmus-portal/frontend/src/views/Home/PassedVsFailed/index.tsx
  litmus-portal/frontend/src/views/Home/ResilienceScoreComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/index.tsx
Labels: area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/M

#2339 (litmus-portal): Adding auth credentials to MongoDB deployment and refactoring gql-sever and auth-server
  litmus-portal/authentication/pkg/store/user.go
  litmus-portal/authentication/pkg/types/const.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: READY TO MERGE, area/litmus-portal, merge, size/L

#2340 Litmus portal analytics report version change
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
Labels: area/chaos-analytics, area/litmus, area/litmus-portal, kind/docs, size/M

#2333 Updated graphql query in frontend and added cron support for custom workflow
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/graphql/quries.ts
  litmus-portal/frontend/src/models/graphql/scheduleData.ts
  litmus-portal/frontend/src/utils/workflowTemplate.ts
Labels: READY TO MERGE, area/litmus-portal, merge, size/M

#2337 Migrated MyHub from users collection to MyHub collection
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/usermanagement.graphqls
  litmus-portal/graphql-server/pkg/database/mongodb/operations/myhub.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations/usermanagement.go
  litmus-portal/graphql-server/pkg/database/mongodb/schema/myhub.go
  litmus-portal/graphql-server/pkg/database/mongodb/schema/usermanagement.go
  litmus-portal/graphql-server/pkg/myhub/gitops/gitops.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/project/create.go
  litmus-portal/graphql-server/pkg/synchandler/sync-handler.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: PR: Changes Requested, area/litmus-portal, size/XL

#2342 adding Keptn
  ADOPTERS.md
Labels: size/XS

#2338 Added changes for My Hub and Custom workflows with Project ID association.
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/PredifinedWorkflows/index.tsx
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/quries.ts
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Templates/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
Labels: READY TO MERGE, size/L

#2345 chore(litmus-portal): Removed unused variables from the models
  litmus-portal/frontend/src/models/graphql/clusterData.ts
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/XS

#2346 (adopters)update: add shantanu as adopter
  ADOPTERS.md
  adopters/users/Shantanu_Deshpande.md
Labels: size/XS

#2341 chore(litmus-portal): Added portal version in sidebar
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/SideBar/styles.ts
Labels: area/litmus-portal, size/S

#2347 Adding namespace for cluster registration
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
Labels: READY TO MERGE, size/XS

#2348 Removed access for viewer to delete cluster
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
Labels: READY TO MERGE, size/S

#2349 Cherry picking from master to 1.10.x
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
Labels: READY TO MERGE, size/S

#2344 (adopters)update: add akridata as an adopter
  ADOPTERS.md
  adopters/organizations/akridata.md
Labels: size/S

#2350 (chore)manifests: update manifests for 1.10.0
  docs/chaos-scheduler-v1.10.0.yaml
  docs/litmus-admin-rbac.yaml
  docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
  docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.10.0.yaml
  docs/litmus-operator-v1.4.0.yaml
  docs/litmus-operator-v1.5.0.yaml
  docs/litmus-operator-v1.6.0.yaml
  docs/litmus-operator-v1.6.2.yaml
  docs/litmus-operator-v1.7.0.yaml
  docs/private_docker_setup.md
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#2352 Upgrading litmus portal version and litmus crds
  litmus-portal/README.md
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/litmus-portal-crds.yml
Labels: size/L

#2354 update(chaosengine-crd): updating chaosengine crd
  docs/chaos-scheduler-v1.10.0.yaml
  docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.10.0.yaml
  docs/litmus-operator-v1.9.0.yaml
  docs/litmus-operator-v1.9.1.yaml
Labels: size/L

#2353 Upgrading litmus-portal version and chaos crds to v1.10.0
  litmus-portal/README.md
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/litmus-portal-crds.yml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/run.sh
Labels: area/litmus-portal, size/L

#2355 Fixing circleci config
  .circleci/config.yml
Labels: size/XS

#2356 Cheery-pick from master
  .circleci/config.yml
Labels: size/XS

#2308 add okteto manifests to graphql and authentication server
  litmus-portal/authentication/.stignore
  litmus-portal/authentication/okteto.yml
  litmus-portal/graphql-server/.stignore
  litmus-portal/graphql-server/okteto.yml
  litmus-portal/platforms/okteto/README.md
Labels: size/M

#2360 (adopters)update: add raspbernetes project as an adopter
  ADOPTERS.md
  adopters/organizations/raspbernetes.md
Labels: size/S

#2362 Printing error instead of return in case of failed cloning
  litmus-portal/graphql-server/pkg/project/create.go
Labels: size/XS

#2361 chore(litmus-portal): Minor fix in custom workflow creation
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/M

#2363 Adding go routine to cloning default myhub function
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/project/create.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: size/S

#2364 Fix rules of the ClusterRole
  docs/litmus-operator-ci.yaml
Labels: READY TO MERGE, size/S

#2365 Added annotationCheck and fixed workflow deletion by viewer
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/L

#2366 Adding DB credentials to run.sh
  litmus-portal/run.sh
Labels: READY TO MERGE, size/XS
