Repository litmuschaos/litmus, pull requests merged in 2020-03, with the labels that each got.

#1226 (feat): Converting pumba daemonset to job with node selector
  chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
  chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
  chaoslib/pumba/network_chaos/network_chaos.yml
  chaoslib/pumba/pod_failure_by_sigkill.yml
  chaoslib/pumba/pumba.j2
Labels: state/review-in-progress

#1264 feat(experiment) Adding support for generation of experiment events in chaosengine
  chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
  chaoslib/litmus/cordon_drain_node.yml
  chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
  chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
  chaoslib/litmus/kill_random_pod.yml
  chaoslib/litmus/platform/aws/disk_loss.yml
  chaoslib/litmus/platform/gke/disk_loss.yml
  chaoslib/litmus/platform/gke/node_cpu_consumption.yml
  chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
  chaoslib/pumba/network_chaos/network_chaos.yml
  chaoslib/pumba/pod_failure_by_sigkill.yml
  experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
  experiments/generic/container_kill/container_kill_ansible_logic.yml
  experiments/generic/disk_fill/disk_fill_ansible_logic.yml
  experiments/generic/disk_loss/disk_loss_ansible_logic.yml
  experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
  experiments/generic/node_drain/node_drain_ansible_logic.yml
  experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml
  experiments/generic/pod_delete/pod_delete_ansible_logic.yml
  experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
  experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
  experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
  experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
  experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
  experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
  experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
  experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
  experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
  experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
  experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
  experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
  experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
  experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
  experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
  experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
  utils/common/generate-kubernetes-chaos-events.yml
  utils/runtime/getting_failure_step.yml
Labels: kind/enhancement, state/review-in-progress

#1266 refactor(disk-fill): Converting the daemonset into job
  chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
  chaoslib/litmus/disk_fill/disk_fill_job.j2
  chaoslib/litmus/service_delete.yml
Labels: kind/refactor

#1271 Refactor(node-cpu-hog): Converting the daemonset into job in node cpu hog Lib
  chaoslib/litmus/platform/gke/node-cpu-hog-daemonset.j2
  chaoslib/litmus/platform/gke/node-cpu-hog-job.j2
  chaoslib/litmus/platform/gke/node_cpu_consumption.yml
Labels: kind/refactor

#1194 (Feat): Adding openebs pool disk loss experiment
  chaoslib/litmus/platform/aws/disk_loss.yml
  experiments/openebs/openebs-pool-disk-loss/chaosutil.j2
  experiments/openebs/openebs-pool-disk-loss/data_persistence.j2
  experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
  experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_prerequisites.yml
  experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_k8s_job.yml
  experiments/openebs/openebs-pool-disk-loss/platform_vars.yml
  utils/apps/openebs/cstor_pool_health_status.yml
  utils/cloud/aws/status_disk.yml
  utils/cloud/gcp/status_disk.yml
  utils/common/disk_status_check.j2
Labels: area/chaos-chart, chart/openebs, kind/feature, state/dev-complete, state/review-in-progress

#1278 (refact): removing disk status check jinja
  experiments/generic/disk_loss/disk_status_check.j2
Labels: kind/refactor

#1237 (experiment): Add node memory hog experiment in the generic experiment list
  chaoslib/litmus/platform/gke/node-memory-hog-job.j2
  chaoslib/litmus/platform/gke/node_memory_consumption.yml
  experiments/generic/node_memory_hog/README.md
  experiments/generic/node_memory_hog/chaosutil.j2
  experiments/generic/node_memory_hog/node_memory_hog_ansible_logic.yml
  experiments/generic/node_memory_hog/node_memory_hog_ansible_prerequisites.yml
  experiments/generic/node_memory_hog/node_memory_hog_k8s_job.yml
Labels: chart/generic, issue-taken, kind/enhancement, kind/feature, language/ansible, state/dev-complete

#1294 Feat(Chaos-lib): Adding run-id support for the chaos libs
  chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
  chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
  chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
  chaoslib/litmus/disk_fill/disk_fill_job.j2
  chaoslib/litmus/platform/gke/node-cpu-hog-job.j2
  chaoslib/litmus/platform/gke/node-memory-hog-job.j2
  chaoslib/litmus/platform/gke/node_cpu_consumption.yml
  chaoslib/litmus/platform/gke/node_memory_consumption.yml
  chaoslib/pumba/pod_failure_by_sigkill.yml
  chaoslib/pumba/pumba.j2
Labels: kind/refactor

#1293 Feat(Openebs-pool-disk-loss): Adding event support for openebs pool disk loss experiment
  experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
Labels: kind/feature

#1291 bug-fix(jinja-template): Adding checks for chaos-uid in all jinja templates
  chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
  chaoslib/litmus/cpu_hog/app_cpu_stress.j2
  chaoslib/litmus/disk_fill/disk_fill_job.j2
  chaoslib/litmus/platform/gke/node-cpu-hog-job.j2
  chaoslib/litmus/platform/gke/node-memory-hog-job.j2
  chaoslib/litmus/platform/gke/node_cpu_consumption.yml
  chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
  chaoslib/powerfulseal/powerfulseal.j2
  chaoslib/pumba/network_chaos/pumba_netem_job.j2
  chaoslib/pumba/pod_failure_by_sigkill.yml
  chaoslib/pumba/pumba.j2
  experiments/coredns/pod_delete/liveness-app.j2
  experiments/coredns/pod_delete/nginx.j2
Labels: kind/bug

#1272 (chore)governance: add governance artefacts for litmus project
  GOVERNANCE.md
  MAINTAINERS
Labels: DO NOT MERGE, WIP

#1357 feat(node-cpu-hog): Using custom input for number of cores in node cpu hog experiment
  chaoslib/litmus/platform/gke/node_cpu_consumption.yml
  experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
  experiments/generic/node_cpu_hog/node_cpu_hog_k8s_job.yml
Labels: kind/enhancement

#1340 feat(chaos_ns): Adding chaos namespace in all experiments
  chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
  chaoslib/litmus/cordon_drain_node.yml
  chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
  chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
  chaoslib/litmus/kill_random_pod.yml
  chaoslib/litmus/platform/aws/disk_loss.yml
  chaoslib/litmus/platform/gke/disk_loss.yml
  chaoslib/litmus/platform/gke/node_cpu_consumption.yml
  chaoslib/litmus/platform/gke/node_memory_consumption.yml
  chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
  chaoslib/pumba/network_chaos/network_chaos.yml
  chaoslib/pumba/pod_failure_by_sigkill.yml
  experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
  experiments/coredns/pod_delete/pod_delete_k8s_job.yml
  experiments/generic/container_kill/container_kill_ansible_logic.yml
  experiments/generic/disk_fill/disk_fill_ansible_logic.yml
  experiments/generic/disk_loss/disk_loss_ansible_logic.yml
  experiments/generic/disk_loss/disk_loss_k8s_job.yml
  experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
  experiments/generic/node_drain/node_drain_ansible_logic.yml
  experiments/generic/node_memory_hog/node_memory_hog_ansible_logic.yml
  experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml
  experiments/generic/pod_delete/pod_delete_ansible_logic.yml
  experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
  experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
  experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
  experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
  experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
  experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
  experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
  experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
  experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_internal_tasks.yml
  experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
  experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
  experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_k8s_job.yml
  experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
  experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
  experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
  experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
  experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
  experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
  experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
  utils/runtime/getting_failure_step.yml
Labels: kind/chaos-experiment

#1250 Feat(Ansible-lint): Adding ansible lint to the CI and checks all the experiments with the ansible lint
  .travis.yml
  Makefile
  ansiblelint/lint-check.sh
  ansiblelint/rules/README.md
  build/ansible-runner/Dockerfile
Labels: kind/feature

#1380 refactor(network_lib): Converting the network chaos Job to Pod
  chaoslib/pumba/network_chaos/network_chaos.yml
  chaoslib/pumba/network_chaos/pumba_netem_job.j2
Labels: DO NOT MERGE
