Repository litmuschaos/litmus, pull requests merged in 2020-10, with the labels that each got.

#2093 bug fix: User details updation in usermanagement tab
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
Labels: merge, size/M

#2135 Adopter information from intuit
  ADOPTERS.md
  adopters/intuit.md
Labels: size/S

#2164 chore(litmus-portal): added title image , fixed a link & few typos
  CONTRIBUTING.md
Labels: READY TO MERGE, area/litmus-portal, size/S

#2120 Themes file update with some generic defined labels
  litmus-portal/frontend/src/components/Header/ProfileDropdownItems.tsx
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/components/Tabs/index.tsx
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/pages/HomePage/style.ts
  litmus-portal/frontend/src/pages/Settings/styles.ts
  litmus-portal/frontend/src/theme/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunDetailsTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
Labels: PR: Changes Requested, size/L

#2170 Added Enter Submit functionality
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/InputField/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/Modalpage.tsx
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
Labels: READY TO MERGE, size/M

#2176 fix: update CRs
  demo/sample-applications/sock-shop/deploy/monitoring/02-prometheus-rbac.yaml
  docs/litmus-admin-rbac.yaml
  docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.4.0.yaml
  docs/litmus-operator-v1.5.0.yaml
  docs/litmus-operator-v1.6.0.yaml
  docs/litmus-operator-v1.6.1.yaml
  docs/litmus-operator-v1.6.2.yaml
  docs/litmus-operator-v1.7.0.yaml
  docs/litmus-operator-v1.8.0.yaml
  docs/litmus-operator-v1.8.1.yaml
  docs/litmus-operator-v1.8.2.yaml
  litmus-portal/graphql-server/manifests/subscriber.yml
Labels: Hacktoberfest, size/M

#2192 Fixed Cron Workflows
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
Labels: READY TO MERGE

#2119 chore(litmus-portal): Added user avatar selection modal
  litmus-portal/frontend/public/avatars/checkmark.svg
  litmus-portal/frontend/public/avatars/default.svg
  litmus-portal/frontend/public/avatars/female1.svg
  litmus-portal/frontend/public/avatars/female2.svg
  litmus-portal/frontend/public/avatars/female3.svg
  litmus-portal/frontend/public/avatars/female4.svg
  litmus-portal/frontend/public/avatars/male1.svg
  litmus-portal/frontend/public/avatars/male2.svg
  litmus-portal/frontend/public/avatars/male3.svg
  litmus-portal/frontend/public/avatars/male4.svg
  litmus-portal/frontend/public/icons/edit.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/ChooseAvatarModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/ChooseAvatarModal/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal

#2184 Adding clusterid and clustername response in UserClusterReg Mutation
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
Labels: size/L

#2197 Adding no of workflow and schedules in getCluster query
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/queries/query.go
Labels: size/L

#2181 updated private_docker_setup.md
  docs/private_docker_setup.md
Labels: size/S

#2204 (litmus-portal): Fixed subscriber role for getting chaosengines and chaosresults
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, priority/high, size/S

#2203 Saving cluster yaml token to clusters collection
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2198 Added a template for question.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: READY TO MERGE, merge, size/S

#2205 Removed expiration from cluster-registration jwt
  litmus-portal/graphql-server/pkg/cluster/cluster_jwt.go
Labels: size/XS

#2195 chore(litmus-portal): Added cron scheduling while creation of a workflow and minor fixes
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/components/CustomText/index.tsx
  litmus-portal/frontend/src/components/DateTime/CustomDate/index.tsx
  litmus-portal/frontend/src/components/DateTime/CustomTime/index.tsx
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/redux/actions/workflow.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2183 Sync styles and themes for litmus-portal
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/components/InfoFilled/index.tsx
  litmus-portal/frontend/src/components/InputFieldOutline/index.tsx
  litmus-portal/frontend/src/components/InputFieldOutline/styles.ts
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/pages/HomePage/style.ts
  litmus-portal/frontend/src/pages/Settings/styles.ts
  litmus-portal/frontend/src/theme/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2209 Translate README.md file into Korean
  README-ko.md
Labels: Hacktoberfest, size/M

#2126 (feat Teaming): Cancel invite, Remove member, Resend Invitation
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations/project.go
  litmus-portal/graphql-server/pkg/project/create.go
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/L

#2206 Added Local Dev Script
  litmus-portal/run.sh
Labels: READY TO MERGE, size/M

#2127 Adding external cluster support for litmusportal
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/k8s/client.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/graphql-server/server.go
  litmus-portal/namespaced-K8s-template.yml
Labels: READY TO MERGE, size/L

#2213 Updated run.sh with new env vars
  litmus-portal/run.sh
Labels: size/XS

#2208 Added Air-Gapped network support in Home and Community screens
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/InfoFilled/index.tsx
  litmus-portal/frontend/src/components/InfoFilled/styles.ts
  litmus-portal/frontend/src/models/redux/analytics.ts
  litmus-portal/frontend/src/models/redux/index.ts
  litmus-portal/frontend/src/pages/Community/index.tsx
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/redux/actions/analytics.ts
  litmus-portal/frontend/src/redux/reducers/analytics.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/views/Community/CommunityTimeSeriesPlot/index.tsx
  litmus-portal/frontend/src/views/Community/GeoMap/CityMap.tsx
  litmus-portal/frontend/src/views/Community/GeoMap/CountryMap.tsx
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, kind/bug-fix, size/L

#2214 Adding uninstallation steps in LitmusPortal Readme
  litmus-portal/README.md
Labels: size/S

#2207 chore(litmus-portal): Frontend functionality for resend invitation, cancel invitation and remove member added
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/theme/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, merge, size/XL

#2216 Ignore Workflow Delete Events
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/workflow.go
Labels: size/XS

#2218 Targets screens with Graphql integration
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
  litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectHome/styles.ts
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectTarget/styles.ts
  litmus-portal/frontend/src/components/Targets/TargetCopy/index.tsx
  litmus-portal/frontend/src/components/Targets/TargetCopy/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/XL

#2219 sock-shop-readme-update
  monitoring/README.md
Labels: READY TO MERGE, size/XS

#2221 Fix for Settings route for different users with different roles.
  litmus-portal/frontend/src/components/Header/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
Labels: READY TO MERGE, size/XS

#2220 Add Chinese translation of the README.md
  README-chn.md
Labels: READY TO MERGE, size/M

#2196 sample workflow for namespaced scope installation.
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
Labels: READY TO MERGE, area/litmus-portal, kind/enhancement, merge, size/M

#2227 Added the redux state while workflow creation and fetch policy in teaming
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, size/S

#2222 Analytics compare mode for litmus-portal.
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/ProgressBar/ColouredProgressBar/index.tsx
  litmus-portal/frontend/src/graphql/quries.ts
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/pages/AnalyticsPage/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/PopOver/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonPlot/Score.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonPlot/style.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/TableHeader.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunsBarChart/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
Labels: area/litmus-portal, priority/high, size/XXL, state/dev-complete, state/review-in-progress

#2224 Adding a few minor styles changes
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunDetailsTable/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
Labels: size/XS

#2211 External Agent Graphql and Backend Integration with Table Section
  litmus-portal/frontend/public/icons/bin-red-delete.svg
  litmus-portal/frontend/public/icons/bin-red.svg
  litmus-portal/frontend/public/icons/targets.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
Labels: area/litmus-portal, size/L, state/review-in-progress

#2230 (fix)readme: remove limitation around network chaos support on containerd & crio runtime
  README.md
Labels: size/XS

#2233 Bug-fix: Replacing string to space in error condition
  litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
Labels: size/XS

#2234 Bug-fix: Adding namespace in argo chaos SA
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
Labels: size/XS

#2228 Create README-ja.md
  translations/README-ja.md
Labels: READY TO MERGE, size/M

#2232 Added endpoint for yaml fetch and refactoring of targets
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
  litmus-portal/frontend/src/components/Targets/TargetCopy/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
Labels: READY TO MERGE, size/L

#2137 chore(litmus-portal): "see more" button refactored with onClick event
  litmus-portal/frontend/src/pages/HomePage/index.tsx
Labels: READY TO MERGE, area/litmus-portal, hacktoberfest-accepted, size/S

#2237 Adding is_cluster_confimed to true, once it got confirmed
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
Labels: size/XS

#2239 Status for Targets | bug fixed
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
Labels: READY TO MERGE, merge, size/XS

#2235 Updated BetterCI Config
  .betterci/ci-k8s-manifest.yml
Labels: PR: Changes Requested, size/M

#2240 chore(litmus-portal): Fixed onKeyPressed Enter Bug
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
Labels: area/litmus-portal, kind/bug-fix, size/XS

#2241 Add netapp as a litmuchaos adopter
  ADOPTERS.md
  adopters/netapp.md
Labels: size/S

#2243 Adding "/api/" for targets manifest
  litmus-portal/frontend/src/components/Targets/TargetCopy/index.tsx
Labels: size/XS

#2247 Added pagination in footer and scrollbar in table.
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/L

#2246 (litmus-portal): Bug fixes and error handling related to analytics.
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, priority/high, size/XL, state/review-in-progress

#2248 adding create configmap permission in subscriber manifest and few refactors in subscriber
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
Labels: size/S

#2250 (litmus-portal): disabled export and analytics button
  litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, size/S

#2245 data-cy, invitation bug fix, Role visibility in manage team
  litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectHome/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
Labels: area/litmus-portal, front-end-issue, kind/bug-fix, merge, size/L

#2254 Disabled delete button in Targets & Settings, Fixed empty dropdown in…
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/TargetCopy/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
Labels: READY TO MERGE, size/M

#2255 Disable for Version, Delete Button | Added time format for Table Last Run | CSS fixes
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2253 chore(litmus-portal): Added timezone generation for cron workflows
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/M

#2256 Okteto manifest update for litmus-portal.
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: PR: Changes Requested, area/litmus-portal, kind/bug-fix, sig-integration, size/S

#2188 chore(permission): Add minimal permission for litmus-admin rbac
  docs/litmus-admin-rbac.yaml
Labels: kind/enhancement, size/XS

#2258 (litmus-portal): using downward api for portal ns
  litmus-portal/namespaced-K8s-template.yml
Labels: READY TO MERGE, area/litmus-portal, size/XS

#2268 Changing version to 1.9.x in readme
  litmus-portal/README.md
Labels: size/XS

#2266 Cherry pick from master to v1.9.x
  demo/kubecon-demo/2020-NA/integrations/.gitkeep
  demo/kubecon-demo/2020-NA/portal/.gitkeep
  docs/litmus-admin-rbac.yaml
  litmus-portal/README.md
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectHome/styles.ts
  litmus-portal/frontend/src/components/Targets/TargetCopy/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: READY TO MERGE, size/L

#2269 changing from ci to latest for v1.9.0
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: size/M

#2274 adding chaos scheduler yaml
  docs/chaos-scheduler-v1.9.0.yaml
Labels: READY TO MERGE, size/L

#2276 (litmus-portal): failed experiments bar width fix for graph
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunsBarChart/index.tsx
Labels: area/litmus-portal, kind/bug-fix, size/XS

#2280 Updating contact info
  MAINTAINERS
Labels: size/XS

#2285 monitoring update to support scrape jobs and minor bug-fix.
  monitoring/README.md
  monitoring/platforms/kublr/README.md
  monitoring/utils/prometheus/prometheus-scrape-configuration/01-prometheus-rbac.yaml
  monitoring/utils/prometheus/prometheus-scrape-configuration/02-prometheus-configMap.yaml
  monitoring/utils/prometheus/prometheus-scrape-configuration/prometheus-alert-rules.yaml
  monitoring/utils/prometheus/prometheus-scrape-configuration/prometheus-deployment.yaml
  monitoring/utils/prometheus/prometheus-scrape-configuration/prometheus-service.yaml
Labels: area/litmus, area/monitoring, kind/bug-fix, kind/feature, size/L

#2113 chore(litmus-portal): Added BreadCrumbs Unit Test
  litmus-portal/frontend/cypress/component/breadcrumb.spec.tsx
Labels: area/litmus-portal, kind/unit-test, size/M

#2229 chore(litmus-portal): Added views in translation file
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/ResultTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ToggleComponent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/Home/AverageResilienceScore/index.tsx
  litmus-portal/frontend/src/views/Home/PassedVsFailed/index.tsx
  litmus-portal/frontend/src/views/Home/TotalWorkflows/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/XXL

#2199 chore(litmus-portal): Refactor of Unimodal and Button
  litmus-portal/frontend/src/components/Button/ButtonFilled/styles.ts
  litmus-portal/frontend/src/components/Button/ButtonOutline/styles.ts
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectTarget/styles.ts
  litmus-portal/frontend/src/components/WelcomeModal/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/containers/layouts/Unimodal/index.tsx
  litmus-portal/frontend/src/containers/layouts/Unimodal/styles.ts
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/L

#2290 Minor fix for gauge count errors on sock-shop dashboard.
  monitoring/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json
Labels: area/monitoring, kind/bug-fix, size/M

#2283 Spanishtranslation2
  translations/README-es.md
Labels: size/L

#2295 Chaging ImagePullPolicy to Always for workflow executor image
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
Labels: READY TO MERGE, size/XS

#2291 Added Backend Implementation for My Hub and required graphql endpoints.
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/project.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/usermanagement.graphqls
  litmus-portal/graphql-server/pkg/database/mongodb/operations/usermanagement.go
  litmus-portal/graphql-server/pkg/database/mongodb/schema/usermanagement.go
  litmus-portal/graphql-server/pkg/myhub/gitops/gitops.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal

#2294 chore(litmus-portal): Added Myhub screens and redux setup for MyHub section
  litmus-portal/frontend/.eslintrc.json
  litmus-portal/frontend/public/icons/add-hub.svg
  litmus-portal/frontend/public/icons/my-hub-charts.svg
  litmus-portal/frontend/public/icons/myhub-crossed.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/DeveloperGuide/index.tsx
  litmus-portal/frontend/src/components/DeveloperGuide/styles.ts
  litmus-portal/frontend/src/components/QuickActionCard/index.tsx
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/VideoCarousel/index.tsx
  litmus-portal/frontend/src/components/VideoCarousel/styles.ts
  litmus-portal/frontend/src/components/VideoFrame/index.tsx
  litmus-portal/frontend/src/components/VideoFrame/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/quries.ts
  litmus-portal/frontend/src/models/graphql/charts.ts
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/models/redux/index.ts
  litmus-portal/frontend/src/models/redux/myhub.ts
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/pages/MyHub/styles.ts
  litmus-portal/frontend/src/redux/actions/myhub.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/redux/reducers/myhub.ts
  litmus-portal/frontend/src/svg/myhub.svg
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/headerSection.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/XXL

#2292 Litmus monitoring getting started guide for Kublr updated
  monitoring/platforms/kublr/README.md
  monitoring/platforms/kublr/grafana-dashboards/kubernetes/Node-and-pod-metrics-dashboard-kublr.json
  monitoring/platforms/kublr/grafana-dashboards/kubernetes/Sock-Shop-Performance-Under-Chaos.json
  monitoring/platforms/kublr/utils/README.md
  monitoring/platforms/kublr/utils/prometheus-config-template-jobs.yaml
Labels: READY TO MERGE, area/monitoring

#2287 Kubecon 2020
  demo/kubecon-demo/2020-NA/.gitignore
  demo/kubecon-demo/2020-NA/App/nginx_demo.yaml
  demo/kubecon-demo/2020-NA/Argo/argowf-chaos-admin.yaml
  demo/kubecon-demo/2020-NA/Argo/argowf-perf-chaos-admin.yaml
  demo/kubecon-demo/2020-NA/Argo/argowf-perf.yaml
  demo/kubecon-demo/2020-NA/Argo/rbac-argo-service.yaml
  demo/kubecon-demo/2020-NA/ChaosExecution/engine-nginx-count-admin.yaml
  demo/kubecon-demo/2020-NA/ChaosExecution/rbac-chaos-admin.yaml
  demo/kubecon-demo/2020-NA/ChaosExperiment/experiments-k8.yaml
  demo/kubecon-demo/2020-NA/Readme.md
  demo/kubecon-demo/2020-NA/demo.md
Labels: size/XXL

#2300 chore(v1.9.1): Adding manifests for v1.9.1
  docs/litmus-operator-v1.9.1.yaml
Labels: READY TO MERGE, size/XL

#2299 Added Endpoints for Hub Status and Repository resync support.
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/database/mongodb/schema/usermanagement.go
  litmus-portal/graphql-server/pkg/myhub/gitops/gitops.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
Labels: READY TO MERGE, size/XL

#2298 chore(litmus-portal): Added myhub experiments page and hub status on myhub cards
  litmus-portal/frontend/public/icons/guide.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/DeveloperGuide/index.tsx
  litmus-portal/frontend/src/components/DeveloperGuide/styles.ts
  litmus-portal/frontend/src/components/ExperimentHeader/index.tsx
  litmus-portal/frontend/src/components/ExperimentHeader/styles.ts
  litmus-portal/frontend/src/components/ExperimentInfo/index.tsx
  litmus-portal/frontend/src/components/ExperimentInfo/styles.ts
  litmus-portal/frontend/src/components/InstallChaos/index.tsx
  litmus-portal/frontend/src/components/InstallChaos/styles.ts
  litmus-portal/frontend/src/components/UsefulLinks/index.tsx
  litmus-portal/frontend/src/components/UsefulLinks/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/quries.ts
  litmus-portal/frontend/src/models/graphql/charts.ts
  litmus-portal/frontend/src/models/redux/myhub.ts
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/pages/MyHub/styles.ts
  litmus-portal/frontend/src/redux/reducers/myhub.ts
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/headerSection.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/XXL

#2180 Fix path collisions on case-sensitive systems
  litmus-portal/frontend/public/icons/edit.svg
Labels: READY TO MERGE, hacktoberfest-accepted, size/XS

#2288 chore(update): user cluster registration schema
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/manifests/cluster-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
  litmus-portal/graphql-server/utils/misc.go
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2304 Added Kublr space/cluster selector in the monitoring dashboards
  monitoring/platforms/kublr/README.md
  monitoring/platforms/kublr/grafana-dashboards/kubernetes/Node-and-pod-metrics-dashboard-kublr.json
  monitoring/platforms/kublr/grafana-dashboards/kubernetes/Sock-Shop-Performance-Under-Chaos.json
Labels: READY TO MERGE, area/monitoring, merge, sig-integration

#2286 Spelling error
  CODE_OF_CONDUCT.md
Labels: Hacktoberfest, hacktoberfest-accepted, size/XS

#2177 Update README.md
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted, size/XS

#2281 German readme
  translations/README-ge.md
Labels: Hacktoberfest, READY TO MERGE, hacktoberfest-accepted, size/L
