Repository litmuschaos/litmus, pull requests merged in 2021-07, with the labels that each got.

#2954 Added engine context in chaos data
  litmus-portal/cluster-agents/subscriber/go.mod
  litmus-portal/cluster-agents/subscriber/pkg/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/types/event.go
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/graphql-server/pkg/chaos-workflow/types.go
Labels: READY TO MERGE, Testing-done, size/XS

#2955 Added active agent count to usage stats
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/usage.graphqls
  litmus-portal/graphql-server/pkg/usage/status.go
  litmus-portal/graphql-server/pkg/usage/types.go
Labels: size/M

#2953 Fixed bug in update/details api
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/go.mod
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/authentication/pkg/user/service.go
  litmus-portal/run.sh
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2956 Litmus UI version update 1.3.1
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/pages/ApplicationDashboard/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/Panel/PanelContent.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/Panel/PanelGroupContent.tsx
Labels: READY TO MERGE, area/monitoring, size/M, state/review-in-progress

#2958 chore(litmus-portal): Added env tunables, date range for usage stats and fixed logs issue
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/UsageStatistics/datePicker.tsx
  litmus-portal/frontend/src/pages/UsageStatistics/index.tsx
  litmus-portal/frontend/src/pages/UsageStatistics/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/EnvironmentVariables.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
  litmus-portal/frontend/src/views/UsageStatistics/UsageStats/index.tsx
  litmus-portal/frontend/src/views/UsageStatistics/UsageTable/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/XL

#2960 Workflow runs details
  litmus-portal/frontend/public/icons/failedTestIndicator.svg
  litmus-portal/frontend/public/icons/hide.svg
  litmus-portal/frontend/public/icons/passedTestIndicator.svg
  litmus-portal/frontend/public/icons/resilienceGraph.svg
  litmus-portal/frontend/public/icons/resiliencyScoreIndicators.svg
  litmus-portal/frontend/public/icons/show.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/colors/graphColors.ts
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/chaosWorkflowYaml.ts
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/pages/WorkflowAnalytics/index.tsx
  litmus-portal/frontend/src/pages/WorkflowAnalytics/styles.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/WorkflowStats/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/WorkflowStats/styles.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/styles.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/StackedBar/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/StackedBar/styles.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/TableData.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/TableHeader.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/TableToolbar.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/styles.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/styles.ts
  litmus-portal/frontend/src/svg/analytics-sidebar.svg
  litmus-portal/frontend/src/svg/usage.svg
  litmus-portal/frontend/src/svg/workflows.svg
  litmus-portal/frontend/src/views/Analytics/Overview/ApplicationDashboardCard/index.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/WorkflowDashboardCard/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/PopOver/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/PopOver/styles.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/style.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
Labels: READY TO MERGE, area/chaos-analytics, area/litmus-portal, merge, size/XXL

#2968 add KubeSphere to ADOPTERS.md
  ADOPTERS.md
Labels: size/XS

#2970 [chore] Updating latest addition in Chronological order
  ADOPTERS.md
Labels: size/XS

#2971 (chore)maintainers: update maintainers email id
  MAINTAINERS
Labels: READY TO MERGE, size/XS

#2964 Disable and Enable user from auth
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/api/middleware/jwt_middlware.go
  litmus-portal/authentication/api/routes/user_router.go
  litmus-portal/authentication/go.sum
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/authentication/pkg/user/service.go
  litmus-portal/authentication/pkg/utils/errors.go
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2972 (chore)governance: add newer maintainers and reviewers
  GOVERNANCE.md
  MAINTAINERS
Labels: READY TO MERGE, size/M

#2973 (chore)roadmap: update roadmap based on latest developments
  ROADMAP.md
Labels: READY TO MERGE, size/M

#2975 Updated the image tags for workflow controller and executor to v2.11.0.
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: PR: Changes Requested, size/S

#2920 Chore(RBAC): minimize and explain the admin rbac and operator permissions
  docs/2.0.0-Beta4/litmus-2.0.0-Beta4.yaml
  docs/2.0.0-Beta4/litmus-namespaced-2.0.0-Beta4.yaml
  docs/litmus-admin-rbac.yaml
  docs/litmus-operator-v1.13.6.yaml
  litmus-portal/README.md
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: PR: Changes Requested, READY TO MERGE, size/XL

#2979 typo in 3a_agent_rbac
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
Labels: size/XS

#2977 type(update): Adding data-cy for E2E and fixing Edit Scheduile View YAML
  litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/pages/EditSchedule/styles.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
Labels: READY TO MERGE, size/L

#2974 Added Code-splitting at components level.
  litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/components/SuspenseLoader/index.tsx
  litmus-portal/frontend/src/components/UnconfiguredAgent/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/pages/ConfigureDataSources/index.tsx
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
  litmus-portal/frontend/src/views/Home/ProjectInfoContainer/index.tsx
Labels: READY TO MERGE, size/L

#2981 Cleanup(.gitlab-ci.yml): Remove .gitlab-ci.yml as we're not using GitLab for CI
  .gitlab-ci.yml
Labels: size/M

#2982 Added Omar Hanafi
  ADOPTERS.md
Labels: READY TO MERGE, size/XS

#2989 Upgrading event tracking k8s pkg to 0.20.1 and goversion to 1.16
  litmus-portal/cluster-agents/event-tracker/controllers/eventtrackerpolicy_controller.go
  litmus-portal/cluster-agents/event-tracker/go.mod
  litmus-portal/cluster-agents/event-tracker/go.sum
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
Labels: size/S

#2984 Added minimal RBAC for agents in Namespace Mode.
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: size/L

#2978 chore(litmus-portal): Updated probes ui, fixed node selector issue in chaos engine and fixed image registry issue
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/redux/image_registry.ts
  litmus-portal/frontend/src/redux/reducers/image_registry.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbesMenu.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/comparatorTypes.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts
  litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/image_registry.graphqls
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/pkg/database/mongodb/image_registry/schema.go
  litmus-portal/graphql-server/pkg/image_registry/ops/image_registry.go
  litmus-portal/graphql-server/pkg/project/create.go
Labels: READY TO MERGE, area/litmus-portal, kind/enhancement, size/XL

#2976 Adding non-empty and duplicate project name check to create project mutation
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/project/create.go
Labels: size/M

#2993 upgrading goversion to 1.16
  litmus-portal/authentication/Dockerfile
  litmus-portal/cluster-agents/event-tracker/Dockerfile
  litmus-portal/cluster-agents/subscriber/Dockerfile
  litmus-portal/cluster-agents/subscriber/go.mod
  litmus-portal/graphql-server/Dockerfile
  litmus-portal/graphql-server/go.mod
Labels: READY TO MERGE, size/XS

#2985 (analytics): Backend enhancements for editing event query, patching verdict to event data and subscription for viewing application dashboards
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/operations.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/prometheus.go
  litmus-portal/graphql-server/pkg/analytics/types.go
  litmus-portal/graphql-server/pkg/data-store/store.go
  litmus-portal/graphql-server/utils/cache.go
  litmus-portal/graphql-server/utils/misc.go
Labels: READY TO MERGE, Testing-done, area/chaos-analytics, area/litmus-portal, area/monitoring, merge, size/XXL

#2997 fix: auth server: cors issue
  litmus-portal/authentication/api/main.go
Labels: READY TO MERGE, size/XS

#2992 type(performance): ⚡️ Optimized Scaffold and increased Performance⚡️
  litmus-portal/frontend/src/components/BreadCrumbs/index.tsx
  litmus-portal/frontend/src/components/Header/index.tsx
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/config/index.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/containers/layouts/Wrapper/index.tsx
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/pages/ApplicationDashboard/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/pages/ChooseAndConfigureDashboards/index.tsx
  litmus-portal/frontend/src/pages/Community/index.tsx
  litmus-portal/frontend/src/pages/ConfigureDataSources/index.tsx
  litmus-portal/frontend/src/pages/ConnectTarget/index.tsx
  litmus-portal/frontend/src/pages/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/pages/ErrorPage/index.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/pages/Targets/index.tsx
  litmus-portal/frontend/src/pages/UsageStatistics/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
Labels: READY TO MERGE, size/L

#3000 Add node selector field in UserClusterReg Mutation
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/server.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/M

#2988 (Litmus-Portal): Community action shifted to community page and fixed the loaders.
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/pages/Community/index.tsx
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
Labels: READY TO MERGE, merge, size/M

#3001 Upgraded myhub package to latest and minor change in myhub api
  litmus-portal/frontend/src/ReduxRoot.tsx
  litmus-portal/frontend/src/config/index.ts
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
Labels: READY TO MERGE, size/L

#3010 Adding rbac permissions for predefined workflow
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: size/S

#3007 Updated version labels to v1.13.6 in RBAC and Deployment for litmus.
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
Labels: READY TO MERGE, size/S

#3012 API integration for fetching application dashboards from hub and added viewed at field on frontend for application dashboards
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/PreconfiguredDashboards/data.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/graphql/subscriptions.ts
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/models/graphql/dashboardsDetails.ts
  litmus-portal/frontend/src/models/graphql/prometheus.ts
  litmus-portal/frontend/src/pages/ApplicationDashboard/constants.ts
  litmus-portal/frontend/src/pages/ApplicationDashboard/index.tsx
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/ChooseADashboardType/Cards/DashBoardCards.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/ChooseADashboardType/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/ConfigureDashboardMetadata/Form/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/index.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/ApplicationDashboardCard/index.tsx
Labels: READY TO MERGE, Testing-done, area/chaos-analytics, area/litmus-portal, kind/bug-fix, kind/feature, size/L

#2880 chore (Litmus-Portal) : Updated E2E GitHub Action Worflow
  .github/BUILD_IMAGE.md
  .github/filter_and_build.sh
  .github/workflows/e2e.yml
Labels: READY TO MERGE, size/L

#2987 Add Mercedes as Adopter
  ADOPTERS.md
  adopters/organizations/mercedes.md
Labels: size/S

#2999 Workflow query optimisation
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
Labels: size/XXL

#3013 Restructure adopters based on organization type
  ADOPTERS.md
  USERS.md
Labels: size/M

#3011 Added viewed_at field for application dashboards
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go
Labels: Testing-done, area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/L

#2980 Deactivate user auth
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/api/main.go
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/icons/UserDisable.svg
  litmus-portal/frontend/public/icons/UserEnable.svg
  litmus-portal/frontend/public/icons/deleteBin.svg
  litmus-portal/frontend/public/icons/removeMember.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/invite.ts
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/pages/GetStartedPage/index.tsx
  litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTable.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/removeMemberModal.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/tableData.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/project.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/usermanagement.graphqls
  litmus-portal/graphql-server/pkg/authorization/validate.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/schema.go
  litmus-portal/graphql-server/pkg/project/create.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: DO NOT MERGE, PR: Changes Requested, size/XXL

#3014 type(fix): 👷 Fixed CSS + Updated translations in stats page and fixed icon issue for predefined workflows 🔥🚀
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/InstallChaos/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/PreDefinedRadio.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/styles.ts
Labels: size/L

#3015 Bug fixes for portal dashboards
  monitoring/portal-dashboards/node_metrics.json
  monitoring/portal-dashboards/pod_metrics.json
  monitoring/portal-dashboards/sock-shop.json
Labels: READY TO MERGE, area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/M

#3016 Bug fixes for dashboard page queries
  litmus-portal/frontend/src/pages/ChooseAndConfigureDashboards/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/ChooseADashboardType/index.tsx
Labels: area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/M

#3017 chore(manifests): Removing privilege permissions from cluster-k8s-manifests
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: READY TO MERGE, size/XL

#3018 (portal-analytics): Bug fix for dashboard list and workflow comparison table
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/ChooseADashboardType/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
Labels: READY TO MERGE, area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/L

#3020 chore(manifest): Remove privilege permissions from the namespace deployment manifests
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: DO NOT MERGE, READY TO MERGE, size/XL

#3021 Updating chaos-cluster-role and chaos-role permissions(rbac) for pre-defined workflow
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: PR: Changes Requested, size/S

#3019 Added Matrix startegy for path-based frontend builds
  .github/filter_and_build.sh
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/push.yml
  litmus-portal/frontend/src/components/UnconfiguredAgent/index.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
Labels: READY TO MERGE, size/L

#3004 Added Cloud Native Chaos Engineering Deck
  resources/Cloud_Native_Chaos_Engineering.md
Labels: kind/docs, size/S

#3022 updating rbac permissions for the operator
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
Labels: size/XS

#2961 feat(rbac): adding minimal rbac permissions for scheduler and update crd version to v1
  docs/chaos-scheduler-v1.13.6.yaml
Labels: size/XL

#3026 (Litmus-Portal): Updated the control-plane to Beta-9.
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/README.md
Labels: size/M

#3028 Adding RBAC in 2.0.0-Beta manifests
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: size/XL

#3029 Updated images for Argo workflow controller and executor to v2.11.0
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/run.sh
Labels: size/S

#3024 adding manifests for the 1.13.8
  docs/chaos-scheduler-v1.13.8.yaml
  docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  docs/litmus-operator-v1.13.8.yaml
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#3031 Fixed updating experiment states in db bug
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go
Labels: READY TO MERGE, size/XS

#3034 chore(rbac-fix): Fixing rbac for ingress
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/XS

#3032 Add Pravega as Adopter
  ADOPTERS.md
  adopters/organizations/pravega.md
Labels: READY TO MERGE, size/S

#3023 beta 9 bug fixes
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTable.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/tableData.tsx
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: READY TO MERGE

#3033 Adding Openshift platform adopter
  ADOPTERS.md
  adopters/organizations/redhat_kraken.md
Labels: READY TO MERGE, size/S

#3041 Shifted agent dependency list to server env
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/server.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/S

#3039 Community page refactor
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/icons/communityMeetup.svg
  litmus-portal/frontend/public/icons/feedback.svg
  litmus-portal/frontend/public/icons/github.svg
  litmus-portal/frontend/public/icons/medium.svg
  litmus-portal/frontend/public/icons/meetup.svg
  litmus-portal/frontend/public/icons/twitter.svg
  litmus-portal/frontend/public/icons/youtube.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
  litmus-portal/frontend/src/pages/Community/index.tsx
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/svg/code.svg
  litmus-portal/frontend/src/svg/downloadGreen.svg
  litmus-portal/frontend/src/svg/slack.svg
  litmus-portal/frontend/src/svg/workflowsPurple.svg
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowRunsBarChart/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowRunsBarChart/styles.ts
  litmus-portal/frontend/src/views/Community/CommunityCards/index.tsx
  litmus-portal/frontend/src/views/Community/CommunityCards/style.ts
  litmus-portal/frontend/src/views/Community/CommunityFooter/index.tsx
  litmus-portal/frontend/src/views/Community/CommunityFooter/style.ts
  litmus-portal/frontend/src/views/Community/CommunityTimeSeriesPlot/index.tsx
  litmus-portal/frontend/src/views/Community/CommunityTimeSeriesPlot/styles.ts
  litmus-portal/frontend/src/views/Community/InfoFilled/index.tsx
  litmus-portal/frontend/src/views/Community/InfoFilled/styles.ts
Labels: READY TO MERGE, Testing-done, area/community, kind/refactor, size/XXL

#3025 Add API Route /status into authn-server
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/api/routes/user_router.go
  litmus-portal/authentication/pkg/entities/user.go
Labels: PR: Changes Requested, size/S

#3044 Renaming "litmusctl agent connect" to "litmusctl create agent" in the UI
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/views/Targets/TargetCopy/index.tsx
Labels: READY TO MERGE, size/XS

#3040 type(Improvement): Improved i18n + Added minor Fixes to Workflow N/A and CSS
  litmus-portal/frontend/public/manifest.json
  litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
  litmus-portal/frontend/src/i18n.js
  litmus-portal/frontend/src/pages/Community/index.tsx
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/Workflows/styles.ts
Labels: READY TO MERGE, kind/refactor, size/M

#3046 Fix ingress logic
  litmus-portal/graphql-server/pkg/k8s/cluster.go
Labels: READY TO MERGE, kind/bug-fix, size/S

#3051 type(rebranding): Updated LoginPage and workflow content
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Header/index.tsx
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/pages/GetStartedPage/index.tsx
  litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/pages/Targets/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
Labels: size/L

#3052 Removing resource limits from namespace manifests
  .betterci/README.md
  litmus-portal/namespaced-k8s-template.yml
Labels: size/S

#3047 type(api-docs): Added API docs with the updated Litmus Portal apis
  docs/api.html
  docs/config.yml
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-docs, kind/docs

#3056 type(color-fix): Update Argo colors to take from Theme
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
Labels: size/S

#3057 Adding vulnerability scanner in the github workflows (codeql-analysis)
  .github/workflows/codeql-analysis.yml
Labels: READY TO MERGE, size/M

#3054 Added separate struct to for /update/details API
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/authentication/pkg/user/service.go
  litmus-portal/frontend/src/pages/GetStartedPage/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, size/M

#3059 Add Klanik as adopter and a brief of our story
  ADOPTERS.md
  adopters/organizations/klanik.md
Labels: size/S

#3058 Migrated from github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt
  litmus-portal/authentication/api/middleware/jwt_middlware.go
  litmus-portal/authentication/go.mod
  litmus-portal/authentication/go.sum
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/authorization/user_jwt.go
  litmus-portal/graphql-server/pkg/authorization/validate.go
  litmus-portal/graphql-server/pkg/cluster/cluster_jwt.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/run.sh
Labels: PR: Changes Requested, READY TO MERGE, size/S

#3062 (Litmus-Portal): Updated CRs versions to v1.13.8.
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: PR: Changes Requested, READY TO MERGE, size/M

#3063 added terminate workflow mutation
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: READY TO MERGE, size/L

#3065 Text corrections and unneeded key removal
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/TuneTheQueries/EditPanelsWizard/index.tsx
Labels: area/chaos-analytics, size/S, translation

#3061 Schema for app. / infra monitoring dashboards on chaos center
  monitoring/portal-dashboards/schema.json
Labels: area/chaos-analytics, area/litmus-docs, area/litmus-portal, size/L

#3068 Optimized the usage stats db query
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/usage/status.go
Labels: READY TO MERGE, size/S

#3069 removed terminated and in-complete workflows from workflow analytics
  litmus-portal/frontend/public/index.html
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
Labels: PR: Changes Requested, READY TO MERGE, size/M

#3071 Analytics UI fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/WorkflowStats/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/TableData.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/TableToolbar.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/ExperimentStatus/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/style.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
Labels: READY TO MERGE, size/L
