Repository litmuschaos/litmus, pull requests merged in 2021-08, with the labels that each got.

#3070 chore(chaos-center): Added terminate workflow functionality and updated probes feature
  litmus-portal/frontend/public/icons/status-terminated.svg
  litmus-portal/frontend/public/icons/terminate-wf-dark.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/workflowConstants.ts
Labels: READY TO MERGE, kind/enhancement, size/L

#3072 area(ChaosAgents): Added Agent Type in ChaosAgents Table
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/styles.ts
Labels: size/M

#3073 chore(chaos-center): Updated default hub name to Litmus ChaosHub
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/ApplicationDashboard/constants.ts
  litmus-portal/frontend/src/pages/ChaosHub/customMyHubCard.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/graphql-server/pkg/project/create.go
Labels: READY TO MERGE, size/S

#3074 WorkflowRun Table fixes (Analytics)
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/workflow.graphqls
Labels: READY TO MERGE, size/L

#3079 litmus ui version update
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: READY TO MERGE, Testing-done, size/XS

#3080 Style fix tool tip overflow and margin fix for all pages
  litmus-portal/frontend/src/components/BreadCrumbs/styles.ts
  litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
  litmus-portal/frontend/src/pages/AnalyticsPage/styles.ts
  litmus-portal/frontend/src/pages/ApplicationDashboard/index.tsx
  litmus-portal/frontend/src/pages/ApplicationDashboard/styles.ts
  litmus-portal/frontend/src/pages/ChaosHub/styles.ts
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/pages/ConnectTarget/index.tsx
  litmus-portal/frontend/src/pages/ConnectTarget/styles.ts
  litmus-portal/frontend/src/pages/HomePage/styles.ts
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/pages/Settings/styles.ts
  litmus-portal/frontend/src/pages/Targets/index.tsx
  litmus-portal/frontend/src/pages/Targets/styles.ts
  litmus-portal/frontend/src/pages/UsageStatistics/styles.ts
  litmus-portal/frontend/src/pages/Workflows/styles.ts
Labels: Testing-done, size/M

#3078 Adding namespace scope support for eventtracker controller
  litmus-portal/cluster-agents/event-tracker/config/example_cr/eventtracker_policy.yaml
  litmus-portal/cluster-agents/event-tracker/main.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
Labels: READY TO MERGE, size/M

#3081 Update README.md
  README.md
Labels: READY TO MERGE, size/S

#3076 chore(chaos-center): Added workflow status and updated agents table
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/statusText.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
Labels: READY TO MERGE, size/L

#3082 Fixing codeql bug
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
Labels: READY TO MERGE, size/XS

#3084 adding docs to the github pages
  .github/workflows/gh-pages.yaml
Labels: size/S

#3085 Bug fixes for analytics and translations for 2.0
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/ApplicationDashboard/index.tsx
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/ChaosAnnotationsEditor/QueryEditor/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/InfoDropdown/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/PanelAndGroup/Panel.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/PanelAndGroup/PanelGroup.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/PanelAndGroup/styles.ts
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/TopNavButtons/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/ConfigureDashboardMetadata/Form/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/TuneTheQueries/EditPanelsWizard/QueryEditingWizard/QueryEditor/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/ApplicationDashboardCard/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Community/CommunityCards/index.tsx
Labels: READY TO MERGE, Testing-done, area/litmus-portal, kind/bug-fix, size/L

#3090 Adding black-box exporter and scrape job, service monitor with updates to litmus version and exporter manifests
  monitoring/README.md
  monitoring/platforms/kublr/README.md
  monitoring/utils/metrics-exporters-with-service-monitors/kube-state-metrics/deployment.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/kube-state-metrics/service-monitor.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/litmus-metrics/chaos-exporter/chaos-exporter.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/litmus-metrics/chaos-exporter/service-monitor.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/mysqld-exporter/deployment.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/mysqld-exporter/service-monitor.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/node-exporter/daemonset.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/node-exporter/service-monitor.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/configmap.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/deployment.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/service-monitor.yaml
  monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/service.yaml
  monitoring/utils/metrics-exporters/kube-state-metrics/deployment.yaml
  monitoring/utils/metrics-exporters/litmus-metrics/chaos-exporter/chaos-exporter.yaml
  monitoring/utils/metrics-exporters/mysqld-exporter/deployment.yaml
  monitoring/utils/metrics-exporters/node-exporter/daemonset.yaml
  monitoring/utils/metrics-exporters/prometheus-blackbox-exporter-metrics/configmap.yaml
  monitoring/utils/metrics-exporters/prometheus-blackbox-exporter-metrics/deployment.yaml
  monitoring/utils/metrics-exporters/prometheus-blackbox-exporter-metrics/service.yaml
  monitoring/utils/prometheus/prometheus-configuration/prometheus.yaml
  monitoring/utils/prometheus/prometheus-scrape-configuration/02-prometheus-configMap.yaml
Labels: area/chaos-exporter, area/monitoring, size/L

#3091 Adding named ports and labels to chaos exporter deployments for monitoring automation
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
Labels: READY TO MERGE, Testing-done, area/litmus-portal, area/monitoring, size/S

#3089 Fixing logs of event tracker
  litmus-portal/cluster-agents/event-tracker/main.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
Labels: size/S, READY TO MERGE

#3095 adding pod-namespace in operator manifest
  docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.13.8.yaml
Labels: size/S

#3077 (Litmus-Portal): Fixed the issue in deletion of chaosengines.
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
Labels: size/XS, READY TO MERGE

#3083 (Litmus-Portal): Changed the litmus version to v2.0.0-RC1
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: size/L, PR: Changes Requested

#3098 Added checks to prevent DB inconsistency
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/api/routes/user_router.go
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/authentication/pkg/user/service.go
  litmus-portal/frontend/src/pages/GetStartedPage/index.tsx
Labels: DO NOT MERGE, size/M, PR: Changes Requested, READY TO MERGE

#3100 (Litmus-Portal): Updated the Readme.md raw links for Beta to Branch specific links.
  litmus-portal/README.md
Labels: size/XS, PR: Changes Requested, READY TO MERGE

#3099 (Litmus-Portal): Fixed RBAC in Beta9 branch
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
Labels: READY TO MERGE, size/XL

#3087 Added version checks in server and agents
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
  litmus-portal/cluster-agents/subscriber/pkg/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/events/workflow.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/log.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/objects.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/cluster/util.go
  litmus-portal/graphql-server/pkg/database/mongodb/collection.go
  litmus-portal/graphql-server/pkg/database/mongodb/config/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/config/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/server.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: size/L, READY TO MERGE

#3101 added version env check in event-tracker
  litmus-portal/cluster-agents/event-tracker/main.go
  litmus-portal/graphql-server/server.go
Labels: size/XS

#3093 chore(chaos-center): Changed nodeSelectors to nodeSelector in target application
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
Labels: kind/bug-fix, size/S, READY TO MERGE

#3103 Adding delete permission to the manifest for deleting the subscriber
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/M, READY TO MERGE

#3104 Permission fix in docs/2.0.0-manifests
  docs/2.0.0/litmus-2.0.0.yaml
  docs/2.0.0/litmus-namespaced-2.0.0.yaml
Labels: size/XS

#3105 type(docs): Updated API docs to v2.0.0
  docs/auth/logo.png
  docs/auth/v2.0.0/api.html
  docs/graphql/config.yml
  docs/graphql/javascripts/spectacle.js
  docs/graphql/javascripts/spectacle.min.js
  docs/graphql/logo.png
  docs/graphql/stylesheets/foundation.css
  docs/graphql/stylesheets/foundation.min.css
  docs/graphql/stylesheets/spectacle.css
  docs/graphql/stylesheets/spectacle.min.css
  docs/graphql/v2.0.0/api.html
  litmus-portal/frontend/src/components/DeveloperGuide/index.tsx
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
Labels: size/XS, READY TO MERGE

#3106 type(docs): Fixed docs versioning 📖
  docs/auth/v2.0.0/api.html
  docs/auth/v2.0.0/public/javascripts/spectacle.js
  docs/auth/v2.0.0/public/javascripts/spectacle.min.js
  docs/auth/v2.0.0/public/stylesheets/foundation.css
  docs/auth/v2.0.0/public/stylesheets/foundation.min.css
  docs/auth/v2.0.0/public/stylesheets/spectacle.css
  docs/auth/v2.0.0/public/stylesheets/spectacle.min.css
  docs/auth/v2.0.0/swagger.yml
  docs/graphql/v2.0.0/api.html
  docs/graphql/v2.0.0/config.yml
  docs/graphql/v2.0.0/javascripts/spectacle.js
  docs/graphql/v2.0.0/javascripts/spectacle.min.js
  docs/graphql/v2.0.0/stylesheets/foundation.css
  docs/graphql/v2.0.0/stylesheets/foundation.min.css
  docs/graphql/v2.0.0/stylesheets/spectacle.css
  docs/graphql/v2.0.0/stylesheets/spectacle.min.css
  docs/logo.png
Labels: READY TO MERGE

#3116 Create Commercial Support.md
  Commercial Support.md
Labels: size/XS

#3122 (Litmus-Portal): Added Installation Manifests for 2.0.0
  litmus-portal/README.md
  mkdocs/docs/2.0.0/litmus-2.0.0.yaml
  mkdocs/docs/2.0.0/litmus-namespaced-2.0.0.yaml
Labels: size/M, READY TO MERGE

#3123 Added Updated Installation Manifests in 2.0.0 branch.
  docs/2.0.0/litmus-2.0.0.yaml
  docs/2.0.0/litmus-namespaced-2.0.0.yaml
  litmus-portal/README.md
Labels: size/M

#3124 feat(experiment): updating collapsable items
  mkdocs/docs/experiments/categories/contents.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/application-details.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/contents.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/engine-state.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/experiment-components.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/rbac-details.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/runner-components.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/runtime-details.md
  mkdocs/docs/experiments/chaos-resources/probes/cmdProbe.md
  mkdocs/docs/experiments/chaos-resources/probes/contents.md
  mkdocs/docs/experiments/chaos-resources/probes/httpProbe.md
  mkdocs/docs/experiments/chaos-resources/probes/k8sProbe.md
  mkdocs/docs/experiments/chaos-resources/probes/promProbe.md
  mkdocs/docs/experiments/troubleshooting/experiments.md
  mkdocs/mkdocs.yml
  mkdocs/overrides/home.html
Labels: size/S

#3125 Updating the chaoscenter readme
  litmus-portal/README.md
Labels: size/XS

#3126 Faq for bank of anthos workflow
  mkdocs/docs/experiments/faq/portal.md
Labels: size/S, READY TO MERGE

#3127 (docs): fixing the list items rendering issue
  mkdocs/docs/experiments/categories/pods/container-kill.md
  mkdocs/docs/experiments/categories/pods/pod-cpu-hog-exec.md
  mkdocs/docs/experiments/categories/pods/pod-cpu-hog.md
  mkdocs/docs/experiments/categories/pods/pod-delete.md
  mkdocs/docs/experiments/categories/pods/pod-dns-error.md
  mkdocs/docs/experiments/categories/pods/pod-dns-spoof.md
  mkdocs/docs/experiments/categories/pods/pod-io-stress.md
  mkdocs/docs/experiments/categories/pods/pod-memory-hog-exec.md
  mkdocs/docs/experiments/categories/pods/pod-memory-hog.md
  mkdocs/docs/experiments/categories/pods/pod-network-corruption.md
  mkdocs/docs/experiments/categories/pods/pod-network-duplication.md
  mkdocs/docs/experiments/categories/pods/pod-network-latency.md
  mkdocs/docs/experiments/categories/pods/pod-network-loss.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/application-details.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/experiment-components.md
  mkdocs/docs/experiments/chaos-resources/chaos-engine/runner-components.md
  mkdocs/docs/experiments/faq/portal.md
  mkdocs/docs/experiments/troubleshooting/portal.md
Labels: size/M

#3128 (docs): Adding the chaos-scheduler docs and examples
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/contents.md
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/engine-specification.md
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/once/immediate.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/once/specific-time.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/basic-schema.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/just-endtime.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/just-starttime.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/time-range.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/work-days.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/work-hours.yaml
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/schedule-once.md
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/schedule-repeat.md
  mkdocs/docs/experiments/chaos-resources/chaos-scheduler/state.md
  mkdocs/mkdocs.yml
Labels: DO NOT MERGE, size/XXL

#3129 (docs): Adding manifest for 2.0.0 operator and scheduler
  mkdocs/docs/chaos-scheduler-v2.0.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.0.0.yaml
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#3131 Updated CONTRIBUTING Docs
  CONTRIBUTING.md
Labels: kind/docs, size/L

#3135 Added Litmus 2.0 slide in Github resources
  resources/Litmus_2.0_Chaos_Engineering_Journey.md
Labels: size/S

#3138 (docs): fixed the embedmd broken links
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/application-details.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/jobcleanup-policy.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-state.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/rbac-details.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runtime-details.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/contents.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/contents.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/engine-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/schedule-once.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/schedule-repeat.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/state.md
  mkdocs/docs/experiments/concepts/chaos-resources/contents.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/cmdProbe.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/httpProbe.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/k8sProbe.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/litmus-probes.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/promProbe.md
Labels: size/L, READY TO MERGE

#3139 (readme-fix): Updating chaos operator flow image on readme
  images/chaos-operator-flow.png
Labels: area/community, kind/bug-fix, READY TO MERGE

#3097 type(bugfix): Updated the Algorithm for Steps Verification
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
Labels: DO NOT MERGE, kind/bug-fix, size/S

#3137 area(Login): Creating a shared component for Login
  litmus-portal/frontend/src/pages/GetStartedPage/index.tsx
  litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/views/Login/index.tsx
  litmus-portal/frontend/src/views/Login/styles.ts
Labels: kind/refactor, size/L, READY TO MERGE

#3109 Adding checks for invalid or duplicate chaos injection events and verdicts
  litmus-portal/frontend/src/pages/MonitoringDashboard/constants.ts
  litmus-portal/graphql-server/pkg/analytics/ops/operations.go
  monitoring/portal-dashboards/schema.json
  monitoring/utils/metrics-exporters-with-service-monitors/litmus-metrics/chaos-exporter/service-monitor.yaml
  monitoring/utils/prometheus/prometheus-scrape-configuration/02-prometheus-configMap.yaml
Labels: area/litmus-portal, area/monitoring, kind/bug-fix, size/S, READY TO MERGE, Testing-done

#3145 type(Icon): Updating Icons to LitmusUI for a few components
  litmus-portal/frontend/src/components/AdjustedWeights/index.tsx
  litmus-portal/frontend/src/components/AdjustedWeights/styles.ts
  litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/components/AgentDeployModal/styles.ts
  litmus-portal/frontend/src/components/Button/BackButton/index.tsx
  litmus-portal/frontend/src/components/DeveloperGuide/index.tsx
  litmus-portal/frontend/src/components/DeveloperGuide/styles.ts
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
Labels: size/L

#3151 Added control plane upgrade agent
  litmus-portal/upgrade-agents/control-plane/Dockerfile
  litmus-portal/upgrade-agents/control-plane/go.mod
  litmus-portal/upgrade-agents/control-plane/go.sum
  litmus-portal/upgrade-agents/control-plane/main.go
  litmus-portal/upgrade-agents/control-plane/pkg/database/connection.go
  litmus-portal/upgrade-agents/control-plane/pkg/database/constants.go
  litmus-portal/upgrade-agents/control-plane/pkg/database/server-config.go
  litmus-portal/upgrade-agents/control-plane/upgrade-agent.t.yaml
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
  litmus-portal/upgrade-agents/control-plane/versions/v2.0.1/auth.go
  litmus-portal/upgrade-agents/control-plane/versions/v2.0.1/manager.go
  litmus-portal/upgrade-agents/control-plane/versions/version-manger.go
Labels: size/L, PR: Changes Requested

#3150 Videos section
  README.md
Labels: size/XS

#3149 type(ux): Changed Revert Chaos to Cleanup Chaos Resources
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: UI/UX, size/M, READY TO MERGE

#3159 added upgrade agent build to ci
  .github/workflows/build.yml
  .github/workflows/push.yml
  litmus-portal/Makefile
  litmus-portal/upgrade-agents/control-plane/main.go
Labels: size/M

#3140 (docs): adding troubleshooting docs for istio enabled ns
  mkdocs/docs/experiments/categories/common/common-tunables-for-all-experiments.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/litmus-probes.md
  mkdocs/docs/experiments/faq/ci-cd.md
  mkdocs/docs/experiments/faq/experiments.md
  mkdocs/docs/experiments/faq/scheduler.md
  mkdocs/docs/experiments/troubleshooting/experiments.md
  mkdocs/docs/experiments/troubleshooting/portal.md
  mkdocs/docs/index.md
  mkdocs/mkdocs.yml
  mkdocs/overrides/home.html
Labels: size/L, READY TO MERGE

#3154 Update README.md
  README.md
Labels: size/XS

#3163 type(Icons Update): Updated Icons for Header, InfoToolTip, InstallChaos Components
  litmus-portal/frontend/src/components/Header/ProjectDropDownItems.tsx
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/components/InfoTooltip/index.tsx
  litmus-portal/frontend/src/components/InputFieldOutline/index.tsx
  litmus-portal/frontend/src/components/InputFieldOutline/styles.ts
  litmus-portal/frontend/src/components/InstallChaos/index.tsx
  litmus-portal/frontend/src/components/InstallChaos/styles.ts
Labels: READY TO MERGE, size/XL

#3164 area(ConfigurationStepper): Fixed Configuration Wizard Open Alert Issue
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/S, READY TO MERGE

#3167 Added initContainer in server deployment to wait for MongoDB.
  litmus-portal/cluster-k8s-manifest.yml
Labels: size/XS, PR: Changes Requested, READY TO MERGE

#3168 Update un-installation section
  litmus-portal/README.md
Labels: size/S, READY TO MERGE

#3169 area(Uninstall): Updated Uninstallation Doc link
  litmus-portal/README.md
Labels: area/litmus-docs, size/M

#3165 types(ux): Added view workflow runs from schedules table and edit icon in create workflow table
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: kind/enhancement, size/L, READY TO MERGE

#3179 Add Neudesic as an adopter.
  ADOPTERS.md
  adopters/organizations/neudesic.md
Labels: size/S, READY TO MERGE

#3175 type(ux): Added view manifest in runs table and alert for re-run workflow errors
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/components/YamlEditor/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/ManifestModal.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: size/L, UI/UX, READY TO MERGE

#3173 area(Probe): Add Probe Editing functionality
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
Labels: size/L, READY TO MERGE

#3180 fixed db version nil issue
  litmus-portal/graphql-server/server.go
Labels: size/XS

#3181 type(ux): Added prompt while copying in myhub section
  litmus-portal/frontend/src/components/InstallChaos/index.tsx
Labels: size/XS, UI/UX, READY TO MERGE
