Repository litmuschaos/litmus, pull requests merged in 2021-06, with the labels that each got.

#2857 🔧 type(bugfix): Fixed Editor for Verify & Commit and Tune Workflow page 🔨
  litmus-portal/frontend/public/icons/terminal.svg
  litmus-portal/frontend/public/index.css
  litmus-portal/frontend/public/index.html
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/components/YamlEditor/styles.ts
  litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, UI/UX, kind/bug-fix, size/XXL

#2843 Added data-cy ids for tests and minor bug fix
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WeightSlider/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/Home/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Labels: READY TO MERGE, size/L

#2861 Backend Enhancements for Portal
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/chaosengine.go
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/workflow.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/pkg/types/event.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
Labels: READY TO MERGE, size/XL

#2859 type(bugfix): Fixing Save template editor and fixing Finish button CSS + Vertically aligning Save alert
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/components/YamlEditor/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: READY TO MERGE, size/L

#2849 chore(litmus-portal): Added podGC on revert-chaos
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/S

#2829 Enhancement: Moving pagination, sorting and filtering of workflow runs table to the backend
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/graphql/subscriptions.ts
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/chaos-workflow/types.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
Labels: DO NOT MERGE, PR: Changes Requested, READY TO MERGE, area/litmus-portal, kind/enhancement, size/XXL

#2864 type(bugfix): Fixing editor save issue when nothing is changes + Removing Kubernetes Conformance Test Header
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/styles.ts
Labels: READY TO MERGE, size/S

#2865 Added chaos schedule support to portal backend
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
Labels: READY TO MERGE, size/M

#2858 Chore(multiarch): Build multiarch images for litmus portal components
  .github/workflows/build.yml
  .github/workflows/push.yml
  litmus-portal/BUILD_IMAGE.md
  litmus-portal/Makefile
  litmus-portal/README.md
  litmus-portal/authentication/Dockerfile
  litmus-portal/cluster-agents/event-tracker/Dockerfile
  litmus-portal/cluster-agents/subscriber/Dockerfile
  litmus-portal/frontend/Dockerfile
  litmus-portal/graphql-server/Dockerfile
Labels: PR: Changes Requested, size/L

#2862 type(ux): Added delete option in experiment table, fixed agent select radio buttons and minor ux changes
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2869 Adding API for sync and delete workflow
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
  litmus-portal/cluster-agents/subscriber/pkg/types/connect.go
  litmus-portal/cluster-agents/subscriber/pkg/utils/workflow.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/chaos-workflow/types.go
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: PR: Changes Requested, size/XL

#2868 type(ux): Added myhub selection for pre-defined workflows
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, size/L

#2873 Remove circleci badge from README.md
  README.md
  litmus-portal/frontend/README.md
Labels: size/XS

#2874 Added filter for available workflow runs and minor fix
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go
Labels: PR: Changes Requested, size/M

#2876 Minor fix for pre-defined workflows
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
Labels: READY TO MERGE, size/XS

#2872 type(bugfix): Fixed Loader to Center + Added alert on Editor not being saved and trying to proceed 🐛
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/src/components/TimePopOver/index.tsx
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/ApplicationDashboard/index.tsx
  litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/WorkflowAnalytics/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/utils/formatCount.ts
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/Panel/PanelContent.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/TopNavButtons/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableToolbar.tsx
  litmus-portal/frontend/src/views/Analytics/DataSources/Table/TableData.tsx
  litmus-portal/frontend/src/views/Analytics/DataSources/Table/TableToolbar.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowRunDetailsTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowRunsBarChart/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/styles.ts
  litmus-portal/frontend/src/views/Community/CommunityTimeSeriesPlot/index.tsx
  litmus-portal/frontend/src/views/Community/GeoMap/geo.json
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/icons.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/icons.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
Labels: READY TO MERGE, size/M

#2879 Update README.md
  README.md
Labels: READY TO MERGE, size/M

#2878 chore(litmus-portal): Added sync and terminate workflow feature and minor ux fixes
  litmus-portal/frontend/public/icons/error-upload.svg
  litmus-portal/frontend/public/icons/retry.svg
  litmus-portal/frontend/public/icons/sync-wf.svg
  litmus-portal/frontend/public/icons/terminate-wf.svg
  litmus-portal/frontend/public/icons/warning.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/Status.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2882 List workflow optimization
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/scheduleData.ts
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/pages/WorkflowAnalytics/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/Tables/worflowData.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#2883 type(update): Updated Litmus-UI to 1.2.0 and added minor UI fixes ⚡️
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/Status.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/__tests__/CustomStatus.test.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
Labels: READY TO MERGE, UI/UX

#2891 Added endpoint for portal stats
  litmus-portal/graphql-server/pkg/authorization/middleware.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
  litmus-portal/graphql-server/pkg/stat/status.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
  litmus-portal/graphql-server/server.go
Labels: READY TO MERGE, size/L

#2886 type(ux): Removed templates tab and minor change in jobCleanUpPolicy
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/components/PredifinedWorkflows/index.tsx
  litmus-portal/frontend/src/components/PredifinedWorkflows/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/ExperimentDetails.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/Head.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/Recommendation.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Templates/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Templates/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/styles.ts
Labels: READY TO MERGE, size/XL

#2885 Added Minor Fix for Resilience Score Calculation Logic and Namespaced mode agent registration.
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/utils/misc.go
Labels: READY TO MERGE, size/XS

#2889 (analytics): Backend updates for Application dashboard CRUD v2
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go
  litmus-portal/graphql-server/utils/misc.go
Labels: READY TO MERGE, Testing-done, area/litmus-portal, size/XXL, state/dev-complete

#2892 Analytics graphs
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/scheduleData.ts
  litmus-portal/frontend/src/views/Analytics/Overview/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/style.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/styles.ts
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/operations.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/schema.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
Labels: DO NOT MERGE, PR: Changes Requested, size/XXL

#2893 Removing Argo server deployment from the agent list
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/server.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: size/L

#2894 Minor fixes for analytics
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/TopNavButtons/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/index.tsx
Labels: READY TO MERGE, area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/XS

#2897 Added fail check for stopped engine with no experiments
  litmus-portal/cluster-agents/subscriber/pkg/events/util.go
Labels: READY TO MERGE, size/XS

#2899 Updated the Control plane to version 2.0.0-Beta8.
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/README.md
Labels: size/M

#2901 Fixed the image push Step for event-tracker.
  .github/workflows/push.yml
Labels: READY TO MERGE, size/S

#2898 WorkflowRun stats in workflow details page for analytics
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go
Labels: READY TO MERGE, size/XL

#2903 Bug fix: changed project_id from String to ID
  litmus-portal/frontend/src/graphql/queries.ts
Labels: READY TO MERGE, size/XS

#2904 type(ux): Added error texts and fixed the probes table
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
Labels: READY TO MERGE, size/L

#2905 Added error log for time discrepancy between workflow and engine resource
  litmus-portal/cluster-agents/subscriber/pkg/events/util.go
Labels: size/XS

#2907 Created lenskart.md
  adopters/organizations/lenskart.md
Labels: READY TO MERGE, size/M

#2909 Added lenskart to the adaptors.md
  ADOPTERS.md
Labels: READY TO MERGE, size/XS

#2908 Update Uma's information in the MAINTAINERS file
  MAINTAINERS
Labels: size/XS

#2910 type(bug): Fixing Radio Button selection issue + Adding data-cy for Smoke Test + Fixing Loader Alignment
  litmus-portal/frontend/src/components/Loader/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/S

#2912 Updated CRDs and CRs version to 1.13.6 for master
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/litmus-portal-crds.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/run.sh
Labels: size/S

#2915 Created halodoc.md
  adopters/organizations/halodoc.md
Labels: size/M

#2916 (chore)adoption: add entry for halodoc in adopters.md file
  ADOPTERS.md
Labels: size/XS

#2917 Added usage query for admin
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/usage.graphqls
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/stat/status.go
  litmus-portal/graphql-server/pkg/usage/status.go
  litmus-portal/graphql-server/pkg/usage/types.go
  litmus-portal/graphql-server/server.go
Labels: READY TO MERGE

#2914 Adding the various states of experiments in workflow runs
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/chaos-workflow/types.go
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
  litmus-portal/graphql-server/utils/misc.go
Labels: READY TO MERGE, area/chaos-workflows, area/litmus-portal, size/XL

#2918 Updated project owner sort to username field
  litmus-portal/graphql-server/pkg/usage/status.go
Labels: size/XS

#2921 chore(litmus-portal): Added overall usage and project stats page
  litmus-portal/frontend/public/icons/myhub.svg
  litmus-portal/frontend/public/icons/users.svg
  litmus-portal/frontend/public/icons/workflow-calender.svg
  litmus-portal/frontend/public/icons/workflows-outline.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/pages/Usage/index.tsx
  litmus-portal/frontend/src/pages/Usage/styles.ts
  litmus-portal/frontend/src/svg/usage.svg
  litmus-portal/frontend/src/views/Usage/UsageStats/Cards.tsx
  litmus-portal/frontend/src/views/Usage/UsageStats/index.tsx
  litmus-portal/frontend/src/views/Usage/UsageStats/styles.ts
  litmus-portal/frontend/src/views/Usage/UsageTable/index.tsx
  litmus-portal/frontend/src/views/Usage/UsageTable/styles.ts
Labels: area/litmus-portal, size/XL

#2924 Updating the supported platforms list
  litmus-portal/README.md
Labels: READY TO MERGE, area/community, area/litmus-portal, size/XS

#2923 type(bugfix): Fixed Sidebar icon darkening + Shifted Usage Table Loader to Center
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/pages/UsageStatistics/index.tsx
  litmus-portal/frontend/src/pages/UsageStatistics/styles.ts
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
  litmus-portal/frontend/src/views/UsageStatistics/UsageStats/Cards.tsx
  litmus-portal/frontend/src/views/UsageStatistics/UsageStats/index.tsx
  litmus-portal/frontend/src/views/UsageStatistics/UsageStats/styles.ts
  litmus-portal/frontend/src/views/UsageStatistics/UsageTable/index.tsx
  litmus-portal/frontend/src/views/UsageStatistics/UsageTable/styles.ts
Labels: READY TO MERGE, size/S

#2925 Chore(RBAC): Add service account for ns mode
  docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
Labels: size/M

#2913 Ux fixes
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/components/Loader/index.tsx
  litmus-portal/frontend/src/components/MainInfoContainer/styles.ts
  litmus-portal/frontend/src/components/RecentOverviewContainer/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/models/redux/tabs.ts
  litmus-portal/frontend/src/redux/actions/tabs.ts
  litmus-portal/frontend/src/redux/reducers/tabs.ts
  litmus-portal/frontend/src/views/Analytics/Overview/WorkflowDashboardCard/index.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/index.tsx
  litmus-portal/frontend/src/views/Analytics/Overview/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/WorkflowRunCard/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/workflowConstants.ts
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2927 Update README.md (Add Maveric Systems blog)
  README.md
Labels: size/XS

#2930 Moving rbac to authorization package
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/authorization/validate.go
Labels: size/M

#2867 refactor: litmus-portal authentication server
  litmus-portal/authentication/.gitignore
  litmus-portal/authentication/Dockerfile
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/api/main.go
  litmus-portal/authentication/api/middleware/jwt_middlware.go
  litmus-portal/authentication/api/presenter/rest.go
  litmus-portal/authentication/api/routes/user_router.go
  litmus-portal/authentication/controller/controller.go
  litmus-portal/authentication/controller/password/password.go
  litmus-portal/authentication/controller/user/user.go
  litmus-portal/authentication/go.mod
  litmus-portal/authentication/go.sum
  litmus-portal/authentication/okteto.yml
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/authentication/pkg/errors/error.go
  litmus-portal/authentication/pkg/errors/response.go
  litmus-portal/authentication/pkg/generates/jwt_access.go
  litmus-portal/authentication/pkg/manage/config.go
  litmus-portal/authentication/pkg/manage/manager.go
  litmus-portal/authentication/pkg/models/token.go
  litmus-portal/authentication/pkg/models/user.go
  litmus-portal/authentication/pkg/providers/github/github.go
  litmus-portal/authentication/pkg/server/config.go
  litmus-portal/authentication/pkg/server/server.go
  litmus-portal/authentication/pkg/server/server_config.go
  litmus-portal/authentication/pkg/store/config.go
  litmus-portal/authentication/pkg/store/user.go
  litmus-portal/authentication/pkg/types/const.go
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/authentication/pkg/user/service.go
  litmus-portal/authentication/pkg/utils/configs.go
  litmus-portal/authentication/pkg/utils/errors.go
  litmus-portal/authentication/pkg/utils/mongo_database.go
  litmus-portal/authentication/pkg/utils/sanitizers.go
  litmus-portal/authentication/pkg/utils/uuid/uuid.go
  litmus-portal/authentication/router/router.go
  litmus-portal/authentication/src/main.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: DO NOT MERGE, PR: Changes Requested, area/litmus-portal, size/XXL

#2932 API doc url fix
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
Labels: READY TO MERGE, size/XS

#2934 Exclude removed agents from usage data
  litmus-portal/graphql-server/pkg/usage/status.go
Labels: size/S

#2929 Filtered out removed workflows and changed weekly filter to daily
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/scheduleData.ts
  litmus-portal/frontend/src/models/graphql/workflowStats.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/style.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/styles.ts
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/operations.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: READY TO MERGE, size/L

#2935 Adding backward compatibility fix for auth server
  litmus-portal/authentication/api/handlers/user_handlers.go
  litmus-portal/authentication/api/main.go
  litmus-portal/authentication/go.mod
  litmus-portal/authentication/go.sum
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/authentication/pkg/utils/configs.go
Labels: READY TO MERGE, Testing-done, kind/bug-fix, size/M

#2931 type(ux): Fixed workflow settings issue for templates and added data-cy for e2e
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/M

#2933 type(bugfix): Fixed Radio Button selection issue at Choose Workflow Screen 🐛
  litmus-portal/frontend/src/components/LitmusStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: size/XL

#2937 type(ux-bugfix): Fixed Accordion width problem and Edit Sequence Button render for No Visualizaed Graphs
  litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/pages/EditSchedule/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/M

#2940 type(ux): Fixed portal ux issues and minor style changes
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/M

#2944 Bug fixes in browse workflow table
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: READY TO MERGE, size/L

#2938 Data source API fixes
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/health-check.go
Labels: READY TO MERGE, Testing-done, area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/L

#2946 Updated argo executor image pull policy
  litmus-portal/graphql-server/manifests/cluster/1c_argo_meta.yaml
  litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml
Labels: READY TO MERGE, size/XS

#2947 adding environment vars check condition in event tracker and subscriber
  litmus-portal/cluster-agents/event-tracker/main.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
Labels: size/S

#2943 type(ux-fix): ⚡️ Fixed Table FormControl active colors + 📝 updated workflow pills + minor UX fixes 🎨
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableToolbar.tsx
  litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/styles.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
  litmus-portal/frontend/src/views/Targets/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/styles.ts
Labels: size/L

#2945 type(ux): Updated exp runs in usage section and refactored the target application code
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/data.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/UsageStatistics/UsageTable/index.tsx
Labels: READY TO MERGE, size/L

#2950 UI fixes beta9
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/ScheduleAndRunStats/style.ts
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/styles.ts
  litmus-portal/frontend/src/views/Settings/GitOpsTab/styles.ts
  litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts
Labels: READY TO MERGE, area/litmus-portal, fixed, size/M

#2951 type(ux): Fixed usage statistics page with LazyQuery and added redux state for Myhub tabs
  litmus-portal/frontend/src/models/redux/tabs.ts
  litmus-portal/frontend/src/pages/ChaosHub/customMyHubCard.tsx
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/redux/actions/tabs.ts
  litmus-portal/frontend/src/redux/reducers/tabs.ts
  litmus-portal/frontend/src/views/Analytics/Overview/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/UsageStatistics/UsageStats/index.tsx
  litmus-portal/frontend/src/views/UsageStatistics/UsageTable/index.tsx
Labels: READY TO MERGE, size/L
