Repository litmuschaos/litmus, pull requests merged in 2021-03, with the labels that each got.

#2482 (circleci/frontend): Adding {version, buildtime} to frontend ui and respective changes to {circleci, Dockerfile}
  .circleci/config.yml
  litmus-portal/frontend/Dockerfile
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/SideBar/styles.ts
Labels: size/M

#2485 minor formatting translation file for the steps of connecting cluster
  litmus-portal/frontend/public/locales/en/translation.yaml
Labels: READY TO MERGE, size/XS

#2486 (fix): Targets table workflow run time update
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/clusterData.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
Labels: READY TO MERGE, size/L

#2489 Update the Maintainers email and company
  MAINTAINERS
Labels: size/XS

#2488 Updating ADOPTERS.md
  ADOPTERS.md
  adopters/organizations/orange.md
Labels: size/M

#2492 Added Litmus Stepper and created onNext handler from Child Component
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/components/LitmusStepper/LitmusStepConnector.tsx
  litmus-portal/frontend/src/components/LitmusStepper/LitmusStepIcon.tsx
  litmus-portal/frontend/src/components/LitmusStepper/index.tsx
  litmus-portal/frontend/src/components/LitmusStepper/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/useQontoStepIconStyles.ts
  litmus-portal/frontend/src/models/redux/alert.ts
  litmus-portal/frontend/src/models/redux/index.ts
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/redux/actions/alert.ts
  litmus-portal/frontend/src/redux/reducers/alert.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts
Labels: kind/enhancement, size/XL

#2493 retriving role from mongodb in litmusportal auth server
  litmus-portal/authentication/pkg/generates/jwt_access.go
  litmus-portal/authentication/pkg/models/user.go
Labels: size/S

#2475 Added Inital UI Changes for v2 workflow representation screens.
  litmus-portal/frontend/public/icons/experiment_icon.svg
  litmus-portal/frontend/public/icons/eye.svg
  litmus-portal/frontend/public/icons/failed.svg
  litmus-portal/frontend/public/icons/filledDownArrow.svg
  litmus-portal/frontend/public/icons/pending.svg
  litmus-portal/frontend/public/icons/running.svg
  litmus-portal/frontend/public/icons/succeeded.svg
  litmus-portal/frontend/public/icons/workflow_icon.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/createLabel.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/workflowTable/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/workflowTable/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/workflowTable/styles.ts
Labels: size/XXL

#2407 Refactor the predefined workflow screens and Clean up
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/components/PredifinedWorkflows/index.tsx
  litmus-portal/frontend/src/components/WorkflowCard/CardContent.tsx
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
  litmus-portal/frontend/src/models/predefinedWorkflow.ts
Labels: READY TO MERGE, size/L

#2497 Added edit gitops config feature and fixed auth server bug
  litmus-portal/authentication/go.mod
  litmus-portal/authentication/pkg/models/user.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/database/mongodb/gitops/operations.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: READY TO MERGE, size/L

#2498 Removed generateName in upload YAML functionality
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/S

#2495 chore(litmus-admin): updating the minimal permissions in litmus-admin RBAC
  docs/litmus-admin-rbac.yaml
Labels: size/M

#2501 chore(litmus-portal): Added edit gitops functionality and updated images to non root
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/gitOpsInfo.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/sshField.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
Labels: PR: Changes Requested, area/litmus-portal, size/XL

#2503 Changed one data-cy parameters for Teaming.
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
Labels: size/XS

#2504 Minor fixes for text and styles
  litmus-portal/frontend/src/pages/AnalyticsDashboards/index.tsx
  litmus-portal/frontend/src/pages/AnalyticsDashboards/styles.ts
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/pages/MyHub/customMyHubCard.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/OverviewQuickActionCard/index.tsx
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, size/M, state/review-complete

#2505 Fixed default error state for password fields and fixed modal padding
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx
Labels: size/L

#2507 Add Red Hat as Litmus adopter
  adopters/organizations/redhat.md
Labels: READY TO MERGE, size/S

#2508 (chore)adopters: add Red Hat adoption story in ADOPTERS.md file
  ADOPTERS.md
  adopters/organizations/redhat.md
Labels: size/XS

#2506 Basic auth disabled for data source and added complete path for API docs
  litmus-portal/frontend/src/components/QuickActionCard/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Forms/prometheus.tsx
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, size/XS

#2502 Added Workflow Settings Details Modification + Navigation
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts
Labels: kind/enhancement, size/L

#2491 chore(litmus-portal): Add Add Probe modal
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/styles.ts
Labels: PR: Changes Requested, area/litmus-portal, size/XL

#2518 Added Myhub option and gql queries to fetch the chaosengine and experiment YAML
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, size/XL

#2523 Adding chaos exporter to agent manifest for chaos events and metrics
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/ 2b_litmus_deployment.yaml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: area/litmus-portal, kind/feature, size/L, state/dev-complete, state/review-in-progress

#2522 Updated mongo queries to use UID as unique identifier
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/project.graphqls
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
  litmus-portal/graphql-server/pkg/project/create.go
Labels: size/M

#2525 chore(litmus-portal): Fix BCH code duplication issues
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/utils/selectorOptions.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Cards/CardContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Cards/dashBoardCards.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Cards/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Home/ResilienceScoreComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/L

#2524 Optimized Workflow Settings and Tune Workflow
  litmus-portal/frontend/.eslintignore
  litmus-portal/frontend/cypress.json
  litmus-portal/frontend/cypress/component/LinearProgressBar.spec.tsx
  litmus-portal/frontend/cypress/component/QuickActionCard.spec.tsx
  litmus-portal/frontend/cypress/component/breadcrumb.spec.tsx
  litmus-portal/frontend/cypress/component/buttons.spec.tsx
  litmus-portal/frontend/cypress/component/infoTooltip.spec.tsx
  litmus-portal/frontend/cypress/component/passedVsFailed.spec.tsx
  litmus-portal/frontend/cypress/component/semiCircularProgressBar.spec.tsx
  litmus-portal/frontend/cypress/component/stepper.spec.tsx
  litmus-portal/frontend/cypress/component/weightSlider.spec.tsx
  litmus-portal/frontend/cypress/fixtures/example.json
  litmus-portal/frontend/cypress/plugins/index.js
  litmus-portal/frontend/cypress/support/commands.js
  litmus-portal/frontend/cypress/support/index.js
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/icons/editsequence.svg
  litmus-portal/frontend/public/icons/viewYAMLicon.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/containers/layouts/Width/index.tsx
  litmus-portal/frontend/src/models/localforage/radioButton.ts
  litmus-portal/frontend/src/models/localforage/workflow.ts
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/testHelpers/ProviderWrapper.tsx
  litmus-portal/frontend/src/testHelpers/ThemeWrapper.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/tsconfig.json
Labels: READY TO MERGE, area/litmus-portal, size/L

#2521 Adding changes to frontend for interleaving chaos events on litmus-ui graphs.
  .gitignore
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/PreconfiguredDashboards/data.ts
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/Configure.tsx
  litmus-portal/frontend/src/testHelpers/ThemeWrapper.tsx
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dashboardData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/styles.ts
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, kind/feature, merge, size/L, state/dev-complete, state/review-complete

#2526 chore(litmus-portal): Added error handling in workflow creation and alert text for ssh authentication
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/QuickActionCard/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/styles.ts
  litmus-portal/frontend/src/views/Settings/GitOpsTab/sshField.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/styles.ts
Labels: READY TO MERGE, area/litmus-portal, merge, size/L

#2528 Updated workflow status to failed for stopped chaosengines
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/workflow.go
Labels: size/XS

#2527 adding version to analytics report
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/index.tsx
Labels: READY TO MERGE, size/XS

#2530 Update card styles for Infra-Chaos tag
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
Labels: READY TO MERGE, merge, size/XS

#2531 Converting mongodb deployment to statefulset
  litmus-portal/cluster-agents/event-tracker/build/Dockerfile
  litmus-portal/cluster-agents/event-tracker/event-tracker.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: PR: Changes Requested, size/L

#2529 Teaming Code refactor, updated queries to use UID
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/src/components/Header/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  litmus-portal/frontend/src/components/WelcomeModal/styles.ts
  litmus-portal/frontend/src/models/graphql/invite.ts
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTable.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/membersTable.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
Labels: READY TO MERGE, merge, size/XL

#2532 welcome modal bug fix
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  litmus-portal/frontend/src/utils/auth.ts
Labels: READY TO MERGE, size/M

#2533 Revoking admin's privileges to edit created user's fullname and email
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx
Labels: READY TO MERGE, size/M

#2536 chore(litmus-portal): Fixed the MyHubs typo and updated the Gitops section
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
Labels: READY TO MERGE, area/litmus-portal, merge, size/L

#2534 Added changes for data-cy identifiers for testing.
  litmus-portal/frontend/src/components/GitHubComponents/GithubInputFields/GithubInputFields.tsx
  litmus-portal/frontend/src/components/PredifinedWorkflows/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WeightSlider/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/gitOpsInfo.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/sshField.tsx
Labels: READY TO MERGE, merge, size/L

#2535 CSS and other bug fixes for 2.0 beta 1
  litmus-portal/frontend/public/icons/addDashboard.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/BreadCrumbs/index.tsx
  litmus-portal/frontend/src/components/BreadCrumbs/styles.tsx
  litmus-portal/frontend/src/components/Button/BinarySwitch/index.tsx
  litmus-portal/frontend/src/components/CheckBox/index.tsx
  litmus-portal/frontend/src/components/InfoFilled/index.tsx
  litmus-portal/frontend/src/components/InfoFilled/styles.ts
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/components/YamlEditor/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/pages/AnalyticsDashboards/index.tsx
  litmus-portal/frontend/src/pages/AnalyticsDashboards/styles.ts
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/HomePage/style.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/styles.ts
  litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/Configure.tsx
  litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/styles.ts
  litmus-portal/frontend/src/pages/SelectAndConfigureDataSource/Configure.tsx
  litmus-portal/frontend/src/pages/SelectAndConfigureDataSource/styles.ts
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Forms/prometheus.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Forms/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Table/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Table/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonPlot/style.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/TableHeader.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/OverviewQuickActionCard/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dashboardData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dataSource.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/styles.ts
  litmus-portal/frontend/src/views/Community/CommunityTimeSeriesPlot/index.tsx
  litmus-portal/frontend/src/views/Community/CommunityTimeSeriesPlot/styles.ts
  litmus-portal/frontend/src/views/Community/GeoMap/index.tsx
  litmus-portal/frontend/src/views/Community/GeoMap/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, merge, state/dev-complete, state/review-complete

#2538 Minor text and link fixes for community page.
  litmus-portal/frontend/src/components/InfoFilled/index.tsx
  litmus-portal/frontend/src/pages/Community/index.tsx
  litmus-portal/frontend/src/pages/Community/styles.ts
Labels: area/community, area/litmus-portal, kind/bug-fix, size/XS

#2539 link, state management fix for reducing computational cost for analytics dashboard.
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/styles.ts
  litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/Configure.tsx
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/utils/timeDifferenceString.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/OverviewQuickActionCard/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dashboardData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dataSource.tsx
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, merge, size/L, state/dev-complete, state/review-complete

#2544 Change the method of connection to a cluster agent using litmusctl
  litmus-portal/frontend/public/icons/connectTarget.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Button/BackButton/index.tsx
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectTarget/styles.ts
  litmus-portal/frontend/src/components/Targets/TargetCopy/index.tsx
  litmus-portal/frontend/src/components/Targets/TargetCopy/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/pages/ConnectTarget/index.tsx
  litmus-portal/frontend/src/pages/ConnectTarget/styles.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
  litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/Select.tsx
  litmus-portal/frontend/src/pages/SelectAndConfigureDataSource/Select.tsx
  litmus-portal/frontend/src/pages/Targets/index.tsx
  litmus-portal/frontend/src/pages/Targets/styles.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/BackButton/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/BackButton/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/YamlEditor/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/Targets/TargetCopy/index.tsx
  litmus-portal/frontend/src/views/Targets/TargetCopy/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
Labels: READY TO MERGE

#2545 litmus-ui version update
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/styles.ts
Labels: size/XS

#2547 Adding litmus-2.0.0-Beta1 manifest
  docs/2.0.0-Beta1/litmus-2.0.0-Beta1.yaml
  litmus-portal/README.md
Labels: size/L

#2553 fixed issue of workflow table dropdown not working, made the workflow name clickable
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
Labels: READY TO MERGE, kind/bug-fix, size/S

#2554 chore(MyHub): Added YAML Generation for Custom Workflows
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/createLabel.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/icons.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: kind/enhancement, size/XL

#2557 minor bug fix in settings tab
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/models/graphql/invite.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
Labels: size/L

#2559 Updated the YAML generation utility
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/M

#2556 chore(litmus-portal): Added loader in verify and commit finish button
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
Labels: READY TO MERGE, area/litmus-portal, merge, size/M

#2562 Updated the fetch policy for getting experiment and engine yaml from MyHub
  litmus-portal/frontend/src/pages/MyHub/customMyHubCard.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/L

#2555 [chore] - Update Beta link Docs
  litmus-portal/README.md
Labels: size/XS

#2564 Populating Custom Chaos Table
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/L

#2548 feat: auto import prometheus datasource and dashboard in grafana deployment
  monitoring/README.md
  monitoring/grafana-dashboards/README.md
  monitoring/grafana-dashboards/kubernetes/Node-and-pod-metrics-dashboard.json
  monitoring/grafana-dashboards/percona-sql/MySQL-Overview-Interleaved.json
  monitoring/grafana-dashboards/percona-sql/PXC_Galera_Node_Summary_Interleaved.json
  monitoring/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json
  monitoring/utils/grafana/dashboard-configMaps.yaml
  monitoring/utils/grafana/datasource-configMap.yaml
  monitoring/utils/grafana/deployment.yaml
Labels: READY TO MERGE, size/L

#2566 chore(litmus-v2): Fixed Adding Experiment data to Table Bug 🐛
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts
Labels: READY TO MERGE, bug, kind/bug-fix, size/M

#2551 chore(crds): updating crds version from v1beta1 to v1
  docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.13.0-crd-v1.yaml
  docs/litmus-operator-v1.13.2.yaml
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
Labels: READY TO MERGE, merge

#2567 Updating delete to disconnect targets
  litmus-portal/frontend/public/icons/ClusterDisconnect.svg
  litmus-portal/frontend/public/icons/DisconnectIcon.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/styles.ts
Labels: PR: Changes Requested, size/M

#2573 Added Redux state for Manifest only + Fixed Roll back local forage persistance ❤🩹
  litmus-portal/frontend/src/models/localforage/workflow.ts
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/redux/actions/workflow.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: kind/bug-fix, kind/enhancement, size/L

#2576 (litmus-portal): removed hardcoded litmus namespace from chaos exporter deployment and removed space at the start of the filename.
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
Labels: area/chaos-exporter, area/litmus-portal, kind/bug-fix, size/XS

#2565 Refactored the v2 workflow representation screen
  litmus-portal/frontend/src/models/redux/button.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/redux/actions/button.ts
  litmus-portal/frontend/src/redux/reducers/button.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/styles.ts
Labels: size/XL

#2579 Adding styles and reducing bundle size to frontend's ProgressBar component
  litmus-portal/frontend/src/components/ProgressBar/AnalyticsLinearProgressBar/index.tsx
  litmus-portal/frontend/src/components/ProgressBar/AnalyticsLinearProgressBar/styles.ts
  litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/index.tsx
  litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2584 chore(v2): Extracted Experiment details and Fixed workflow preview render 🛠️
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ExtractSteps.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: kind/enhancement, size/L

#2581 Using Quick action card from Litmus-ui and 'ops' to 'qps' change
  litmus-portal/frontend/cypress/component/QuickActionCard.spec.tsx
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/components/PreconfiguredDashboards/data.ts
  litmus-portal/frontend/src/components/QuickActionCard/index.tsx
  litmus-portal/frontend/src/components/QuickActionCard/style.ts
  litmus-portal/frontend/src/pages/Community/index.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/OverviewQuickActionCard/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
Labels: READY TO MERGE, size/L

#2583 Directory restructuring of components in settings, minor UI fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/ChooseAvatarModal/index.tsx
  litmus-portal/frontend/src/components/ChooseAvatarModal/styles.ts
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/components/UserDetails/index.tsx
  litmus-portal/frontend/src/components/UserDetails/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/styles.ts
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx
Labels: READY TO MERGE

#2591 Added probe deletion logic and minor fix
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: size/XL

#2592 chore(litmus-v2): Updated manifest saving logic to save updated ChaosEngine and reflect on Table 🌻
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/S

#2594 Adding support of litmus portal build using github workflow and removing circleci
  .circleci/config.yml
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/push.yml
  hack/push
Labels: PR: Changes Requested

#2596 UI enhancements in teaming
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/styles.ts
Labels: READY TO MERGE, size/M

#2597 Adding buildtime and version args to docker build of frontend
  .github/workflows/push.yml
Labels: size/XS

#2585 Added a global loader that fills in when react has not yet built
  litmus-portal/frontend/public/index.css
  litmus-portal/frontend/public/index.html
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
Labels: READY TO MERGE, area/litmus-portal, size/M

#2600 Fixed workflow run update bug
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go
Labels: READY TO MERGE, size/XS

#2552 chore(litmus-portal): Fix workflow name issue
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
Labels: PR: Changes Requested, area/litmus-portal, size/S

#2580 Update README.md
  litmus-portal/README.md
Labels: PR: Changes Requested, size/S

#2595 chore(litmus-portal): Updated the Linear ProgressBar component and some minor bug fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/AdjustedWeights/index.tsx
  litmus-portal/frontend/src/components/AdjustedWeights/styles.ts
  litmus-portal/frontend/src/components/ProgressBar/AnalyticsLinearProgressBar/index.tsx
  litmus-portal/frontend/src/components/ProgressBar/AnalyticsLinearProgressBar/styles.ts
  litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/index.tsx
  litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/styles.ts
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowRunDetailsTable/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/ExperimentPoints.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/ResultTable.tsx
Labels: READY TO MERGE, area/litmus-portal, size/L

#2601 Added checks to avoid frontend URL manipulation
  litmus-portal/frontend/src/containers/app/App.tsx
Labels: READY TO MERGE, size/L

#2603 (chore)GSoD: Project Proposal Page
  GoogleSeasonOfDocs.md
Labels: size/M

#2605 Filter steps based on the changed files
  .github/workflows/build.yml
  litmus-portal/frontend/Dockerfile
Labels: READY TO MERGE, kind/ci, size/M

#2606 Homepage refactor
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/icons/NoAgentAlert.svg
  litmus-portal/frontend/public/icons/goToIcon.svg
  litmus-portal/frontend/public/icons/radialIcon.svg
  litmus-portal/frontend/public/icons/wfIcon.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/HomePage/style.ts
  litmus-portal/frontend/src/pages/HomePage/styles.ts
  litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/AgentCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/AgentCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/PassFailCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/PassFailCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/ProjectsCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/ProjectsCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/QuickActionCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/QuickActionCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/ResilienceScoreCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/ResilienceScoreCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/TotalWorkflows/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/TotalWorkflows/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/WorkFlowCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/WorkFlowCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/styles.ts
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#2612 Added beta2 fixes for auth and teaming
  litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
Labels: READY TO MERGE, size/M

#2614 Upgrading litmusportal image tags, docs to v2.0.0-Beta1
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/README.md
Labels: size/S

#2610 chore(litmus-portal): Integrated the Probes modal and updated the vertical stepper
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: PR: Changes Requested, area/litmus-portal, size/XXL

#2611 chore(Dagre Graph): Added Basic Workflow Preview and install-experiment steps for Predefined Workflows 🖼️
  litmus-portal/frontend/src/components/LitmusStepper/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ExtractSteps.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, kind/enhancement, size/L

#2618 chore(v2): Added Workflow Scheduling and UI Fixes 📆
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/models/localforage/workflow.ts
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts
Labels: kind/enhancement, size/XL

#2574 Refactoring portal backend to mount external configmap
  litmus-portal/cluster-agents/event-tracker/event-tracker.go
  litmus-portal/cluster-agents/subscriber/build/Dockerfile
  litmus-portal/cluster-agents/subscriber/pkg/gql/mutations.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/pkg/types/connect.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/utils/misc.go
Labels: DO NOT MERGE, PR: Changes Requested, size/L
