Repository litmuschaos/litmus, pull requests merged in 2021-01, with the labels that each got.

#2390 (chore)apidocs: fix api doc title
  docs/api.html
Labels: size/XS

#2388 chore (litmus-portal): Added Enhancements in workflow for Testing using Github Actions.
  .github/Readme.md
  .github/filter_and_build.sh
  .github/workflows/main.yml
Labels: area/litmus-portal, size/L

#2392 Changed name for Readme.md for commands.
  .github/Commands.md
Labels: READY TO MERGE

#2391 directory re-structuring of subscriber's manifest and changing it's respective code
  litmus-portal/graphql-server/manifests/cluster/1a_argo_crds.yaml
  litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/1c_argo_meta.yaml
  litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace-subscriber.yml
  litmus-portal/graphql-server/manifests/namespace/ 2b_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
  litmus-portal/graphql-server/utils/misc.go
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#2396 increase circleci frontend build timeout
  .circleci/config.yml
Labels: size/XS

#2397 Updated user-load manifest and Prometheus scrap time
  monitoring/utils/prometheus/prometheus-scrape-configuration/02-prometheus-configMap.yaml
  monitoring/utils/sample-application-under-test/sock-shop/user-load.yaml
Labels: size/S

#2398 Polishing UI, Adding Delete Schedule Modal + Disable Back button on Editing a Schedule + Minor UI Bug Fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Button/ButtonFilled/index.tsx
  litmus-portal/frontend/src/components/Button/ButtonFilled/styles.ts
  litmus-portal/frontend/src/components/CustomText/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/components/WorkflowCard/CardContent.tsx
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/index.ts
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/createWorkflowData.ts
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/SchedulePage/SetTime/index.tsx
  litmus-portal/frontend/src/pages/SchedulePage/SetTime/styles.ts
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/pages/SchedulePage/styles.ts
  litmus-portal/frontend/src/pages/SchedulePage/templates.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/svg/crossmark.svg
  litmus-portal/frontend/src/utils/trim.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Templates/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/tableData.tsx
Labels: READY TO MERGE, area/litmus-portal

#2399 replacing customText with EditableText from k-ui
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/src/components/CustomText/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
Labels: READY TO MERGE, size/L

#2400 Added Disable Schedule feature + InputField Fixes + Modifications
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/BreadCrumbs/index.tsx
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/models/redux/button.ts
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/redux/actions/button.ts
  litmus-portal/frontend/src/redux/reducers/button.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WeightSlider/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2404 Fixed Litmus Colors + Button from KUI + Argo Colors
  litmus-portal/frontend/public/icons/alignmentToggle.svg
  litmus-portal/frontend/src/components/InfoTooltip/index.tsx
  litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/index.tsx
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
  litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/quontoConnector.ts
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/useQontoStepIconStyles.ts
  litmus-portal/frontend/src/components/YamlEditor/styles.ts
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/HomePage/style.ts
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/L

#2401 chore(litmus-portal): Update GeoMap colors
  litmus-portal/frontend/src/views/Community/GeoMap/CountryMap.tsx
  litmus-portal/frontend/src/views/Community/GeoMap/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/S

#2403 (litmus-portal): Analytics style fixes for kui integration
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/DateRangeSelector/index.tsx
  litmus-portal/frontend/src/components/DateRangeSelector/styles.ts
  litmus-portal/frontend/src/components/ProgressBar/AnalyticsLinearProgressBar/index.tsx
  litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/ExperimentStatus/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/PopOver/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/TableHeader.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunDetailsTable/TableHeader.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunDetailsTable/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunsBarChart/index.tsx
  litmus-portal/frontend/src/views/Home/AverageResilienceScore/styles.ts
  litmus-portal/frontend/src/views/Home/PassedVsFailed/styles.ts
  litmus-portal/frontend/src/views/Home/ResilienceScoreComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
  litmus-portal/frontend/src/views/Home/TotalWorkflows/styles.ts
Labels: READY TO MERGE, area/chaos-analytics, area/litmus-portal, kind/bug-fix, merge, size/L

#2405 Browse Workflow table and MyHub section css fix, logs section revamp and minor KUI fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/DeveloperGuide/styles.ts
  litmus-portal/frontend/src/components/InstallChaos/styles.ts
  litmus-portal/frontend/src/components/UsefulLinks/styles.ts
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/pages/MyHub/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Labels: READY TO MERGE, size/L

#2406 InputField BugFix in Settings Page
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/M

#2409 Upgrading litmus portal to v1.12.0
  litmus-portal/README.md
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/ 2b_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/litmus-portal-crds.yml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: READY TO MERGE, size/M

#2411 changing image tag to 1.12.0
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/S

#2417 Readjusting Disabling logic
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
Labels: READY TO MERGE, bug, size/XS

#2419 Adding Kublr as adopter reference #2191
  ADOPTERS.md
  adopters/organizations/kublr.md
Labels: READY TO MERGE, size/S

#2393 chore(litmus-portal): Added CRUD operation and private hub support in MyHub
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/authorization/middleware.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations/myhub.go
  litmus-portal/graphql-server/pkg/database/mongodb/schema/myhub.go
  litmus-portal/graphql-server/pkg/myhub/gitops/gitops.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/myhub/myhub_ops/gitops.go
  litmus-portal/graphql-server/pkg/myhub/myhub_ops/sshkey-gen.go
  litmus-portal/graphql-server/pkg/synchandler/sync-handler.go
  litmus-portal/graphql-server/server.go
Labels: READY TO MERGE, area/litmus-portal, size/XXL

#2421 Added private hub icons and minor fix
  litmus-portal/frontend/src/components/ExperimentHeader/index.tsx
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/redux/myhub.ts
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/chartCard.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
Labels: READY TO MERGE, size/L

#2420 Chore(update): Update the litmus CRD version
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.12.0-crd-v1.yaml
  docs/litmus-operator-v1.12.0.yaml
Labels: size/XL
