Repository litmuschaos/litmus, pull requests merged in 2021-11, with the labels that each got.

#3322 Add cypress parameters for workflow stats test suite
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/StackedBar/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
Labels: size/M, READY TO MERGE

#3329 Updated token name
  litmus-portal/frontend/src/utils/auth.ts
  litmus-portal/graphql-server/pkg/authorization/middleware.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
Labels: DO NOT MERGE, size/S

#3333 Fixed an edge case for saving template for a basic argo workflow
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: size/XS, READY TO MERGE

#3339 chore(2.3.0): Adding manifests for the 2.3.0 release
  mkdocs/docs/chaos-scheduler-v2.3.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.3.0.yaml
Labels: DO NOT MERGE, size/XXL

#3313 chore(admin-rbac): Adding networking policies permissions for the network partition experiment
  mkdocs/docs/litmus-admin-rbac.yaml
Labels: size/XS

#3337 Add parameters for workflow stats loader
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
Labels: size/M, READY TO MERGE

#3341 chore(chaos-center): Added error logs while uploading yaml and fixed edit schedule functionality
  litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx
Labels: size/M, READY TO MERGE

#3348 Add cy-parameters for deleting schedule
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
Labels: size/XS

#3351 added ipv6 support
  litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/M, PR: Changes Requested

#3356 Added SSL disable option to gql and agent components
  litmus-portal/cluster-agents/event-tracker/main.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
  litmus-portal/cluster-agents/subscriber/pkg/graphql/operations.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/schema.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
Labels: size/M, READY TO MERGE

#3360 Adding Cypress identifiers for project details validation.
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/components/Header/ProjectDropDownItems.tsx
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/pages/Targets/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/utils/auth.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/removeMemberModal.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx
Labels: size/L, READY TO MERGE

#3338 Adding "change" operator in the event tracker policy
  litmus-portal/cluster-agents/event-tracker/api/v1/eventtrackerpolicy_types.go
  litmus-portal/cluster-agents/event-tracker/api/v1/zz_generated.deepcopy.go
  litmus-portal/cluster-agents/event-tracker/config/example_cr/eventtracker_policy_example1.yaml
  litmus-portal/cluster-agents/event-tracker/config/example_cr/eventtracker_policy_example2.yaml
  litmus-portal/cluster-agents/event-tracker/config/rbac/role.yaml
  litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
Labels: size/L, READY TO MERGE

#3362 Removed isActive condition from upgrade button
  litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx
Labels: size/XS, READY TO MERGE

#3364 Add cypress parameters for data source
  litmus-portal/frontend/src/pages/ConfigureDataSources/index.tsx
  litmus-portal/frontend/src/views/Observability/DataSources/Forms/prometheus.tsx
  litmus-portal/frontend/src/views/Observability/DataSources/Table/TableData.tsx
  litmus-portal/frontend/src/views/Observability/DataSources/Table/index.tsx
Labels: size/XS, PR: Changes Requested, READY TO MERGE

#3366 added support for ingress loadbalancer hostname
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/pkg/k8s/cluster.go
Labels: size/XS, READY TO MERGE
