Repository litmuschaos/litmus, pull requests merged in 2021-12, with the labels that each got.

#3365 Add cypress parameters for workflow stats graph
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/WorkflowStats/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/ExperimentPoints.tsx
Labels: size/S, READY TO MERGE

#3358 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/XS, PR: Changes Requested, READY TO MERGE

#3380 Removing the event tracker dependency from "last-applied-configuration" annotation
  litmus-portal/cluster-agents/event-tracker/controllers/eventtrackerpolicy_controller.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
Labels: size/L, PR: Changes Requested

#3378 Fix bug: responsive home page for litmus exp docs
  mkdocs/overrides/exp-docs-icons/Youtube.svg
  mkdocs/overrides/home.html
Labels: size/L, READY TO MERGE

#3381 Updated cluster manifest and fixed go import issues
  litmus-portal/authentication/api/presenter/protos/authentication.pb.go
  litmus-portal/authentication/api/presenter/protos/authentication_grpc.pb.go
  litmus-portal/authentication/api/presenter/protos/project.pb.go
  litmus-portal/authentication/api/presenter/protos/project_grpc.pb.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/protos/authentication.pb.go
  litmus-portal/graphql-server/protos/authentication_grpc.pb.go
  litmus-portal/graphql-server/protos/project.pb.go
  litmus-portal/graphql-server/protos/project_grpc.pb.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/M, READY TO MERGE

#3383 Start deployer
  litmus-portal/authentication/api/handlers/rest/project_handler.go
  litmus-portal/authentication/api/presenter/protos/project.pb.go
  litmus-portal/authentication/api/presenter/protos/project.proto
  litmus-portal/authentication/pkg/utils/grpc.go
  litmus-portal/graphql-server/pkg/projects/project_handler.go
  litmus-portal/graphql-server/pkg/projects/types.go
  litmus-portal/graphql-server/protos/project.pb.go
  litmus-portal/graphql-server/protos/project.proto
  litmus-portal/graphql-server/server.go
Labels: size/M

#3346 Upgrade script for project DB migration
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/upgrade-agents/control-plane/upgrade-agent.yaml
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
  litmus-portal/upgrade-agents/control-plane/versions/v2.0.1/auth.go
  litmus-portal/upgrade-agents/control-plane/versions/v2.4.0/auth.go
  litmus-portal/upgrade-agents/control-plane/versions/v2.4.0/manager.go
Labels: size/L, READY TO MERGE

#3384 Closing the unclosed connections for grpc client in graphql-server
  litmus-portal/graphql-server/pkg/authorization/validate.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: size/XS, READY TO MERGE

#3386 Upgraded CRDs & litmus core images
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/litmus-portal-crds.yml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/L

#3387 Disabling Leader election for workflow controller in Namespaced mode
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
Labels: size/XS, READY TO MERGE

#3389 Added CRDs & RBAC for the workflowtasksets.
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/1a_argo_crds.yaml
  litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
  litmus-portal/litmus-portal-crds.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/M, READY TO MERGE

#3344 feat: change manifests folder chown grp to 0(root) - openshift friendly
  litmus-portal/graphql-server/Dockerfile
Labels: size/XS, PR: Changes Requested, discussion

#3391 Fixed typo of clusterrole
  litmus-portal/dex-server/dex-deployment.yaml
Labels: size/XS, READY TO MERGE

#3393 (Temporary-removal): Ignoring depcheck due to false alerts
  litmus-portal/Makefile
Labels: size/XS

#3390 Adding manifests for 2.4.0 ChaosCenter
  mkdocs/docs/2.4.0/litmus-2.4.0.yaml
  mkdocs/docs/2.4.0/litmus-namespaced-2.4.0.yaml
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#3395 chore(2.4.0): Adding manifests for the 2.4.0 release
  mkdocs/docs/chaos-scheduler-v2.4.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.4.0.yaml
Labels: size/XXL

#3396 Chore(2.4.0): Updating Readme.md for v2.4.0 manifests changes.
  litmus-portal/README.md
Labels: size/XS

#3398 Add cy param for revert-chaos button
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
Labels: size/XS

#3402 Change fatal error to standard error for some logs
  litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
Labels: size/S

#3403 Adding fatal error for the connections in subscriber
  litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
Labels: size/S

#3406 Add cy-params for monitoring dashboard
  litmus-portal/frontend/src/components/LitmusStepper/index.tsx
  litmus-portal/frontend/src/pages/ObservabilityPage/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/InfoDropdown/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/TopNavButtons/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Stepper/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/ConfigureDashboardMetadata/Form/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/index.tsx
Labels: size/M, READY TO MERGE

#3409 Bug Fix: Fixed the project details updation issue in teaming
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
Labels: size/M, READY TO MERGE
