Repository litmuschaos/litmus, pull requests merged in 2021-05, with the labels that each got.

#2762 Chore(Beta4): Add litmus-portal manifest for Beta4 version
  docs/2.0.0-Beta4/litmus-2.0.0-Beta4.yaml
  docs/2.0.0-Beta4/litmus-namespaced-2.0.0-Beta4.yaml
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2764 add kitopi to ADOPTERS.md
  ADOPTERS.md
  adopters/organizations/kitopi.md
Labels: READY TO MERGE, size/S

#2746 Created mongo interface and refactored the database operations [This is preparation to create mock interfaces for unit testing]
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/collection.go
  litmus-portal/graphql-server/pkg/database/mongodb/gitops/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/myhub/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflowtemplate/operations.go
  litmus-portal/graphql-server/pkg/project/create.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
  litmus-portal/graphql-server/server.go
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#2775 Fixed Verify & Commit page issue with updated Editable Text
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
Labels: READY TO MERGE, kind/bug-fix, size/M

#2773 chore(litmus-portal): Updated workflow generation logic and added predefined myhub api
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
Labels: READY TO MERGE, area/litmus-portal, size/L

#2778 chore(workflow):Removed kube-proxy pre-defined workflow
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
Labels: READY TO MERGE, merge, size/S

#2782 type(bugfix): ⚡ Fixed Predefined Workflow Name population issue + Cleansed Verify & Commit Page 🎨
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
Labels: READY TO MERGE, size/L

#2781 type(bugfix): Fix MyHub input validation
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
Labels: READY TO MERGE, size/M

#2779 Added changes for handling Node Phases edge cases. [Omitted/ Skipped/ Error]
  litmus-portal/frontend/public/icons/error.svg
  litmus-portal/frontend/public/icons/omitted.svg
  litmus-portal/frontend/public/icons/skipped.svg
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/icons.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/workflowConstants.ts
Labels: PR: Changes Requested, merge, size/L

#2788 (monitoring): Fixing count of experiments & event query for sock shop dashboard
  monitoring/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json
Labels: READY TO MERGE, area/community, area/monitoring, kind/bug-fix, size/M

#2790 Fix for overridden workflow labels
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
Labels: READY TO MERGE, size/M

#2792 (monitoring): Readme, dashboard and service fixes
  monitoring/README.md
  monitoring/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json
  monitoring/utils/grafana/dashboard-configMaps.yaml
  monitoring/utils/grafana/service.yaml
Labels: READY TO MERGE, area/community, area/monitoring, kind/bug-fix

#2780 (Portal - Analytics/Monitoring): Adding APIs for fetching series list and (label, values), in-memory caching, concurrent requests & moving data pre-processing pipeline.
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/prometheus.go
  litmus-portal/graphql-server/pkg/analytics/types.go
  litmus-portal/graphql-server/utils/cache.go
Labels: Testing-done, area/chaos-analytics, area/litmus-portal, kind/enhancement, kind/feature, size/XXL

#2786 chore(litmus-portal): Added image registry frontend integration
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/constants.ts
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
  litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2789 Feature/adding anutanetworks as adopter
  ADOPTERS.md
  adopters/organizations/anutanetworks.md
Labels: READY TO MERGE, size/S

#2787 (Portal - Analytics/Monitoring): Removing data mapping and filtering, adding new typed queries & fixing minor style issues
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/src/components/Accordion/index.tsx
  litmus-portal/frontend/src/components/CheckBox/index.tsx
  litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/models/graphql/prometheus.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/styles.ts
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Forms/prometheus.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/TableHeader.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosAccordion/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/TableHeader.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/InfoDropdown/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/InfoDropdown/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/PanelContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/PanelGroupContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/styles.ts
Labels: READY TO MERGE, Testing-done, area/chaos-analytics, area/litmus-portal, kind/bug-fix, kind/enhancement, size/XXL

#2791 Added pre-defined experiment from default chaos hub and workflow_name label in chaos engine
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/constants.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/predefinedWorkflow.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: size/L

#2784 type(bugfix): Fix Editor typing & pagedown issues
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
Labels: READY TO MERGE, size/XS

#2796 type(validation): 👾 Added validation to Verify & commit page 🕶🕵🏻‍♂️
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
Labels: READY TO MERGE, size/M

#2785 type(fix): Fixes overflowing experiment bug in Edit Sequence + Increases Table height for better visualisation
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: READY TO MERGE, size/S

#2795 chore(litmus-portal): Added image-registry changes in workflow manifest
  litmus-portal/frontend/src/models/graphql/createWorkflowData.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, merge, size/L

#2799 type(bugfix 🐛): Solving context issues for experiments + Fixing workflow name length 👷
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
Labels: size/M

#2800 (portal - analytics / monitoring): Fixing a minor style issue on app. dashboard page
  litmus-portal/frontend/src/pages/ApplicationDashboard/styles.ts
Labels: area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/S

#2801 changing all docker image repo name to litmuschaos
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  docs/2.0.0-Beta4/litmus-2.0.0-Beta4.yaml
  docs/2.0.0-Beta4/litmus-namespaced-2.0.0-Beta4.yaml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: READY TO MERGE, size/M

#2803 Fixed workflow name issue, added info popover for private image registry
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
  litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts
Labels: READY TO MERGE, size/L

#2805 (portal- workflows): Bug fix for editor
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
Labels: READY TO MERGE, area/chaos-workflows, area/litmus-portal, kind/bug-fix, size/XS

#2802 Added agent component live check
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2806 chore(litmus-portal): Handled edge case when no image registry is present
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
  litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts
Labels: area/litmus-portal, size/L

#2794 replace: workflow image
  images/litmus-arch_1.png
Labels: READY TO MERGE

#2807 Fixed the query race conditions and handled few edge cases
  litmus-portal/frontend/src/models/graphql/createWorkflowData.ts
  litmus-portal/frontend/src/models/redux/image_registry.ts
  litmus-portal/frontend/src/redux/actions/image_registry.ts
  litmus-portal/frontend/src/redux/reducers/image_registry.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/L

#2808 Added one minor UI fix for Node table
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
Labels: READY TO MERGE, size/XS

#2810 upgrading litmusportal manifest to 2.0.0-Beta6
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/README.md
Labels: READY TO MERGE, size/S

#2812 Added CRD for Event-tracker
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
Labels: READY TO MERGE, size/M

#2816 Upgrading manifest to Litmus-2.0.0-Beta7
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/README.md
Labels: READY TO MERGE, size/S

#2814 type(bugfix): 🐛 Fixed revert chaos not working after returning to tune worklfow and adding a new experiment 🐛
  litmus-portal/frontend/src/models/redux/customyaml.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: DO NOT MERGE, READY TO MERGE, size/M

#2817 type(community): 📝 Adding a beginner friendly resource section 🚀🎉
  resources/README.md
Labels: area/community, size/M

#2815 Updated pod logs to fetch argo and experiment logs independently
  litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
Labels: READY TO MERGE, size/S

#2821 Added Fix for Icon in Workflow Name
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/index.tsx
Labels: READY TO MERGE, size/XS

#2820 type(ux): Fixed UX Issue 3, 4 and 10 🔨 🔨
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
Labels: READY TO MERGE, UI/UX, size/L

#2822 type(bugfix): Fixed revert chaos deletion issue for Pre-Defined Workflows
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/XS

#2819 Added unit-test cases for workflow name and custom status
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/Status.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/__tests__/CustomStatus.test.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/__tests__/WorkflowSetting.test.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: kind/unit-test, size/M

#2825 type(bug): Updating serviceaccount of chaosengine before patching in workflow manifest for custom workflows
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, kind/bug-fix, size/XS

#2826 type(ui-refactor): Updated MyHub UI and added connect myhub drawer
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/MyHub/MyHubConnectDrawer/index.tsx
  litmus-portal/frontend/src/pages/MyHub/MyHubConnectDrawer/styles.ts
  litmus-portal/frontend/src/pages/MyHub/customMyHubCard.tsx
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/pages/MyHub/styles.ts
Labels: DO NOT MERGE, PR: Changes Requested, litmus-portal /refactor, size/XXL

#2824 type(ux): Adding enable schedule (ux-issue 14) + fixing ux issue 7 and 11
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
Labels: READY TO MERGE, size/M

#2827 type(ui-refactor): Added edit MyHub drawer and minor directory restructure
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/styles.ts
  litmus-portal/frontend/src/pages/ChaosHub/customMyHubCard.tsx
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/styles.ts
Labels: READY TO MERGE, UI/UX

#2828 type(ux): Fixed ux-issue 16, 38 and 39
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
Labels: READY TO MERGE, UI/UX, size/M

#2831 Update resources section
  resources/README.md
Labels: area/community, merge, priority/high, project/community, size/M

#2830 type(ux): Added time-stamp popover and download logs button
  litmus-portal/frontend/public/icons/download-logs.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/TimePopOver/index.tsx
  litmus-portal/frontend/src/components/TimePopOver/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
Labels: READY TO MERGE, UI/UX, litmus-portal /refactor, size/L

#2833 type(ux): 🔨 Making Graph Visualization Green + Fixing Editor UI
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/components/YamlEditor/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: READY TO MERGE, UI/UX, size/L

#2832 type(bug-fix): Added kubeobj fix for namespace mode, agent-config fix and isCustomworkflow field for template
  litmus-portal/cluster-agents/subscriber/go.mod
  litmus-portal/cluster-agents/subscriber/pkg/cluster/objects/objects.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflowtemplate/schema.go
Labels: READY TO MERGE, kind/bug-fix, size/L

#2837 chore(litmus-portal): Added pre-defined workflows in myhub and minor bug fix
  litmus-portal/frontend/public/icons/default-experiment.svg
  litmus-portal/frontend/public/icons/no-experiment-found.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/InstallChaos/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/chartCard.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/styles.ts
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
Labels: DO NOT MERGE, READY TO MERGE, area/litmus-portal, size/XXL

#2840 Upgraded Images for Chaos-Operator, Runner and Exporter.
  .github/workflows/build.yml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2842 chore(litmus-portal): Added validation in probes modal and minor fix
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/MyHub/ExperimentHeader/index.tsx
  litmus-portal/frontend/src/views/MyHub/ExperimentHeader/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/XL
