Repository litmuschaos/litmus, pull requests merged in 2021-09, with the labels that each got.

#3183 Fixes for workflow comparison and statistics
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/HeaderSection.tsx
  litmus-portal/frontend/src/views/Observability/DataSources/Forms/prometheus.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/TopNavButtons/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/ConfigureDashboardMetadata/Form/data.ts
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonPlot/style.ts
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableHeader.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowGraphs/ScheduleAndRunStats/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowGraphs/ScheduleAndRunStats/style.ts
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowGraphs/styles.ts
Labels: area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/XL, Testing-done

#3185 removing few gitops logs
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: size/S

#3186 Added litmuschaos/curl image in all dev/ci manifests for initContainers
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/S, READY TO MERGE

#3188 Created Namespaced Mode Deploy Definitions for Chaos Scheduler. Vali…
  mkdocs/docs/experiments/faq/scheduler.md
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-scheduler-namespaced-crd.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-scheduler-ns-rbac.yaml
Labels: READY TO MERGE, size/XL

#3171 (docs): adding pod-network-partition experiment docs
  mkdocs/docs/experiments/categories/aws-ssm/aws-ssm-chaos-by-id.md
  mkdocs/docs/experiments/categories/aws-ssm/aws-ssm-chaos-by-tag.md
  mkdocs/docs/experiments/categories/aws/ebs-loss-by-id.md
  mkdocs/docs/experiments/categories/aws/ebs-loss-by-tag.md
  mkdocs/docs/experiments/categories/aws/ec2-terminate-by-id.md
  mkdocs/docs/experiments/categories/aws/ec2-terminate-by-tag.md
  mkdocs/docs/experiments/categories/azure/azure-disk-loss.md
  mkdocs/docs/experiments/categories/azure/azure-instance-stop.md
  mkdocs/docs/experiments/categories/cassandra/cassandra-pod-delete.md
  mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss.md
  mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop.md
  mkdocs/docs/experiments/categories/kafka/kafka-broker-pod-failure.md
  mkdocs/docs/experiments/categories/nodes/docker-service-kill.md
  mkdocs/docs/experiments/categories/nodes/kubelet-service-kill.md
  mkdocs/docs/experiments/categories/nodes/node-cpu-hog.md
  mkdocs/docs/experiments/categories/nodes/node-drain.md
  mkdocs/docs/experiments/categories/nodes/node-io-stress.md
  mkdocs/docs/experiments/categories/nodes/node-memory-hog.md
  mkdocs/docs/experiments/categories/nodes/node-restart.md
  mkdocs/docs/experiments/categories/nodes/node-taint.md
  mkdocs/docs/experiments/categories/pods/container-kill.md
  mkdocs/docs/experiments/categories/pods/disk-fill.md
  mkdocs/docs/experiments/categories/pods/pod-autoscaler.md
  mkdocs/docs/experiments/categories/pods/pod-cpu-hog-exec.md
  mkdocs/docs/experiments/categories/pods/pod-cpu-hog.md
  mkdocs/docs/experiments/categories/pods/pod-delete.md
  mkdocs/docs/experiments/categories/pods/pod-dns-error.md
  mkdocs/docs/experiments/categories/pods/pod-dns-spoof.md
  mkdocs/docs/experiments/categories/pods/pod-io-stress.md
  mkdocs/docs/experiments/categories/pods/pod-memory-hog-exec.md
  mkdocs/docs/experiments/categories/pods/pod-memory-hog.md
  mkdocs/docs/experiments/categories/pods/pod-network-corruption.md
  mkdocs/docs/experiments/categories/pods/pod-network-duplication.md
  mkdocs/docs/experiments/categories/pods/pod-network-latency.md
  mkdocs/docs/experiments/categories/pods/pod-network-loss.md
  mkdocs/docs/experiments/categories/pods/pod-network-partition.md
  mkdocs/docs/experiments/categories/pods/pod-network-partition/destination-ips-and-hosts.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-partition/namespace-selectors.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-partition/pod-selectors.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-partition/policy-type.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-partition/ports.yaml
  mkdocs/docs/experiments/categories/vmware/vm-poweroff.md
  mkdocs/docs/experiments/faq/experiments.md
  mkdocs/docs/experiments/images/pod-network-partition.png
  mkdocs/mkdocs.yml
Labels: size/XL

#3194 type(ux): Fixed fetch policy issue in tune workflow page
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/XS

#3196 Upgrading litmus core version to 2.1.0
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/S

#3202 Updating readme
  litmus-portal/README.md
Labels: size/XS, READY TO MERGE

#3153 [mem-hog][docs] Remove max consumption limit
  mkdocs/docs/experiments/categories/pods/pod-memory-hog.md
Labels: size/XS, READY TO MERGE

#3201 updated litmus-ui version to 1.6.0 for fixing analytics bugs
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
Labels: area/chaos-analytics, area/litmus-portal, kind/bug-fix, size/S, READY TO MERGE

#3203 fixed grafana dashboard links for percona
  monitoring/utils/sample-application-under-test/percona/README.md
Labels: kind/docs, area/monitoring, kind/bug-fix, size/XS

#3205 fixing application dashboard crash on saving after panel group name update with existing panel association
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
Labels: area/chaos-analytics, area/litmus-portal, area/monitoring, priority/high, kind/bug-fix, size/S

#3208 Adding nginx config as a separated configmap to make it more configurable
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/L, READY TO MERGE

#3210 Feat: Added feature to display previos values of users fullname and e…
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
Labels: size/M, PR: Changes Requested, READY TO MERGE

#3189 docs(AWS): Add docs for AWS IAM integration for litmus service accounts
  mkdocs/docs/experiments/concepts/awsIamIntegration.md
  mkdocs/mkdocs.yml
Labels: size/L, READY TO MERGE

#3212 removing harcoded namepsace from nginx config
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/XS

#3213 (chore)security: add security disclosure process for litmuschaos
  SECURITY.md
Labels: size/M

#3190 chore(crd): adding valueFrom field inside env
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
  mkdocs/docs/litmus-operator-ci.yaml
  mkdocs/docs/litmus-operator-latest.yaml
  mkdocs/docs/litmus-operator-v2.0.0.yaml
Labels: size/L

#3215 chore(manifest): adding valueFrom field
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
  mkdocs/docs/litmus-operator-ci.yaml
  mkdocs/docs/litmus-operator-latest.yaml
  mkdocs/docs/litmus-operator-v2.0.0.yaml
  mkdocs/docs/litmus-operator-v2.1.0.yaml
Labels: size/L

#3217 Adding a status route to graphql-server
  litmus-portal/graphql-server/pkg/rest_handlers/file_handler.go
  litmus-portal/graphql-server/pkg/rest_handlers/status_handler.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
  litmus-portal/graphql-server/server.go
Labels: size/M, PR: Changes Requested, READY TO MERGE

#3218 removing some unnecessary argo rbacs
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: READY TO MERGE, size/XL

#3220 Fixed CLUSTER_ID typo in event-tracker
  litmus-portal/cluster-agents/event-tracker/main.go
Labels: size/XS, READY TO MERGE

#3224 Added ENVs fix for gql-server
  litmus-portal/graphql-server/server.go
Labels: size/XS, READY TO MERGE

#3113 Permission added for cassandra-chaos | Require to deploy liveness pod
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/XS, READY TO MERGE

#3225 Add parameters to required components for cypress test
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/EnvironmentVariables.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/statusText.tsx
Labels: size/S, READY TO MERGE

#3233 Added rbac for mutations
  litmus-portal/graphql-server/graph/schema.resolvers.go
Labels: size/S, READY TO MERGE
