Repository litmuschaos/litmus, pull requests merged in 2021-04, with the labels that each got.

#2623 Added logic for Application details, Design Changes for Dagre graph and some improvements.
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/createLabel.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ChaosResult/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ChaosResult/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/XXL

#2626 Minor UI tweaks to Verify & Commit 🎨
  litmus-portal/frontend/public/icons/b-finance.png
  litmus-portal/frontend/public/icons/b-finance.svg
  litmus-portal/frontend/public/icons/calendar.svg
  litmus-portal/frontend/public/icons/calendarWorkflowIcon.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
Labels: READY TO MERGE

#2627 Added backend implementation for Resiliency score calculation and Total experiments passed calculation.
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2630 Adding user to litmusDB at the time of login
  litmus-portal/frontend/src/utils/auth.ts
  litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx
Labels: READY TO MERGE, size/M

#2625 Added Kubernetes Objects API with dynamic client
  litmus-portal/cluster-agents/subscriber/pkg/cluster/objects/objects.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/mutations.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
  litmus-portal/cluster-agents/subscriber/pkg/types/connect.go
  litmus-portal/cluster-agents/subscriber/pkg/types/kubeobject.go
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/data-store/store.go
Labels: PR: Changes Requested, READY TO MERGE, size/XL

#2622 chore(litmus-portal): Add unit testing setup using `@testing-library/react`
  litmus-portal/frontend/.eslintrc.json
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/testHelpers/ThemeWrapper.tsx
  litmus-portal/frontend/src/testHelpers/test-util.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/__tests__/ChooseWorkflow.test.tsx
  litmus-portal/frontend/tsconfig.json
Labels: PR: Changes Requested, READY TO MERGE

#2629 Removed the Resiliency score calculation and local tab component from dagre graph screen
  litmus-portal/frontend/src/components/Tabs/index.tsx
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2634 chore(v2): Added an algorithm to map the Nodes and Step Group ☕
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/CreateCustomWorkflow/index.tsx
  litmus-portal/frontend/src/pages/CreateCustomWorkflow/styles.ts
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/pages/SchedulePage/templates.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/YamlEditor/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/YamlEditor/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/ResultTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ToggleComponent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ToggleComponent/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/styles.ts
Labels: DO NOT MERGE, kind/enhancement, size/XXL

#2632 Add goimports CI check and format exiting imports
  .github/workflows/build.yml
  .github/workflows/push.yml
  litmus-portal/cluster-agents/event-tracker/event-tracker.go
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
Labels: PR: Changes Requested, size/S

#2641 Fixed Github Action
  .github/workflows/build.yml
Labels: READY TO MERGE, size/XS

#2639 Fix failing CI tests and remove go imports check from push.yml
  .github/workflows/push.yml
  litmus-portal/cluster-agents/subscriber/pkg/cluster/objects/objects.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go
  litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
Labels: size/XS

#2635 chore(bch): Updating BCH config 🤯
  .bettercodehub.yml
Labels: READY TO MERGE, size/XS

#2643 chore(bch): Updating bch path in config
  .bettercodehub.yml
Labels: READY TO MERGE, size/XS

#2645 Added translations and InputField from litmus-ui in login and get started pages
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/GetStarted/PasswordSet/index.tsx
  litmus-portal/frontend/src/views/GetStarted/PasswordSet/styles.ts
  litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx
  litmus-portal/frontend/src/views/GetStarted/ProjectSet/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/WorkFlowCard/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2638 Added permission required for kubernetes obj api
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
Labels: READY TO MERGE, size/S

#2648 chore(v2): Added upload and editor functionality in workflow creation
  litmus-portal/frontend/public/icons/cross-disabled.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, merge, size/L

#2593 (litmus-portal): Graph pop out mode, state-less prometheus queries for chaos events, mongoDB resync updates removed, optimization of analytics code for monitoring, reducing heap-size usage, time range / refresh rate selection and chaos metrics on graphs with selection module.
  litmus-portal/frontend/public/icons/cloudIcon.svg
  litmus-portal/frontend/public/icons/editIcon.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/DateRangeSelector/index.tsx
  litmus-portal/frontend/src/components/StyledTableCell/index.tsx
  litmus-portal/frontend/src/components/ThreeTierCard/styles.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/models/graphql/prometheus.ts
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/models/redux/dashboards.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/constants.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/refreshData.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/styles.ts
  litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/Configure.tsx
  litmus-portal/frontend/src/redux/reducers/dashboards.ts
  litmus-portal/frontend/src/svg/aligment.svg
  litmus-portal/frontend/src/svg/alignmentStriked.svg
  litmus-portal/frontend/src/svg/arrowsOut.svg
  litmus-portal/frontend/src/svg/edit.svg
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosAccordion/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosAccordion/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/TableHeader.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/DashboardPanelGroup.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/DataSourceInactiveModal/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/DataSourceInactiveModal/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/GraphPanel.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/DashboardPanelGroup.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/GraphPanel.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/PanelContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/PanelGroupContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelContainer.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelGroupContainer.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelGroupContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dashboardData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/worflowData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/styles.ts
Labels: READY TO MERGE, area/litmus-portal, merge, size/XXL, state/dev-complete, state/review-complete

#2647 chore(v2): Alert and Validation added in workflow creation + Fixed minor issues
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/LitmusStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, merge, size/M, state/review-in-progress

#2394 Improved german translation of the README file
  translations/README-ge.md
Labels: READY TO MERGE, size/M

#2646 Updated the Workflows and Schedules tables for V2
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
  litmus-portal/frontend/src/pages/Workflows/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/Status.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/workflowConstants.ts
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2651 chore(v2): Fixed the workflow creation step issues 🔨
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/L

#2658 Added Disable schedule and Enabled/Disabled filter.
  litmus-portal/frontend/public/icons/disableSchedule.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
Labels: READY TO MERGE, merge, size/L, state/review-complete

#2656 RBAC for teaming (backend)
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/resolver.go
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
  litmus-portal/graphql-server/pkg/project/create.go
  litmus-portal/graphql-server/pkg/rbac/validate.go
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2633 chore(litmus-portal): Added workflow template operations API
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflowtemplate/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflowtemplate/schema.go
Labels: READY TO MERGE, area/litmus-portal, merge, size/XXL

#2663 Added RBAC for workflows and myhub
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: READY TO MERGE, size/M

#2660 Added fixes for handling edge cases in Workflow Visualisation Screen
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/Status.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/workflowConstants.ts
Labels: READY TO MERGE, area/litmus-portal, size/M, state/review-complete

#2667 Renaming self cluster to self agent
  litmus-portal/graphql-server/pkg/self-deployer/start.go
Labels: size/XS

#2670 (chore)adopters: add VMWare as an adopter
  ADOPTERS.md
Labels: READY TO MERGE, size/XS

#2668 Added Minor fix for embedded YAML parsing logic for Applications details.
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
Labels: size/S

#2666 chore(scheduling): Adding scheduling through template + Schedule Fixes ☑️☑️
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/L, state/review-complete

#2672 chore(validation): ⚠️ Fixing Alerts and Validation 📟
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, size/L

#2541 Updated kublr setup and README for monitoring
  monitoring/README.md
  monitoring/platforms/kublr/README.md
  monitoring/platforms/kublr/grafana-dashboards/kubernetes/Node-and-pod-metrics-dashboard-kublr.json
  monitoring/platforms/kublr/grafana-dashboards/kubernetes/Sock-Shop-Performance-Under-Chaos.json
  monitoring/platforms/kublr/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json
  monitoring/platforms/kublr/screenshots/Node-and-Pod-metrics-Dashboard-1.png
  monitoring/platforms/kublr/screenshots/Node-and-Pod-metrics-Dashboard-2.png
  monitoring/platforms/kublr/screenshots/Sock-Shop-Dashboard-1.png
  monitoring/platforms/kublr/screenshots/Sock-Shop-Dashboard-2.png
  monitoring/platforms/kublr/screenshots/Sock-Shop-Dashboard-3.png
  monitoring/platforms/kublr/screenshots/prometheus-config-update.png
  monitoring/utils/prometheus/prometheus-configuration/prometheus.yaml
  monitoring/utils/prometheus/prometheus-scrape-configuration/prometheus-deployment.yaml
Labels: READY TO MERGE, area/litmus, area/monitoring, kind/bug-fix

#2669 chore(v2): Added kubernetes obj integration, fixed chaos engine name, fixed probes 🌟
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/constants.ts
  litmus-portal/frontend/src/graphql/subscriptions.ts
  litmus-portal/frontend/src/models/graphql/createWorkflowData.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, kind/feature, size/XXL, state/review-complete

#2677 chore(scheduling): Added revert chaos 👾👾
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: READY TO MERGE, merge, size/L, state/review-complete

#2671 Added modal(UI) for save template, listManifestTemplate query with frontend integration (WIP)
  litmus-portal/frontend/public/icons/errorYaml.svg
  litmus-portal/frontend/public/icons/templateIcon.svg
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
Labels: WIP, size/L

#2664 Added Predefined workflow template for podtato-head
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
Labels: READY TO MERGE, size/M

#2676 Added fix for handling one edge case for appinfo and removed the Hosted On Option.
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/styles.ts
Labels: READY TO MERGE, kind/bug-fix, merge, size/L, state/review-complete

#2681 Updating image for Predefined workflow template cards
  litmus-portal/frontend/public/icons/podtato_head.png
  litmus-portal/frontend/public/icons/sock-shop.png
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
Labels: READY TO MERGE, merge

#2680 chore(litmus-portal): Added save template functionality, delete template and minor fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/LitmusStepper/styles.ts
  litmus-portal/frontend/src/constants.ts
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/L

#2683 chore(bugfix): Fixed Revert ChaosEngine names + Removed Back button from stepper's first step + Conditional Experiment Addition
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/LitmusStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/L

#2684 chore(bugfix): Minor Alert Fix
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
Labels: size/M

#2685 Name modify "sock-shop-chaos"
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
Labels: merge, size/XS

#2686 chore(scheduling): Fixed Scheduling Bug on Close Modal
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
Labels: size/S

#2679 Beta3 analytics
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/index.html
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Accordion/index.tsx
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/components/ToolTip/index.tsx
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
  litmus-portal/frontend/src/svg/expandAccordion.svg
  litmus-portal/frontend/src/svg/shrinkAccordion.svg
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/PanelContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/PanelGroupContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dashboardData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dataSource.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/worflowData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
Labels: state/review-in-progress

#2598 Adding {Ingress, ClusterIP, LoadBalancer} support for connecting external agent to the server
  litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
  litmus-portal/ingress.yml
Labels: PR: Changes Requested, size/L

#2688 Fixed probes modal for https/probes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
Labels: PR: Changes Requested, size/L

#2687 New Home Pages & App Layout changes
  litmus-portal/frontend/public/icons/NoAgentAlert.svg
  litmus-portal/frontend/public/icons/agentDeploy.svg
  litmus-portal/frontend/public/icons/agentDeployModal.svg
  litmus-portal/frontend/public/icons/applause.png
  litmus-portal/frontend/public/icons/copyProjectID.svg
  litmus-portal/frontend/public/icons/download.svg
  litmus-portal/frontend/public/icons/viewProjects.svg
  litmus-portal/frontend/public/icons/workflowScheduleHome.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/CreateWorkflowCard/styles.ts
  litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
  litmus-portal/frontend/src/components/Header/ProjectDropDownItems.tsx
  litmus-portal/frontend/src/components/Header/index.tsx
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/SideBar/styles.ts
  litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/svg/docs.svg
  litmus-portal/frontend/src/utils/actions.ts
  litmus-portal/frontend/src/utils/timeDifferenceString.ts
  litmus-portal/frontend/src/utils/userInitials.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/AgentInfoContainer/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/AgentInfoContainer/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/AgentDeployModal/styles.ts
  litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/styles.ts
  litmus-portal/frontend/src/views/Home/MainInfoContainer/index.tsx
  litmus-portal/frontend/src/views/Home/MainInfoContainer/styles.ts
  litmus-portal/frontend/src/views/Home/ProjectInfoContainer/index.tsx
  litmus-portal/frontend/src/views/Home/ProjectInfoContainer/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/AgentCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/AgentCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/PassFailCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/PassFailCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/ProjectsCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/ProjectsCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/QuickActionCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/QuickActionCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/ResilienceScoreCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/ResilienceScoreCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/TotalWorkflows/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/TotalWorkflows/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/WorkFlowCard/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/WorkFlowCard/styles.ts
  litmus-portal/frontend/src/views/Home/ReturningHome/index.tsx
  litmus-portal/frontend/src/views/Home/ReturningHome/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
Labels: PR: Changes Requested

#2689 Beta3 analytics fixes and minor updates.
  litmus-portal/frontend/public/icons/closeIcon.svg
  litmus-portal/frontend/public/icons/disconnected.svg
  litmus-portal/frontend/public/icons/externalLink.svg
  litmus-portal/frontend/public/icons/info.svg
  litmus-portal/frontend/public/icons/infoWhite.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/InfoTooltip/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/models/dashboardsData.ts
  litmus-portal/frontend/src/models/redux/dataSource.ts
  litmus-portal/frontend/src/pages/AnalyticsDashboards/styles.ts
  litmus-portal/frontend/src/pages/AnalyticsPage/styles.ts
  litmus-portal/frontend/src/pages/Community/styles.ts
  litmus-portal/frontend/src/pages/HomePage/styles.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/constants.ts
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
  litmus-portal/frontend/src/pages/MonitoringDashboardPage/styles.ts
  litmus-portal/frontend/src/pages/MyHub/styles.ts
  litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/Configure.tsx
  litmus-portal/frontend/src/pages/Settings/styles.ts
  litmus-portal/frontend/src/pages/Targets/styles.ts
  litmus-portal/frontend/src/pages/Workflows/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Table/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowRunDetailsTable/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowRunsBarChart/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosAccordion/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/TableData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/TableHeader.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/ChaosTable/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/DataSourceInactiveModal/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/DataSourceInactiveModal/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/InfoDropdown/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/InfoDropdown/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/PanelGroupContent.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/TopNavButtons/index.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/TopNavButtons/styles.ts
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dashboardData.tsx
  litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/styles.ts
Labels: READY TO MERGE, area/litmus-portal, kind/bug-fix, kind/feature, merge, size/XL, state/review-complete

#2644 Making event-tracker as a k8s controller to run by custom resource(Policy)
  .github/workflows/build.yml
  .github/workflows/push.yml
  litmus-portal/cluster-agents/event-tracker/.gitignore
  litmus-portal/cluster-agents/event-tracker/Dockerfile
  litmus-portal/cluster-agents/event-tracker/Makefile
  litmus-portal/cluster-agents/event-tracker/PROJECT
  litmus-portal/cluster-agents/event-tracker/api/v1/eventtrackerpolicy_types.go
  litmus-portal/cluster-agents/event-tracker/api/v1/groupversion_info.go
  litmus-portal/cluster-agents/event-tracker/api/v1/zz_generated.deepcopy.go
  litmus-portal/cluster-agents/event-tracker/config/crd/eventtracker.litmuschaos.io_eventtrackerpolicies.yaml
  litmus-portal/cluster-agents/event-tracker/config/rbac/clusterrole.yaml
  litmus-portal/cluster-agents/event-tracker/controllers/eventtrackerpolicy_controller.go
  litmus-portal/cluster-agents/event-tracker/event-tracker.go
  litmus-portal/cluster-agents/event-tracker/go.mod
  litmus-portal/cluster-agents/event-tracker/go.sum
  litmus-portal/cluster-agents/event-tracker/hack/boilerplate.go.txt
  litmus-portal/cluster-agents/event-tracker/main.go
  litmus-portal/cluster-agents/event-tracker/pkg/k8s/client.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/litmus-portal-crds.yml
Labels: size/XXL, state/review-in-progress

#2690 Create vmware.md
  adopters/organizations/vmware.md
Labels: READY TO MERGE, size/S

#2691 (chore)adopters: link vmware adoption story to adopters table
  ADOPTERS.md
Labels: size/XS

#2692 UI improvements
  litmus-portal/frontend/public/icons/calendarBlank.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/AgentInfoContainer/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/AgentInfoContainer/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
  litmus-portal/frontend/src/views/Home/MainInfoContainer/styles.ts
  litmus-portal/frontend/src/views/Home/ProjectInfoContainer/index.tsx
  litmus-portal/frontend/src/views/Home/ProjectInfoContainer/styles.ts
Labels: READY TO MERGE, area/litmus-portal, kind/enhancement, kind/refactor, kind/ui-implementation, size/L

#2694 chore(Workflow Cards): Styling fix
  litmus-portal/frontend/src/components/WorkflowCard/styles.ts
Labels: READY TO MERGE, merge, size/XS

#2698 Added minor translations and style fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Button/BackButton/styles.ts
  litmus-portal/frontend/src/components/Tabs/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2700 chore(v2): Fixed editor crashing issues and minor translation fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: READY TO MERGE, size/L

#2693 Made the tabs consistent, minor translation fix
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/views/GetStarted/PasswordSet/index.tsx
  litmus-portal/frontend/src/views/GetStarted/PasswordSet/styles.ts
  litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx
  litmus-portal/frontend/src/views/GetStarted/ProjectSet/styles.ts
  litmus-portal/frontend/src/views/Home/ProjectInfoContainer/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2706 (event-tracker): Adding few error checks
  litmus-portal/cluster-agents/event-tracker/controllers/eventtrackerpolicy_controller.go
  litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go
Labels: size/S

#2707 updated litmuschaos monitoring dashboard for sockshop.
  monitoring/grafana-dashboards/percona-sql/README.md
  monitoring/grafana-dashboards/sock-shop/README.md
  monitoring/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json
  monitoring/screenshots/Sock-Shop-Dashboard.png
  monitoring/screenshots/sock-shop/alerts-active.png
  monitoring/screenshots/sock-shop/alerts-sent.png
  monitoring/screenshots/sock-shop/chaos-engine-context-selector.png
  monitoring/screenshots/sock-shop/chaos-event-annotation.png
  monitoring/screenshots/sock-shop/chaos-experiments.png
  monitoring/screenshots/sock-shop/chaos-result-selector.png
  monitoring/screenshots/sock-shop/chaos-result-verdict-annotation.png
  monitoring/screenshots/sock-shop/interleaved-events.png
  monitoring/screenshots/sock-shop/interleaved-results.png
  monitoring/screenshots/sock-shop/no-alerts-issued.png
  monitoring/screenshots/sock-shop/probe-failure-alert.png
  monitoring/screenshots/sock-shop/verdict-failure-alert.png
Labels: area/litmus, area/monitoring, sig-monitoring

#2714 Fixed the agent installation issue when server service is of Type NodePort/LoadBalancer
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/pkg/k8s/cluster.go
Labels: DO NOT MERGE, PR: Changes Requested, size/S

#2712 chore(bug-fix): Fixing Revert Chaos + Edit Schedule Icon
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
Labels: READY TO MERGE, size/M

#2716 Updated chaos operator and runner images in manifest
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/S

#2715 Updated chaos operator dependency
  litmus-portal/cluster-agents/subscriber/go.mod
  litmus-portal/cluster-agents/subscriber/go.sum
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go
Labels: size/XS

#2718 (fix)annotation-injector-validation: fix the validation flags in CRD …as per new names in chaosengine API
  docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.13.3.yaml
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/litmus-portal-crds.yml
Labels: READY TO MERGE, size/M

#2717 Version updates, readme fixes, manifest fixes, env. for argo's container runtime executor and bug fixes for Okteto dev. env. setup.
  .betterci/ci-k8s-manifest.yml
  demo/sample-applications/sock-shop/deploy/litmus-metrics/chaos-exporter.yaml
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/manifests/cluster/1c_argo_meta.yaml
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/server.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/README.md
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
  monitoring/README.md
  monitoring/platforms/kublr/README.md
  monitoring/utils/metrics-exporters-with-service-monitors/litmus-metrics/chaos-exporter/chaos-exporter.yaml
  monitoring/utils/metrics-exporters/litmus-metrics/chaos-exporter/chaos-exporter.yaml
Labels: READY TO MERGE, Testing-done, area/community, area/litmus-portal, kind/bug-fix, kind/enhancement, size/L, state/review-complete

#2719 Added mutation to update project name
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/project/create.go
Labels: READY TO MERGE, size/L

#2723 Refactored teaming code
  litmus-portal/graphql-server/pkg/project/create.go
Labels: PR: Changes Requested, READY TO MERGE, size/M

#2704 Bugfix: cancel invite, remove member, search functionality in user ma…
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTable.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/membersTable.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/removeMemberModal.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
Labels: READY TO MERGE, size/L

#2722 Added minor style fixes
  litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
Labels: READY TO MERGE, size/M

#2725 chore(bugfix): Adding CronWorkflow Bug Fix + Taking login Background from litmus-ui
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
  litmus-portal/frontend/src/pages/LoginPage/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ExtractSteps.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
Labels: READY TO MERGE, size/M

#2726 Updated GVRs for namespaced manifest's Role and litmus 2.0 beta helm installation steps for Okteto.
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/README.md
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: READY TO MERGE, Testing-done, area/community, area/litmus-portal, kind/bug-fix, kind/docs, size/M

#2724 Added branch and tag clone functionality and env for branch/tag for MyHub
  .github/workflows/push.yml
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/frontend/Dockerfile
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/graphql-server/pkg/authorization/middleware.go
  litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
  litmus-portal/graphql-server/pkg/project/create.go
  litmus-portal/graphql-server/server.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: Testing-done, area/litmus-portal, size/M

#2728 Minor readme fix for Okteto platform helm installation steps
  litmus-portal/platforms/okteto/README.md
Labels: READY TO MERGE, area/community, area/litmus-portal, kind/bug-fix, size/XS

#2729 (chore)version-update: update versions of portal components to 2.0.0Beta4
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/README.md
Labels: READY TO MERGE, size/S

#2730 Updating pns to k8sapi as the CRE for argo on Okteto
  litmus-portal/platforms/okteto/README.md
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: area/community, area/litmus-portal, kind/bug-fix, size/S

#2732 Adding argument for forcing the CNE to user given value instead of docker/default for workflow controller.
  litmus-portal/README.md
  litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/platforms/okteto/README.md
Labels: READY TO MERGE, area/community, area/litmus-portal, kind/bug-fix, size/S

#2733 shrink and expand bug fix
  litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/styles.ts
Labels: READY TO MERGE, size/XS

#2734 chore(litmus-portal): Added parallel and serial sequencing of experiments for workflow creation
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/icons/sequencing-exp.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/reorder.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/L

#2737 Home page UX feedbacks addressed, removed ID selectors
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/AgentInfoContainer/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/styles.ts
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/Home/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/views/Home/AgentDeployModal/styles.ts
  litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
Labels: READY TO MERGE, kind/enhancement

#2736 <feature>: Updating Sequence Visualization
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/M

#2741 type(bugfix): Minor Icon Fix
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
Labels: kind/bug-fix, size/XS

#2742 appinfo undefined bug fix
  litmus-portal/frontend/src/utils/promUtils.ts
Labels: READY TO MERGE, size/XS

#2740 Added argo instanceid, discard older results with same engine name
  litmus-portal/cluster-agents/subscriber/go.sum
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/workflow.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/manifests/cluster/1c_argo_meta.yaml
  litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
Labels: READY TO MERGE, size/S

#2738 Added validation in probes modal and fixed the type issue while probe creation
  litmus-portal/frontend/public/icons/delete-exp.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
Labels: READY TO MERGE, size/XL

#2731 chore(litmus-portal): Add units to AddProbe modal
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/S

#2720 chore(litmus-portal): Change AddExperimentModal to use RadioButton
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/L

#2743 type(visualization): 🩹 Fixing edit sequence 🩹
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ExtractSteps.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
Labels: kind/enhancement, size/L

#2703 chore(testing): Adding Unit Tests for ChooseWorkflow
  litmus-portal/frontend/.eslintrc.json
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/__tests__/ChooseWorkflow.test.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
Labels: size/M

#2745 type: bugfix -- Fixed Edit and Schedule navigation + Added finish button loading
  litmus-portal/frontend/src/components/LitmusStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
Labels: kind/bug-fix, size/XL

#2747 chore(litmus-portal): Added subject and context fields while workflow creation and fixed some minor bugs
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
  litmus-portal/frontend/src/constants.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/redux/customyaml.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/L

#2751 chore(litmus-portal) : Fixed the argo graph crashing issue, workflow persistence for MyHub and added context for pre-defined workflows
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, area/litmus-portal, size/L

#2752 type(style-fix): 🎨 Minor style fix in Add Experiment Modal 🎨
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
Labels: READY TO MERGE, size/S

#2678 type(testing): Adding unit tests for Reliability Score and Weight Slider
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/__tests__/ChooseAWorkflowAgent.test.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/__tests__/ReliabilityScore.test.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WeightSlider/__test__/WeightSlider.test.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WeightSlider/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
Labels: PR: Changes Requested, READY TO MERGE, WIP, area/litmus-portal, size/L

#2753 type(validation): 🔧 Added Viewer permission + Fixed Alert when no cluster is available ✨
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/__tests__/ChooseAWorkflowAgent.test.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
Labels: size/M

#2755 (bug-fix): Created utility for dynamic namespace while workflow creation
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: READY TO MERGE, size/M

#2754 type(bugfix): 🔨 Fixed Breaking Upload YAML 🔨
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
Labels: size/S

#2756 Subscriber permissions for namespace mode
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: READY TO MERGE, size/S

#2757 Fixes for ns scope permissions and handling an edge case.
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: READY TO MERGE, Testing-done, area/litmus-portal, kind/bug-fix, size/M

#2758 Minor fix for ns mode- agent scope to be taken from cluster registration request
  litmus-portal/graphql-server/utils/misc.go
Labels: READY TO MERGE, Testing-done, area/litmus-portal, kind/bug-fix, size/XS

#2760 Minor SA fix in eventtracker (namespace)
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
Labels: size/XS

#2761 Upgrading LitmusPortal manifests to Beta5
  docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
  docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
  litmus-portal/README.md
Labels: size/S
