Repository litmuschaos/litmus, pull requests merged in 2021-10, with the labels that each got.

#3246 chore(2.1.1): adding manifest for 2.1.1 version
  mkdocs/docs/chaos-scheduler-v2.1.1.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.1.1.yaml
Labels: DO NOT MERGE, size/XXL

#3226 chore(concepts): adding experiment and result schema details
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/component-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/configuration-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/contents.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-component/args.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-component/command.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-component/image.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-component/imagePullPolicy.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/configmaps.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/container-security-context.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/experiment-annotations.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/host-file-volumes.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/host-pid.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/labels.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/pod-security-context.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-configuration/secrets.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-scope/permissions.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-scope/scope.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-tunable-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/experiment-tunable/env.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-experiment/scope-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/contents.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/probe-details/probe.out
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/probe-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/spec-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/spec/spec.out
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/status-specification.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/status/experiment-status.out
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-result/status/history.out
  mkdocs/docs/experiments/concepts/chaos-resources/probes/contents.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/litmus-probes.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/probe-chaining.md
  mkdocs/mkdocs.yml
Labels: DO NOT MERGE, size/XXL

#3239 Add Iter8 to adopters.md
  ADOPTERS.md
Labels: size/XS, READY TO MERGE

#3244 area(litmusportal-auth/dex): dex server with litmus brandings and custom css
  litmus-portal/dex-server/Dockerfile
  litmus-portal/dex-server/web/static/img/atlassian-crowd-icon.svg
  litmus-portal/dex-server/web/static/img/bitbucket-icon.svg
  litmus-portal/dex-server/web/static/img/email-icon.svg
  litmus-portal/dex-server/web/static/img/github-icon.svg
  litmus-portal/dex-server/web/static/img/gitlab-icon.svg
  litmus-portal/dex-server/web/static/img/google-icon.svg
  litmus-portal/dex-server/web/static/img/keystone-icon.svg
  litmus-portal/dex-server/web/static/img/ldap-icon.svg
  litmus-portal/dex-server/web/static/img/linkedin-icon.svg
  litmus-portal/dex-server/web/static/img/microsoft-icon.svg
  litmus-portal/dex-server/web/static/img/oidc-icon.svg
  litmus-portal/dex-server/web/static/img/saml-icon.svg
  litmus-portal/dex-server/web/static/main.css
  litmus-portal/dex-server/web/templates/approval.html
  litmus-portal/dex-server/web/templates/device.html
  litmus-portal/dex-server/web/templates/device_success.html
  litmus-portal/dex-server/web/templates/error.html
  litmus-portal/dex-server/web/templates/footer.html
  litmus-portal/dex-server/web/templates/header.html
  litmus-portal/dex-server/web/templates/login.html
  litmus-portal/dex-server/web/templates/oob.html
  litmus-portal/dex-server/web/templates/password.html
  litmus-portal/dex-server/web/themes/dark/favicon.png
  litmus-portal/dex-server/web/themes/dark/logo.png
  litmus-portal/dex-server/web/themes/dark/styles.css
  litmus-portal/dex-server/web/themes/light/favicon.png
  litmus-portal/dex-server/web/themes/light/logo.png
  litmus-portal/dex-server/web/themes/light/styles.css
  litmus-portal/dex-server/web/web.go
Labels: READY TO MERGE

#3248 Adding toleration field to the cluster registration mutation
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/schema.go
  litmus-portal/graphql-server/utils/misc.go
Labels: size/L, READY TO MERGE

#3249 Get Manifest and Get Agent Details query
  litmus-portal/cluster-agents/subscriber/go.mod
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/schema.go
  litmus-portal/graphql-server/pkg/rest_handlers/file_handler.go
  litmus-portal/graphql-server/utils/misc.go
Labels: size/L, PR: Changes Requested, READY TO MERGE

#3255 Minor fix in subscriber
  litmus-portal/cluster-agents/subscriber/subscriber.go
Labels: size/XS, READY TO MERGE

#3256 Add Pôle Emploi as an adopter.
  ADOPTERS.md
  adopters/organizations/pole_emploi.md
Labels: size/M, READY TO MERGE

#3259 Update `IS_CLUSTER_CONFIRMED` in manifest
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/utils/misc.go
Labels: size/S, READY TO MERGE

#3258 [chore] update Adopters section
  ADOPTERS.md
Labels: size/XS, READY TO MERGE

#3262 minor logic-fix in subscriber manifest generation
  litmus-portal/graphql-server/utils/misc.go
Labels: size/XS, READY TO MERGE
