Repository litmuschaos/litmus, pull requests merged in 2021-02, with the labels that each got.

#2424 Added GitOps Feature
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/resolver.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/authorization/middleware.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/data-store/store.go
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations/gitops.go
  litmus-portal/graphql-server/pkg/database/mongodb/schema/gitops.go
  litmus-portal/graphql-server/pkg/gitops/git-lock.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
  litmus-portal/graphql-server/pkg/gitops/sshkey-gen.go
  litmus-portal/graphql-server/pkg/gitops/util.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/queries/query.go
  litmus-portal/graphql-server/pkg/graphql/subscriptions/subscription.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/myhub/myhub_ops/gitops.go
  litmus-portal/graphql-server/pkg/synchandler/sync-handler.go
  litmus-portal/graphql-server/server.go
Labels: DO NOT MERGE, size/XXL

#2425 Adding event tracker as part of gitops
  .circleci/config.yml
  litmus-portal/Makefile
  litmus-portal/cluster-agents/event-tracker/build/Dockerfile
  litmus-portal/cluster-agents/event-tracker/event-tracker.go
  litmus-portal/cluster-agents/event-tracker/go.mod
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-K8s-template.yml
Labels: size/L

#2426 Minor fix for Gitops Notifier
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: size/XS

#2427 Adding configmap permission to event tracker
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: size/XS

#2430 Changing logic in event-tracker for update event
  litmus-portal/cluster-agents/event-tracker/event-tracker.go
Labels: PR: Changes Requested, size/L

#2432 changing rbac name for event tracker and change in workflow_id access
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
Labels: size/S

#2433 chore(litmus-portal): Updated the inputfields to Kubera-UI inputfields in welcome modal
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
Labels: READY TO MERGE, area/litmus-portal, size/M

#2434 fixed argo graph for firefox
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/createLabel.ts
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
Labels: READY TO MERGE, size/S

#2435 Updated Delete Operation for Git
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
  litmus-portal/graphql-server/pkg/gitops/util.go
Labels: size/S

#2436 Minor Fix GitOps
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: size/XS

#2437 Removing workflow agent from external cluster agents
  litmus-portal/cluster-agents/workflow-agent/go.mod
  litmus-portal/cluster-agents/workflow-agent/go.sum
  litmus-portal/cluster-agents/workflow-agent/main.go
  litmus-portal/cluster-agents/workflow-agent/pkg/cluster/events/util.go
  litmus-portal/cluster-agents/workflow-agent/pkg/cluster/events/workflow.go
  litmus-portal/cluster-agents/workflow-agent/pkg/cluster/logs/pod.go
  litmus-portal/cluster-agents/workflow-agent/pkg/gql/mutation.go
  litmus-portal/cluster-agents/workflow-agent/pkg/gql/subscription.go
  litmus-portal/cluster-agents/workflow-agent/pkg/gql/util.go
  litmus-portal/cluster-agents/workflow-agent/pkg/k8s/config.go
  litmus-portal/cluster-agents/workflow-agent/pkg/types/event.go
  litmus-portal/cluster-agents/workflow-agent/pkg/types/log.go
Labels: size/XL

#2440 Upgrading litmusportal to 1.13.0
  litmus-portal/README.md
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/litmus-portal-crds.yml
Labels: size/L

#2442 version upgrade to 1.13.0 in the k8s manifest
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-K8s-template.yml
Labels: size/S

#2443 feat(image): updating image tag for scheduler
  docs/chaos-scheduler-v1.10.0.yaml
  docs/chaos-scheduler-v1.12.0.yaml
  docs/chaos-scheduler-v1.13.0.yaml
Labels: size/XS

#2444 Chore(v1-crd): Update v1-crds for version 1.13.0
  docs/litmus-operator-v1.13.0-crd-v1.yaml
Labels: size/M

#2413 [Snyk] Upgrade plotly.js from 1.54.6 to 1.58.4
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: size/XS

#2416 [Snyk] Upgrade react-ace from 9.1.1 to 9.2.1
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: size/XS

#2446 Added `deletecollection` resource for litmus-admin ClusterRole
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
Labels: READY TO MERGE, merge, size/XS

#2450 Updated Litmus Portal with Litmus-UI
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/react-app-env.d.ts
  litmus-portal/frontend/src/testHelpers/ThemeWrapper.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/myHubInput.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
Labels: READY TO MERGE, size/M

#2451 Bootstrap Litmus with Litmus-UI
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/HomePage/index.tsx
  litmus-portal/frontend/src/pages/LoginPage/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/react-app-env.d.ts
  litmus-portal/frontend/src/testHelpers/ThemeWrapper.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/myHubInput.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
Labels: READY TO MERGE, size/M

#2452 Added complete chaos result to workflow data
  litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/types/event.go
Labels: size/S

#2439 (Litmus-Portal): Adding datasource and dashboard APIs for analytics / monitoring.
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/health-check.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/prometheus.go
  litmus-portal/graphql-server/pkg/analytics/types.go
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations/analytics.go
  litmus-portal/graphql-server/pkg/database/mongodb/schema/analytics.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/queries/query.go
Labels: area/litmus, area/litmus-portal, state/dev-complete, state/review-in-progress

#2423 chore(litmus-portal): Switch Unimodal to Litmus-ui Modal
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/styles.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/containers/layouts/Center/index.tsx
  litmus-portal/frontend/src/containers/layouts/Unimodal/index.tsx
  litmus-portal/frontend/src/containers/layouts/Unimodal/styles.ts
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/styles.ts
  litmus-portal/frontend/src/views/Settings/TeammingTab/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/NodeLogs/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/XL

#2453 Added select agents screen
  litmus-portal/frontend/package.json
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/containers/layouts/Row/index.tsx
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts
Labels: size/XL

#2459 Better: Russian translation
  translations/README-ru.md
  translations/TRANSLATIONS.md
Labels: size/M

#2458 adding go info in server, event tracker and subscriber log
  litmus-portal/cluster-agents/event-tracker/event-tracker.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/graphql-server/server.go
Labels: size/S

#2463 Added gql query to get GitOps details
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: READY TO MERGE, size/XL

#2462 Adding UID and Role to /login response and refactoring in createUser GQL API
  litmus-portal/authentication/go.mod
  litmus-portal/authentication/go.sum
  litmus-portal/authentication/pkg/generates/jwt_access.go
  litmus-portal/authentication/pkg/models/user.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
Labels: PR: Changes Requested, size/L

#2465 fix(crds): Removing maxProperties field from openapi validator for chaosengine
  docs/chaos-scheduler-v1.13.0.yaml
  docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
  docs/litmus-operator-ci.yaml
  docs/litmus-operator-latest.yaml
  docs/litmus-operator-v1.13.0-crd-v1.yaml
  docs/litmus-operator-v1.13.0.yaml
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/litmus-portal-crds.yml
Labels: size/XS

#2456 chore(litmus-portal): Switch Buttons to Litmus-ui Buttons
  litmus-portal/frontend/cypress/component/buttons.spec.tsx
  litmus-portal/frontend/src/components/Button/ButtonFilled/index.tsx
  litmus-portal/frontend/src/components/Button/ButtonFilled/styles.ts
  litmus-portal/frontend/src/components/Button/ButtonOutline/index.tsx
  litmus-portal/frontend/src/components/Button/ButtonOutline/styles.ts
  litmus-portal/frontend/src/components/InstallChaos/index.tsx
  litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
  litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
  litmus-portal/frontend/src/components/Targets/TargetCopy/index.tsx
  litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  litmus-portal/frontend/src/pages/MyHub/customMyHubCard.tsx
  litmus-portal/frontend/src/pages/MyHub/index.tsx
  litmus-portal/frontend/src/pages/SchedulePage/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunDetailsTable/TableHeader.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
  litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/index.tsx
  litmus-portal/frontend/src/views/Settings/TeammingTab/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/ChooseAvatarModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Labels: PR: Changes Requested, area/litmus-portal, size/XL

#2466 chore(litmus-portal): Integrated Enable/Disable GitOps functionality in front-end
  litmus-portal/frontend/public/icons/gitops-image.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/GitHubComponents/GitHubToggleButtons/GitHubToggleButton.tsx
  litmus-portal/frontend/src/components/GitHubComponents/GitHubToggleButtons/styles.ts
  litmus-portal/frontend/src/components/GitHubComponents/GithubInputFields/GithubInputFields.tsx
  litmus-portal/frontend/src/components/GitHubComponents/GithubInputFields/styles.ts
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/gitOps.ts
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/pages/Settings/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, area/litmus-portal, size/XL

#2464 Updated Logic for Workflow Settings + Accordions + Added Alerts
  litmus-portal/frontend/public/icons/check.png
  litmus-portal/frontend/public/icons/dart.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/Header/styles.ts
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
  litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts
Labels: kind/enhancement

#2468 (chore)cleanup: remove stale and redundant artifacts from litmus
  RELEASES.md
Labels: size/L

#2445 Custom Card for Sock-Shop Predefined Workflow
  litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
Labels: READY TO MERGE, size/M

#2473 fix(version): upgrade version to 1.13.0
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-K8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/run.sh
Labels: size/S

#2471 Added workflow re-run feature
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: PR: Changes Requested, READY TO MERGE, size/L

#2454 (Litmus-Portal) GQL server refractor for database and handlers
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/resolver.go
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/health-check.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/prometheus.go
  litmus-portal/graphql-server/pkg/authorization/user_jwt.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/cluster/cluster_jwt.go
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/cluster/types.go
  litmus-portal/graphql-server/pkg/cluster/util.go
  litmus-portal/graphql-server/pkg/data-store/store.go
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/cluster/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/gitops/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/gitops/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/myhub/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/myhub/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/project/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/schema.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
  litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
  litmus-portal/graphql-server/pkg/gitops/git-lock.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
  litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
  litmus-portal/graphql-server/pkg/graphql/queries/query.go
  litmus-portal/graphql-server/pkg/graphql/subscriptions/subscription.go
  litmus-portal/graphql-server/pkg/k8s/client.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
  litmus-portal/graphql-server/pkg/myhub/ops/sshkey-gen.go
  litmus-portal/graphql-server/pkg/project/create.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/pkg/usermanagement/create.go
  litmus-portal/graphql-server/server.go
  litmus-portal/graphql-server/utils/misc.go
Labels: READY TO MERGE, area/litmus, area/litmus-portal, litmus-portal /refactor, state/dev-complete, state/review-complete

#2474 chore(litmus-portal): Added workflow rerun functionality in frontend
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/Settings/GitOpsTab/styles.ts
Labels: READY TO MERGE, area/litmus-portal, size/M

#2412 [Snyk] Upgrade @apollo/client from 3.1.2 to 3.3.6
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: size/XS

#2414 [Snyk] Upgrade react-i18next from 11.7.2 to 11.8.5
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: size/XS

#2415 [Snyk] Upgrade cronstrue from 1.100.0 to 1.106.0
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: size/XS

#2447 [Snyk] Upgrade: @material-ui/core, @material-ui/icons
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: size/XS

#2449 [Snyk] Security upgrade i18next from 19.7.0 to 19.8.5
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/package.json
Labels: size/XS
