Repository litmuschaos/litmus, pull requests merged in 2022-01, with the labels that each got.

#3414 Updated Auth API documentation
  mkdocs/docs/auth/v2.0.0/api.html
  mkdocs/docs/auth/v2.0.0/swagger.yml
  mkdocs/docs/graphql/v2.0.0/api.html
  mkdocs/docs/graphql/v2.0.0/config.yml
Labels: READY TO MERGE

#3415 Updated project schema to remove redundant fields
  litmus-portal/authentication/api/handlers/grpc/grpc_handler.go
  litmus-portal/authentication/api/handlers/rest/project_handler.go
  litmus-portal/authentication/api/types/project_types.go
  litmus-portal/authentication/pkg/entities/project.go
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
Labels: size/L

#3408 added ability to use self-signed cert for tls
  litmus-portal/cluster-agents/event-tracker/main.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/graphql-server/pkg/handlers/file_handler.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/graphql-server/pkg/types/configurations.go
  litmus-portal/graphql-server/utils/misc.go
  litmus-portal/namespaced-k8s-template.yml
Labels: size/M, PR: Changes Requested

#3416 Added RBAC to reRunChaosworkflow API
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/authorization/roles.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: size/M, PR: Changes Requested, READY TO MERGE

#3419 Updating litmus core images to v2.4.0 in CI manifests
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/S

#3421 Updated the grpc endpoints to localhost & upgrade manager
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/S, PR: Changes Requested, READY TO MERGE

#3424 Fix pod IO stress docs example for mount path
  mkdocs/docs/experiments/categories/pods/pod-io-stress/mount-path.yaml
Labels: size/XS

#3425 Update Email address
  MAINTAINERS
Labels: size/XS

#3428 Updating litmus version to 2.5.0
  litmus-portal/README.md
Labels: size/XS, READY TO MERGE

#3430 (ChaosCenter): Fixed Upgrade Agent
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/XS, READY TO MERGE

#3431 Chore(2.5.0): Add manifest for 2.5.0 litmus backend
  mkdocs/docs/chaos-scheduler-v2.5.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.5.0.yaml
Labels: size/XXL

#3432 Added partialFilter in workflow name indexing
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
Labels: size/XS, READY TO MERGE

#3435 Updating base image of frontend to nginxinc/nginx-unprivileged:1.21-alpine
  litmus-portal/frontend/Dockerfile
Labels: size/XS

#3441 Updated Sandbox to Incubating Project Status in Experiment Docs
  mkdocs/overrides/home.html
Labels: size/XS

#3434 Updated GQL Schema naming convention and docs
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/image_registry.graphqls
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/project.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/usage.graphqls
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/analytics/ops/operations.go
  litmus-portal/graphql-server/pkg/analytics/ops/prometheus/prometheus.go
  litmus-portal/graphql-server/pkg/analytics/types.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
Labels: READY TO MERGE
