Repository litmuschaos/litmus, pull requests merged in 2022-11, with the labels that each got.

#3790 Update to Pod Network Docs - Removed Ingress references
  mkdocs/docs/experiments/categories/pods/pod-network-corruption.md
  mkdocs/docs/experiments/categories/pods/pod-network-corruption/destination-ips-and-hosts.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-corruption/network-corruption.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-corruption/network-interface.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-duplication.md
  mkdocs/docs/experiments/categories/pods/pod-network-duplication/destination-ips-and-hosts.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-duplication/network-duplication.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-duplication/network-interface.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-latency.md
  mkdocs/docs/experiments/categories/pods/pod-network-latency/destination-ips-and-hosts.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-latency/network-interface.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-latency/network-latency-jitter.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-latency/network-latency.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-loss.md
  mkdocs/docs/experiments/categories/pods/pod-network-loss/destination-ips-and-hosts.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-loss/network-interface.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-loss/network-loss.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/application-details.md
Labels: area/litmus-docs, size/L, READY TO MERGE, READY-FOR-REVIEW

#3823 Chore(Fix): Fixed Aux App docs
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/application-details.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/annotation-check.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/app-info.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/auxiliary-appinfo.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/engine-state.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/jobcleanup-policy.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/service-account.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/terminationGracePeriod.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-state.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-annotations.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-configmaps-and-secrets.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-image.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-imagePullSecrets.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-nodeSelectors.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-resources.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-statusCheckTimeout.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-tolerations.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/rbac-details.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components.md
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-annotations.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-args-and-command.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-configmaps-and-secrets.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-image-and-pullPolicy.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-imagePullSecrets.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-nodeSelectors.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-resources.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-tolerations.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runtime-details.md
Labels: size/L

#3802 chore(docs): adding source and destination ports
  mkdocs/docs/experiments/categories/pods/pod-network-corruption.md
  mkdocs/docs/experiments/categories/pods/pod-network-corruption/source-and-destination-ports.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-duplication.md
  mkdocs/docs/experiments/categories/pods/pod-network-duplication/source-and-destination-ports.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-latency.md
  mkdocs/docs/experiments/categories/pods/pod-network-latency/source-and-destination-ports.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-loss.md
  mkdocs/docs/experiments/categories/pods/pod-network-loss/source-and-destination-ports.yaml
Labels: size/L, PR: Changes Requested

#3826 Adding upgrade agent for 3.0-beta1
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/XS

#3829 Ignoring semantic versioning
  litmus-portal/graphql-server/server.go
Labels: size/XS, READY TO MERGE

#3832 Updated manifest readme for 3.0-Beta1
  litmus-portal/README.md
  litmus-portal/cluster-agents/subscriber/pkg/k8s/objects.go
  litmus-portal/cluster-agents/subscriber/pkg/workloads/workloads.go
Labels: size/S

#3836 Adding multiple workloads and pod filtering
  litmus-portal/README.md
  litmus-portal/cluster-agents/subscriber/pkg/k8s/objects.go
  litmus-portal/cluster-agents/subscriber/pkg/types/kubeobject.go
  litmus-portal/cluster-agents/subscriber/pkg/workloads/workloads.go
  litmus-portal/frontend/package-lock.json
  litmus-portal/frontend/src/models/graphql/createWorkflowData.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/ConfigureDashboardMetadata/Form/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/k8s.graphqls
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/server.go
  litmus-portal/upgrade-agents/control-plane/go.mod
  litmus-portal/upgrade-agents/control-plane/go.sum
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
  mkdocs/docs/3.0-beta1/litmus-3.0-beta1-without-resources.yaml
  mkdocs/docs/3.0-beta1/litmus-3.0-beta1.yaml
  mkdocs/docs/3.0-beta1/litmus-namespaced-3.0-beta1.yaml
  mkdocs/docs/3.0-beta1/litmus-portal-crds-3.0-beta1.yml
  mkdocs/docs/3.0-beta1/upgrade-agent.yaml
Labels: READY TO MERGE

#3834 docs(spring-boot): Adding the spring boot experiments docs
  mkdocs/docs/experiments/categories/contents.md
  mkdocs/docs/experiments/categories/spring-boot/common/level.yaml
  mkdocs/docs/experiments/categories/spring-boot/common/watch-custom-services.yaml
  mkdocs/docs/experiments/categories/spring-boot/common/watchers.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-app-kill.md
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-app-kill/target-port.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-cpu-stress.md
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-cpu-stress/cpu-load-fraction.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-cpu-stress/target-port.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-exceptions.md
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-exceptions/exception-type-and-args.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-exceptions/target-port.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-experiments-tunables.md
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-faults.md
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-faults/appkill-memory-faults.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-faults/cpu-latency-exceptions-faults.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-latency.md
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-latency/latency.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-latency/target-port.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-memory-stress.md
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-memory-stress/memory-fill-fraction.yaml
  mkdocs/docs/experiments/categories/spring-boot/spring-boot-memory-stress/target-port.yaml
  mkdocs/docs/experiments/images/spring-boot-chaos.png
  mkdocs/mkdocs.yml
Labels: size/XXL
