Repository litmuschaos/litmus, pull requests merged in 2022-03, with the labels that each got.

#3468 Adding mongo headless service to mongo sts
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/M, PR: Changes Requested

#3470 fix: updated gin version
  litmus-portal/authentication/go.mod
  litmus-portal/authentication/go.sum
Labels: size/XS

#3472 Adding security contexts to all litmus resouces
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/M

#3469 Updated litmus-core images and added tagged image for curl
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/M

#3471 Adding resources requests and limits
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/L

#3476 Disabled auto mounting of default SA token for Frontend & MongoDB deployments
  litmus-portal/authentication/pkg/utils/configs.go
  litmus-portal/authentication/pkg/utils/grpc.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/L, PR: Changes Requested, READY TO MERGE

#3478 fixing auth server endpoints in the frontend NGINX config
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/XS

#3467 Fixed Authentication API issues
  litmus-portal/authentication/api/handlers/rest/project_handler.go
  litmus-portal/authentication/api/handlers/rest/user_handlers.go
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/authentication/pkg/project/repository.go
  litmus-portal/authentication/pkg/services/transaction_service.go
  litmus-portal/authentication/pkg/utils/errors.go
  litmus-portal/authentication/pkg/validations/roles.go
Labels: size/M

#3481 Adding readOnlyRootFilesystem to true for servers
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/S, READY TO MERGE

#3444 chore(chaos-center): Updated MyHub Rbacs and optimized filetype for fetching hub data
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/authorization/roles.go
  litmus-portal/graphql-server/pkg/database/mongodb/myhub/operations.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
Labels: kind/enhancement, size/L, PR: Changes Requested, READY TO MERGE

#3487 chore(chaos-center): Updated hub mountPath and minor fix in deleteAgent mutation
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
Labels: kind/bug-fix, size/S, PR: Changes Requested, READY TO MERGE

#3482 Added minor Fix for RPC endpoint in Authentication server
  litmus-portal/authentication/pkg/utils/configs.go
Labels: size/XS

#3479 Updating the k8s resources request and limits
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/L

#3490 Adding resource in chaos exporter deployment
  litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
Labels: size/XS

#3486 Rbac validation
  litmus-portal/frontend/src/graphql/mutations.ts
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/clusterData.ts
  litmus-portal/frontend/src/models/graphql/dashboardsDetails.ts
  litmus-portal/frontend/src/models/graphql/dataSourceDetails.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/Observability/DataSources/Table/TableData.tsx
  litmus-portal/frontend/src/views/Observability/DataSources/Table/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/ChaosAnnotationsEditor/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/TuneTheQueries/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/pkg/analytics/handler/handler.go
  litmus-portal/graphql-server/pkg/authorization/roles.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
Labels: PR: Changes Requested, size/XL

#3492 Moving CLUSTERID, ACCESSKEY from agent configs to secret
  litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
  litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
Labels: size/M, PR: Changes Requested, READY TO MERGE

#3494 Fixing manifest for namespaced scope
  litmus-portal/namespaced-k8s-template.yml
Labels: size/XS, READY TO MERGE

#3495 Adding readiness routes to graphql-server and auth-server for readiness probes
  USERS.md
  litmus-portal/authentication/api/handlers/rest/misc_handlers.go
  litmus-portal/authentication/api/handlers/rest/user_handlers.go
  litmus-portal/authentication/api/main.go
  litmus-portal/authentication/api/routes/misc_routers.go
  litmus-portal/authentication/api/routes/user_router.go
  litmus-portal/authentication/pkg/misc/repository.go
  litmus-portal/authentication/pkg/project/repository.go
  litmus-portal/authentication/pkg/services/application_service.go
  litmus-portal/authentication/pkg/services/misc_service.go
  litmus-portal/authentication/pkg/user/repository.go
  litmus-portal/authentication/pkg/utils/mongo_database.go
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/pkg/database/mongodb/init.go
  litmus-portal/graphql-server/pkg/database/mongodb/operations.go
  litmus-portal/graphql-server/pkg/handlers/readiness_handler.go
  litmus-portal/graphql-server/server.go
  litmus-portal/namespaced-k8s-template.yml
Labels: size/L, PR: Changes Requested, READY TO MERGE

#3500 Added minor fix for upgrade agent for 2.7.0
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/XS

#3501 added the new APIs in frontend for RBAC and fixed associated security issues
  litmus-portal/authentication/pkg/project/repository.go
  litmus-portal/frontend/src/containers/app/App.tsx
Labels: size/M, READY TO MERGE

#3504 chore(ChaosCenter): Updated Readme for 2.7.0 ChaosCenter
  litmus-portal/README.md
  litmus-portal/namespaced-k8s-template.yml
  mkdocs/docs/2.7.0/litmus-2.7.0.yaml
  mkdocs/docs/2.7.0/litmus-namespaced-2.7.0.yaml
Labels: size/S, READY TO MERGE

#3508 Release(2.7.0): Adds manifest for litmus backend 2.7.0
  mkdocs/docs/chaos-scheduler-v2.7.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.7.0.yaml
Labels: READY TO MERGE, size/XXL

#3527 feat: ability to configure self-agent component's node selector and tolerations
  litmus-portal/Makefile
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/pkg/projects/project_handler.go
  litmus-portal/graphql-server/pkg/self-deployer/start.go
  litmus-portal/graphql-server/server.go
  litmus-portal/namespaced-k8s-template.yml
Labels: size/M

#3483 Updated api docs with optional fields
  mkdocs/docs/auth/v2.0.0/api.html
  mkdocs/docs/auth/v2.0.0/public/javascripts/spectacle.min.js
  mkdocs/docs/auth/v2.0.0/swagger.yml
  mkdocs/docs/graphql/v2.0.0/api.html
Labels: size/L, PR: Changes Requested, READY TO MERGE
