Repository litmuschaos/litmus, pull requests merged in 2022-07, with the labels that each got.

#3682 Updated litmuctl command to connect agent
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/views/Targets/TargetCopy/index.tsx
Labels: size/XS, READY TO MERGE

#3680 Updated terminology for chaos agent, workflow and charts in frontend
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/LitmusStepper/index.tsx
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/components/UnconfiguredAgent/index.tsx
  litmus-portal/frontend/src/components/WorkflowCard/CardContent.tsx
  litmus-portal/frontend/src/components/WorkflowCard/CustomWorkflow.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/constants.ts
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/WorkflowStats/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/StackedBar/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/TableToolbar.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/WorkflowRunCard/index.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/ChaosTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Observability/Overview/MonitoringDashboardCard/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowGraphs/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowRunDetailsTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowRunDetailsTable/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/HeaderSection.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
Labels: READY TO MERGE, size/XL

#3685 UI Fixes: Removed the duplicate words
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
Labels: size/S, READY TO MERGE

#3688 Adding release manifests for 2.11.0 Chaoscenter release
  litmus-portal/upgrade-agents/control-plane/go.mod
  litmus-portal/upgrade-agents/control-plane/go.sum
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
  mkdocs/docs/2.11.0/litmus-2.11.0.yaml
  mkdocs/docs/2.11.0/litmus-namespaced-2.11.0.yaml
  mkdocs/docs/2.11.0/litmus-portal-crds-2.11.0.yml
  mkdocs/docs/2.11.0/upgrade-agent.yaml
Labels: READY TO MERGE, size/XXL

#3692 Updating readme for 2.11.0
  litmus-portal/README.md
Labels: size/S, READY TO MERGE

#3679 Chore [Docs]: Http Chaos Modify Body experiment docs
  mkdocs/docs/experiments/categories/contents.md
  mkdocs/docs/experiments/categories/pods/pod-http-modify-body.md
  mkdocs/docs/experiments/categories/pods/pod-http-modify-body/container-runtime-and-socket-path.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-modify-body/network-interface.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-modify-body/proxy-port.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-modify-body/response-body.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-modify-body/target-service-port.yaml
  mkdocs/docs/experiments/images/pod-http.png
  mkdocs/mkdocs.yml
Labels: READY TO MERGE, READY-FOR-REVIEW

#3677 Chore [Docs]: Http Chaos Status Code experiment docs
  mkdocs/docs/experiments/categories/contents.md
  mkdocs/docs/experiments/categories/pods/pod-http-status-code.md
  mkdocs/docs/experiments/categories/pods/pod-http-status-code/container-runtime-and-socket-path.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-status-code/modify-body-with-response.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-status-code/network-interface.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-status-code/proxy-port.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-status-code/status-code.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-status-code/target-service-port.yaml
  mkdocs/docs/experiments/images/pod-http.png
  mkdocs/mkdocs.yml
Labels: area/litmus-docs, READY TO MERGE, size/XL, READY-FOR-REVIEW

#3697 links to docs
  README.md
Labels: size/XS, READY TO MERGE

#3709 Added changes for making clusterIP as default endpoint for self/internal delegates
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/handlers/file_handler.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/manifests/namespace-k8s-manifest.yml
Labels: size/M, READY TO MERGE

#3708 Adding cluster roles and roles required for the deployment in openshift
  litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
  litmus-portal/manifests/cluster-k8s-manifest.yml
  litmus-portal/manifests/namespace-k8s-manifest.yml
Labels: size/S, READY TO MERGE
