Repository litmuschaos/litmus, pull requests merged in 2022-02, with the labels that each got.

#3429 Make workflow operations auditable
  litmus-portal/cluster-agents/subscriber/pkg/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/events/workflow.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
  litmus-portal/cluster-agents/subscriber/pkg/types/connect.go
  litmus-portal/cluster-agents/subscriber/pkg/types/event.go
  litmus-portal/cluster-agents/subscriber/pkg/utils/workflow.go
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/graphql/queries.ts
  litmus-portal/frontend/src/models/graphql/scheduleData.ts
  litmus-portal/frontend/src/models/graphql/workflowData.ts
  litmus-portal/frontend/src/models/graphql/workflowListData.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/__tests__/ReliabilityScore.test.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableHeader.tsx
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/pkg/authorization/user_jwt.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/cluster/types.go
  litmus-portal/graphql-server/pkg/database/mongodb/workflow/schema.go
  litmus-portal/graphql-server/pkg/gitops/gitops.go
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: size/L, READY TO MERGE

#3449 (Chaos-Center): Upgraded Core Images to v2.5.0 in master manifests
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/S, READY TO MERGE

#3450 Added control-plane upgrade script and minor UI fix
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/index.tsx
  litmus-portal/upgrade-agents/control-plane/go.mod
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
  litmus-portal/upgrade-agents/control-plane/versions/v2.6.0/manager.go
  litmus-portal/upgrade-agents/control-plane/versions/v2.6.0/workflow.go
Labels: size/M, PR: Changes Requested

#3454 Updated Readme.md with 2.6.0 changes
  litmus-portal/README.md
Labels: size/S, READY TO MERGE

#3433 Docs(examples): Add some example docs for jitter and default app check tunable
  mkdocs/docs/experiments/categories/pods/common-tunables-for-pod-experiments.md
  mkdocs/docs/experiments/categories/pods/common/default-app-health-check.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-latency.md
  mkdocs/docs/experiments/categories/pods/pod-network-latency/network-latency-jitter.yaml
Labels: size/L

#3455 Chore(2.6.0): Add manifest for 2.6.0
  mkdocs/docs/chaos-scheduler-v2.6.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.6.0.yaml
Labels: size/XXL
