Repository litmuschaos/litmus, pull requests merged in 2022-06, with the labels that each got.

#3618 Update pod-network-latency Docs FOR JITTER env
  mkdocs/docs/experiments/categories/pods/pod-network-latency.md
Labels: area/litmus-docs, size/XS, READY TO MERGE

#3639 Enchancement: added scroll to invitation table
  litmus-portal/frontend/src/models/redux/tabs.ts
  litmus-portal/frontend/src/redux/actions/tabs.ts
  litmus-portal/frontend/src/redux/reducers/tabs.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/styles.ts
Labels: size/L, READY TO MERGE, front-end-issue

#3635 Fixed issues with httpProbe and promProbe in tune workflow section
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
Labels: kind/bug-fix, size/XS

#3630 fix(workflow-schedule): Added check for invalid schedule type
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
Labels: size/S, READY TO MERGE

#3653 Changes to the Main Repo: Added Training & Courses, Commercial Support; Updated Adopters
  ADOPTERS.md
  COMMERCIAL_SUPPORT.md
  TRAINING_AND_COURSES.md
  adopters/organizations/adidas.md
  adopters/organizations/containersolutions.md
  adopters/organizations/fis.md
  adopters/organizations/ifood.md
Labels: DO NOT MERGE, size/M

#3654 Fixed updateGitOps functionality
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/pkg/gitops/handler/handler.go
Labels: size/XS, READY TO MERGE

#3619 Chore [Docs]: Http Chaos Latency experiment docs
  mkdocs/docs/experiments/categories/contents.md
  mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss-by-label.md
  mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop-by-label.md
  mkdocs/docs/experiments/categories/pods/common-tunables-for-pod-experiments.md
  mkdocs/docs/experiments/categories/pods/pod-http-latency.md
  mkdocs/docs/experiments/categories/pods/pod-http-latency/container-runtime-and-socket-path.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-latency/latency.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-latency/listen-port.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-latency/network-interface.yaml
  mkdocs/docs/experiments/categories/pods/pod-http-latency/target-port.yaml
  mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-imagePullSecrets.yaml
  mkdocs/docs/experiments/images/pod-http.png
  mkdocs/mkdocs.yml
Labels: kind/docs, area/litmus-docs, size/L, READY TO MERGE, READY-FOR-REVIEW

#3632 Adding CHAOS_CENTER_UI_ENDPOINT available for cluster and namespace scope
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/pkg/cluster/handler/handler.go
  litmus-portal/graphql-server/pkg/handlers/file_handler.go
  litmus-portal/graphql-server/pkg/k8s/cluster.go
  litmus-portal/graphql-server/server.go
  litmus-portal/namespace-k8s-manifest.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: DO NOT MERGE, size/L, PR: Changes Requested, READY TO MERGE

#3643 Added imagePullSecret in chaos engine and minor change in probes
  .github/workflows/build.yml
  .github/workflows/push.yml
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/redux/actions/workflow.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/graphql-server/pkg/handlers/core_version_handler.go
  litmus-portal/graphql-server/server.go
  litmus-portal/namespace-k8s-manifest.yml
Labels: size/M

#3656 Minor fix in env config
  litmus-portal/graphql-server/server.go
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/XS, PR: Changes Requested

#3658 Adding manifests for v2.10.0 ChaosCenter & updating upgrade agent
  litmus-portal/manifests/agent-plane-network-policies.yml
  litmus-portal/manifests/cluster-k8s-manifest.yml
  litmus-portal/manifests/control-plane-network-policies.yml
  litmus-portal/manifests/ingress.yml
  litmus-portal/manifests/litmus-portal-crds.yml
  litmus-portal/manifests/namespace-k8s-manifest.yml
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
  mkdocs/docs/2.10.0/litmus-2.10.0.yaml
  mkdocs/docs/2.10.0/litmus-namespaced-2.10.0.yaml
  mkdocs/docs/2.10.0/litmus-portal-crds-2.10.0.yml
  mkdocs/docs/2.10.0/upgrade-agent.yaml
Labels: READY TO MERGE

#3660 Updating readme.md for 2.10.0
  litmus-portal/README.md
Labels: size/S, READY TO MERGE

#3661 Relase(2.10.0): Adds release manifest for 2.10.0
  mkdocs/docs/chaos-scheduler-v2.10.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.10.0.yaml
Labels: READY TO MERGE, size/XXL
