Repository litmuschaos/litmus, pull requests merged in 2022-04, with the labels that each got.

#3534 Added email validation and added rbac in get_user_with_project API
  litmus-portal/authentication/api/handlers/rest/project_handler.go
  litmus-portal/authentication/api/handlers/rest/user_handlers.go
  litmus-portal/authentication/pkg/entities/user.go
  litmus-portal/authentication/pkg/utils/errors.go
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/tableData.tsx
Labels: size/M, READY TO MERGE

#3529 Added created_at field while creating user via dex
  litmus-portal/authentication/api/handlers/rest/dex_auth_handler.go
Labels: size/S, READY TO MERGE

#3543 (ChaosCenter): Upgrading workflow-controller & Executor to v3.2.9 & Litmus-Core to 2.7.0
  litmus-portal/cluster-agents/subscriber/go.mod
  litmus-portal/cluster-agents/subscriber/go.sum
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/namespaced-k8s-template.yml
Labels: size/M, READY TO MERGE

#3540 Added fix for workflow failure issue while adding experiments with same name( issue #11)
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/L, READY TO MERGE

#3539 chore(chaos-center): Added workflow type filter, pre-defined workflow redirect link and updated analytics routes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/components/SideBar/index.tsx
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/ConfigureDataSources/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
  litmus-portal/frontend/src/views/Observability/DataSources/Table/TableData.tsx
  litmus-portal/frontend/src/views/Observability/DataSources/Table/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/DataSourceInactiveModal/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/PanelAndGroup/Panel.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboard/TopNavButtons/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/TuneTheQueries/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/TableData.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/MonitoringDashboardCard/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableData.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/styles.ts
Labels: size/L, READY TO MERGE

#3554 Adding aws region in mandateory field
  mkdocs/docs/experiments/categories/aws-ssm/aws-ssm-chaos-by-id.md
  mkdocs/docs/experiments/categories/aws-ssm/aws-ssm-chaos-by-tag.md
  mkdocs/docs/experiments/categories/aws/ebs-loss-by-id.md
  mkdocs/docs/experiments/categories/aws/ebs-loss-by-tag.md
  mkdocs/docs/experiments/categories/aws/ec2-terminate-by-id.md
  mkdocs/docs/experiments/categories/aws/ec2-terminate-by-tag.md
Labels: size/M

#3556 Updated pre-defined workflows route
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
Labels: size/XS, READY TO MERGE

#3546 Fixing subscriber to update CLUSTER_ID and ACCESS_KEY to the agent-secret
  litmus-portal/cluster-agents/subscriber/pkg/events/workflow.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/log.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/objects.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
  litmus-portal/cluster-agents/subscriber/pkg/utils/workflow.go
  litmus-portal/cluster-agents/subscriber/subscriber.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/namespaced-k8s-template.yml
Labels: size/L, PR: Changes Requested, READY TO MERGE

#3557 Fixing eventtracker to retrieve CLUSTER_ID and ACCESS_KEY from agent-secret
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
Labels: size/S

#3559 adding list secrets permission to eventtracker RBAC
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
  litmus-portal/namespaced-k8s-template.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
  mkdocs/docs/2.8.0/litmus-2.8.0.yaml
  mkdocs/docs/2.8.0/litmus-namespaced-2.8.0.yaml
Labels: size/S

#3561 Updating chaoscenter readme with 2.8.0 installation links
  litmus-portal/README.md
  litmus-portal/run.sh
Labels: size/M

#3553 Chore(docs): Add docs for NODE_LABEL feature in pod level experiments
  mkdocs/docs/experiments/categories/pods/common-tunables-for-pod-experiments.md
  mkdocs/docs/experiments/categories/pods/common/node-label-filter.yaml
Labels: size/M

#3563 Reducing the complexity of installing namespace scope manifest
  litmus-portal/README.md
  litmus-portal/namespace-k8s-manifest.yml
Labels: size/M, READY TO MERGE

#3525 chore: update contact details for gdsoumya
  MAINTAINERS
Labels: size/XS, READY TO MERGE

#3568 Fixing RBAC in namespaced scope
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
Labels: size/XS, PR: Changes Requested

#3574 fixing upgrade-agent
  litmus-portal/upgrade-agents/control-plane/go.mod
  litmus-portal/upgrade-agents/control-plane/go.sum
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/XS, READY TO MERGE
