Repository litmuschaos/litmus, pull requests merged in 2022-08, with the labels that each got.

#3712 changing trivy exit code to 0
  .github/workflows/build.yml
Labels: size/XS

#3705 Alter email to base64, because the regex enconding
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/graphql-server/utils/misc.go
Labels: size/S, READY TO MERGE

#3714 Fixed ui crashing issue for invalid cron syntax
  litmus-portal/frontend/src/utils/validate.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
Labels: size/M, READY TO MERGE

#3715 Added advance tune feature and updated workflow creation steps
  litmus-portal/frontend/src/graphql/queries/chaosHub.ts
  litmus-portal/frontend/src/graphql/queries/workflows.ts
  litmus-portal/frontend/src/models/graphql/chaoshub.ts
  litmus-portal/frontend/src/pages/CreateWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/AdvanceEngineTune.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/EnvironmentVariables.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/myhub.resolvers.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/graph/workflow.resolvers.go
  litmus-portal/graphql-server/pkg/authorization/roles.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
Labels: DO NOT MERGE, READY TO MERGE, size/XXL

#3717 Added UI changes, warning text for SSH method, updated litmusctl commands and minor fixes
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
  litmus-portal/frontend/src/pages/Workflows/index.tsx
  litmus-portal/frontend/src/pages/Workflows/styles.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/styles.ts
  litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
  litmus-portal/frontend/src/views/Targets/TargetCopy/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
  litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/index.tsx
Labels: size/L, PR: Changes Requested

#3721 Added getServerVersion API to fetch GQL server version
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/graph/cluster.graphqls
  litmus-portal/graphql-server/graph/cluster.resolvers.go
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Labels: size/L

#3718 Upgrading pkgs for Chaos-operator & Argo-workflows
  litmus-portal/cluster-agents/subscriber/go.mod
  litmus-portal/cluster-agents/subscriber/go.sum
  litmus-portal/cluster-agents/subscriber/pkg/events/chaosengine.go
  litmus-portal/cluster-agents/subscriber/pkg/events/util.go
  litmus-portal/cluster-agents/subscriber/pkg/types/event.go
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/graphql-server/manifests/cluster/1a_argo_crds.yaml
  litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
  litmus-portal/graphql-server/manifests/cluster/1c_argo_meta.yaml
  litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
  litmus-portal/graphql-server/pkg/chaos-workflow/types.go
  litmus-portal/manifests/cluster-k8s-manifest.yml
  litmus-portal/manifests/litmus-portal-crds.yml
  litmus-portal/manifests/namespace-k8s-manifest.yml
Labels: size/S, PR: Changes Requested, READY TO MERGE

#3716 Removed Observability route, keeping only workflow analytics, updated terminologies
  litmus-portal/frontend/Dockerfile
  litmus-portal/frontend/README.md
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
  litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
  litmus-portal/frontend/src/pages/ObservabilityPage/index.tsx
  litmus-portal/frontend/src/pages/ObservabilityPage/styles.ts
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/WorkflowStats/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/StackedBar/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/HeaderSection.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
  litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx
  litmus-portal/frontend/src/views/Observability/Overview/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableToolbar.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/styles.ts
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowRunDetailsTable/index.tsx
Labels: READY TO MERGE, size/XL

#3725 Adding request logger middleware
  litmus-portal/graphql-server/pkg/handlers/request_logger.go
  litmus-portal/graphql-server/pkg/handlers/status_handler.go
  litmus-portal/graphql-server/server.go
Labels: size/M

#3722 Added remote/hosted chaoshub functionality and updated frontend
  litmus-portal/frontend/public/icons/remote-git.svg
  litmus-portal/frontend/public/locales/en/translation.yaml
  litmus-portal/frontend/src/components/UsefulLinks/index.tsx
  litmus-portal/frontend/src/graphql/mutations/chaosHub.ts
  litmus-portal/frontend/src/graphql/queries/chaosHub.ts
  litmus-portal/frontend/src/models/graphql/chaoshub.ts
  litmus-portal/frontend/src/models/redux/index.ts
  litmus-portal/frontend/src/models/redux/myhub.ts
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/connectGit.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/connectRemote.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/styles.ts
  litmus-portal/frontend/src/pages/ChaosHub/customMyHubCard.tsx
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/pages/ChaosHub/styles.ts
  litmus-portal/frontend/src/redux/actions/myhub.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/redux/reducers/myhub.ts
  litmus-portal/frontend/src/utils/promptCopy.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/chartCard.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
  litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/ChooseADashboardType/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/model/models_gen.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/myhub.resolvers.go
  litmus-portal/graphql-server/pkg/database/mongodb/myhub/schema.go
  litmus-portal/graphql-server/pkg/myhub/handler/handler.go
  litmus-portal/graphql-server/pkg/myhub/myhub.go
  litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
Labels: DO NOT MERGE, PR: Changes Requested, READY TO MERGE, size/XXL

#3726 Added optional fields in cmdProbe and minor fixes
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
  litmus-portal/graphql-server/server.go
Labels: size/M, READY TO MERGE

#3727 Fixed edit schedule option
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
  litmus-portal/frontend/src/pages/EditSchedule/index.tsx
Labels: size/L, READY TO MERGE

#3729 Added fixes for comparison plot & logs for install experiments step & data-cy parameters for ChaosHub
  litmus-portal/frontend/src/containers/app/App.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
  litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonPlot/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonPlot/style.ts
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
  litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/styles.ts
Labels: size/L, READY TO MERGE

#3731 Minor fix in ChaosHub auth
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/connectGit.tsx
  litmus-portal/manifests/cluster-k8s-manifest.yml
  litmus-portal/manifests/namespace-k8s-manifest.yml
Labels: size/XS, READY TO MERGE

#3732 Added warning text for remote chaos hub
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/connectRemote.tsx
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/styles.ts
  litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml
  litmus-portal/manifests/namespace-k8s-manifest.yml
Labels: size/S, READY TO MERGE

#3733 Fixed issue in deactivate user and created_at showing `invalid date`
  litmus-portal/frontend/src/models/graphql/invite.ts
  litmus-portal/frontend/src/models/graphql/user.ts
  litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
  litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
  litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
  litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/tableData.tsx
  litmus-portal/graphql-server/graph/cluster.graphqls
Labels: size/M, READY TO MERGE

#3734 Fixed issue with executed_by label in subscriber and updated upgrade agent
  litmus-portal/cluster-agents/subscriber/pkg/events/util.go
  litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/S, READY TO MERGE

#3737 Updating readme for 2.12.0
  litmus-portal/README.md
Labels: size/S, READY TO MERGE

#3719 Update README.md
  README.md
Labels: size/S

#3745 Added installation manifest without resources for cluster scope
  mkdocs/docs/2.12.0/litmus-2.12.0-without-resources.yaml
Labels: size/XL

#3746 docs(cmdProbe): Adding docs for source attributes
  mkdocs/docs/experiments/concepts/chaos-resources/probes/cmdProbe.md
  mkdocs/docs/experiments/concepts/chaos-resources/probes/litmus-probes.md
Labels: size/XL
