Repository litmuschaos/litmus, pull requests merged in 2022-05, with the labels that each got.

#3566 Document fixes for cpu/io stress experiments
  .github/workflows/build.yml
  mkdocs/docs/experiments/categories/contents.md
  mkdocs/docs/experiments/categories/nodes/node-cpu-hog.md
  mkdocs/docs/experiments/categories/nodes/node-cpu-hog/node-cpu-load.yaml
  mkdocs/docs/experiments/categories/nodes/node-io-stress.md
  mkdocs/docs/experiments/categories/nodes/node-io-stress/limit-cpu-utilization.yaml
  mkdocs/docs/experiments/categories/pods/pod-cpu-hog.md
  mkdocs/docs/experiments/categories/pods/pod-cpu-hog/cpu-load.yaml
  mkdocs/docs/experiments/categories/pods/pod-io-stress.md
Labels: size/L, READY TO MERGE

#3570 update: Prometheus k8s version update from beta1 to v1
  monitoring/utils/prometheus/prometheus-scrape-configuration/01-prometheus-rbac.yaml
Labels: DO NOT MERGE, size/XS, READY TO MERGE

#3590 Fixed API docs and minor API changes
  litmus-portal/frontend/src/graphql/mutations/workflows.ts
  litmus-portal/frontend/src/pages/ChaosHub/index.tsx
  litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  mkdocs/docs/graphql/v2.9.0/api.html
  mkdocs/docs/graphql/v2.9.0/config.yml
  mkdocs/docs/graphql/v2.9.0/javascripts/spectacle.js
  mkdocs/docs/graphql/v2.9.0/javascripts/spectacle.min.js
  mkdocs/docs/graphql/v2.9.0/stylesheets/foundation.css
  mkdocs/docs/graphql/v2.9.0/stylesheets/foundation.min.css
  mkdocs/docs/graphql/v2.9.0/stylesheets/spectacle.css
  mkdocs/docs/graphql/v2.9.0/stylesheets/spectacle.min.css
Labels: READY TO MERGE

#3594 Fixed error logs in Subscriber & updated Litmus core components
  litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/namespace-k8s-manifest.yml
  litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Labels: size/M, READY TO MERGE

#3596 Chore(2.9.0): Add core component release manifest for 2.9.0
  mkdocs/docs/chaos-scheduler-v2.9.0.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
  mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
  mkdocs/docs/litmus-operator-v2.9.0.yaml
Labels: size/XXL

#3595 Fixed analytics dashboard and gitops related issues
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/frontend/src/components/Header/index.tsx
  litmus-portal/frontend/src/graphql/mutations/chaosHub.ts
  litmus-portal/frontend/src/graphql/mutations/gitOps.ts
  litmus-portal/frontend/src/models/graphql/chaoshub.ts
  litmus-portal/frontend/src/models/graphql/prometheus.ts
  litmus-portal/frontend/src/models/redux/workflow.ts
  litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
  litmus-portal/frontend/src/pages/MonitoringDashboard/index.tsx
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
  litmus-portal/frontend/src/redux/actions/workflow.ts
  litmus-portal/frontend/src/redux/reducers/index.ts
  litmus-portal/frontend/src/redux/reducers/workflow.ts
  litmus-portal/frontend/src/utils/promUtils.ts
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
  litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/TuneTheQueries/EditPanelsWizard/index.tsx
  litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
  litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
  litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go
  litmus-portal/graphql-server/pkg/handlers/core_version_handler.go
  litmus-portal/graphql-server/server.go
  litmus-portal/namespace-k8s-manifest.yml
  litmus-portal/run.sh
Labels: size/L, READY TO MERGE

#3591 Added info msg in upgrade manager when current and desired version are same
  litmus-portal/upgrade-agents/control-plane/main.go
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/S, READY TO MERGE

#3601 Fixing GitOps API in event tracker
  litmus-portal/cluster-agents/event-tracker/go.mod
  litmus-portal/cluster-agents/event-tracker/go.sum
  litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
Labels: size/XS, READY TO MERGE

#3600 Updated weightage logic and fixed workflow stats page
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
Labels: size/M, READY TO MERGE

#3565 Update ROADMAP.md
  ROADMAP.md
Labels: size/S

#3606 Minor fix in workflow stats
  litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
Labels: size/XS

#3605 Added manifests for 2.9.0 release
  mkdocs/docs/2.9.0/litmus-2.9.0.yaml
  mkdocs/docs/2.9.0/litmus-namespaced-2.9.0.yaml
  mkdocs/docs/2.9.0/litmus-portal-crds-2.9.0.yml
  mkdocs/docs/2.9.0/upgrade-agent.yaml
Labels: DO NOT MERGE, PR: Changes Requested, size/XXL

#3607 Updated version to 2.9.0 in readme
  litmus-portal/README.md
  litmus-portal/run.sh
Labels: size/M, READY TO MERGE

#3602 Extracting queries, mutations and subscriptions to the respective schema files
  litmus-portal/graphql-server/graph/analytics.graphqls
  litmus-portal/graphql-server/graph/analytics.resolvers.go
  litmus-portal/graphql-server/graph/cluster.graphqls
  litmus-portal/graphql-server/graph/cluster.resolvers.go
  litmus-portal/graphql-server/graph/generated/generated.go
  litmus-portal/graphql-server/graph/gitops.graphqls
  litmus-portal/graphql-server/graph/gitops.resolvers.go
  litmus-portal/graphql-server/graph/image_registry.graphqls
  litmus-portal/graphql-server/graph/image_registry.resolvers.go
  litmus-portal/graphql-server/graph/myhub.graphqls
  litmus-portal/graphql-server/graph/myhub.resolvers.go
  litmus-portal/graphql-server/graph/schema.graphqls
  litmus-portal/graphql-server/graph/schema.resolvers.go
  litmus-portal/graphql-server/graph/usage.graphqls
  litmus-portal/graphql-server/graph/usage.resolvers.go
  litmus-portal/graphql-server/graph/workflow.graphqls
  litmus-portal/graphql-server/graph/workflow.resolvers.go
  litmus-portal/graphql-server/graph/workflow_template.graphqls
  litmus-portal/graphql-server/graph/workflow_template.resolvers.go
Labels: READY TO MERGE

#3622 Removed ignore-path filter from workflow level
  .github/workflows/build.yml
Labels: size/XS

#3612 Fix: AWS EKS IAM SA command
  mkdocs/docs/experiments/concepts/IAM/awsIamIntegration.md
Labels: size/XS, READY TO MERGE

#3631 Updated local nginx.conf as well as in manifests for supporting envoy proxy
  litmus-portal/cluster-k8s-manifest.yml
  litmus-portal/frontend/nginx/nginx.conf
  litmus-portal/namespace-k8s-manifest.yml
Labels: size/M, READY TO MERGE

#3523 chore (ChaosCenter): Adding Network-Policies for control-plane & agent-plane components
  litmus-portal/agent-plane-network-policies.yml
  litmus-portal/control-plane-network-policies.yml
Labels: size/L, PR: Changes Requested, READY TO MERGE
