Repository litmuschaos/litmus, pull requests merged in 2022-09, with the labels that each got.

#3752 Update ADOPTERS.md with HCL Cloud Native Labs entry
  ADOPTERS.md
Labels: size/XS

#3754 Update Adopters (AbInbev, CI&T)
  ADOPTERS.md
  adopters/organizations/abinbev.md
  adopters/organizations/ci&t.md
Labels: size/M

#3758 Added workflow.uid label in chaosengine
  litmus-portal/frontend/src/utils/yamlUtils.ts
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
  litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
Labels: size/M, READY TO MERGE

#3742 Updated litmus CRDs & updated litmus-core components to 2.12.0 in CI manifests
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/manifests/cluster-k8s-manifest.yml
  litmus-portal/manifests/litmus-portal-crds.yml
  litmus-portal/manifests/namespace-k8s-manifest.yml
  mkdocs/docs/2.12.0/litmus-portal-crds-2.12.0.yml
Labels: READY TO MERGE

#3759 Upgraded chaos operator go pkg to 2.12.0 in gql-server & subscriber
  litmus-portal/graphql-server/go.mod
  litmus-portal/graphql-server/go.sum
  litmus-portal/manifests/cluster-k8s-manifest.yml
  litmus-portal/manifests/namespace-k8s-manifest.yml
Labels: READY TO MERGE

#3765 Minor fix in CRDs
  litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
  litmus-portal/manifests/litmus-portal-crds.yml
Labels: size/XS

#3766 Updated upgrade agent version to 2.13.0
  litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
Labels: size/XS, READY TO MERGE

#3774 Update SCC docs with comments
  mkdocs/docs/experiments/concepts/security/openshift-scc.md
Labels: size/S

#3775 Updated Ports example/docs for pod network partition experiment & minor fix in installation manifest
  mkdocs/docs/2.13.0/litmus-2.13.0-without-resources.yaml
  mkdocs/docs/2.13.0/litmus-2.13.0.yaml
  mkdocs/docs/experiments/categories/pods/pod-network-partition.md
  mkdocs/docs/experiments/categories/pods/pod-network-partition/ports.yaml
Labels: size/S, READY TO MERGE

#3776 Adding depth=1 in the git clone options
  litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
Labels: size/XS, READY TO MERGE
