Repository litmuschaos/litmus, pull requests merged in 2023-07, with the labels that each got.

#4010 feat: Reduce code duplicacy in chaos-workflow package
  litmus-portal/graphql-server/pkg/chaos-workflow/service.go
Labels: LFX-MENTORSHIP, READY-FOR-REVIEW, go

#4054 fix: updated the webpack config to have entrypoint in index.ts
  chaoscenter/web/config/moduleFederation.config.js
  chaoscenter/web/config/webpack.common.js
  chaoscenter/web/config/webpack.dev.js
  chaoscenter/web/entrypoint.sh
  chaoscenter/web/nginx/nginx.conf
  chaoscenter/web/src/global.d.ts
  chaoscenter/web/src/public-path.ts
Labels: litmus3.0.0

#4059 fix: Fixed target application state not preserving issue
  chaoscenter/web/src/components/InputSlider/InputSlider.module.scss
  chaoscenter/web/src/controllers/ChaosStudioClone/ChaosStudioClone.tsx
  chaoscenter/web/src/controllers/ChaosStudioEdit/ChaosStudioEdit.tsx
  chaoscenter/web/src/controllers/TargetApplicationTab/TargetApplicationTab.tsx
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/TargetApplication/TargetApplication.tsx
Labels: litmus3.0.0

#4057 feat: 3.0.0: Added event tracker module
  chaoscenter/event-tracker/.dockerignore
  chaoscenter/event-tracker/.gitignore
  chaoscenter/event-tracker/Dockerfile
  chaoscenter/event-tracker/Makefile
  chaoscenter/event-tracker/PROJECT
  chaoscenter/event-tracker/api/v1/eventtrackerpolicy_types.go
  chaoscenter/event-tracker/api/v1/groupversion_info.go
  chaoscenter/event-tracker/api/v1/zz_generated.deepcopy.go
  chaoscenter/event-tracker/config/crd/eventtracker.litmuschaos.io_eventtrackerpolicies.yaml
  chaoscenter/event-tracker/config/rbac/clusterrole.yaml
  chaoscenter/event-tracker/config/rbac/role.yaml
  chaoscenter/event-tracker/config/sample_eventtracker_policies/eventtracker_policy_example1.yaml
  chaoscenter/event-tracker/config/sample_eventtracker_policies/eventtracker_policy_example2.yaml
  chaoscenter/event-tracker/controllers/eventtrackerpolicy_controller.go
  chaoscenter/event-tracker/controllers/suite_test.go
  chaoscenter/event-tracker/go.mod
  chaoscenter/event-tracker/go.sum
  chaoscenter/event-tracker/hack/boilerplate.go.txt
  chaoscenter/event-tracker/main.go
  chaoscenter/event-tracker/pkg/k8s/client.go
  chaoscenter/event-tracker/pkg/utils/informers.go
  chaoscenter/event-tracker/pkg/utils/utils.go
  chaoscenter/graphql/definitions/shared/gitops.graphqls
  chaoscenter/graphql/server/go.mod
  chaoscenter/graphql/server/go.sum
  chaoscenter/graphql/server/graph/generated/generated.go
  chaoscenter/graphql/server/graph/gitops.resolvers.go
  chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go
  chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go
Labels: litmus3.0.0

#4078 fix: Updated target application drawer to contain labels
  chaoscenter/web/src/routes/RouteDestinations.tsx
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/TargetApplication/TargetApplication.tsx
Labels: litmus3.0.0

#4062 #4061 Update README of litmus-portal to fix the minikube command
  litmus-portal/README.md
Labels: kind/docs, READY-FOR-REVIEW
