Repository litmuschaos/litmus, pull requests merged in 2023-11, with the labels that each got.

#4257 chore: Updating GetProbesInExperimentRun API
  chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go
Labels: backend

#4189 Tests/Chaoscenter: Added test cases for Grpc Handler
  chaoscenter/authentication/api/handlers/grpc/grpc_handler_test.go
  chaoscenter/authentication/api/mocks/grpc_mocks.go
  chaoscenter/authentication/api/mocks/rest_mocks.go
  chaoscenter/authentication/go.mod
  chaoscenter/authentication/go.sum
Labels: LFX-MENTORSHIP

#4207 Remove redundant code
  chaoscenter/web/src/views/ExperimentDashboardV2/ExperimentDashboardV2Table.tsx
Labels: good first issue, Hacktoberfest

#4175 Added tests for environments handler
  chaoscenter/graphql/server/pkg/environment/handler/handler_test.go
Labels: kind/unit-test, LFX-MENTORSHIP

#4197 Incorporate documentation for the Chaoscenter REST API
  chaoscenter/authentication/DOC_SETUP.md
  chaoscenter/authentication/api/docs/docs.go
  chaoscenter/authentication/api/docs/swagger.json
  chaoscenter/authentication/api/docs/swagger.yaml
  chaoscenter/authentication/api/handlers/doc.go
  chaoscenter/authentication/api/handlers/rest/dex_auth_handler.go
  chaoscenter/authentication/api/handlers/rest/misc_handlers.go
  chaoscenter/authentication/api/handlers/rest/project_handler.go
  chaoscenter/authentication/api/handlers/rest/user_handlers.go
  chaoscenter/authentication/api/main.go
  chaoscenter/authentication/go.mod
  chaoscenter/authentication/go.sum
Labels: LFX-MENTORSHIP

#4292 chore: update ChaosEngine crd in chaoscenter/manifest
  chaoscenter/manifests/litmus-portal-crds.yml
Labels: kind/bug-fix

#4248 feat: add tests cases for chaoscenter web views
  chaoscenter/web/src/api/ReactQueryProvider.tsx
  chaoscenter/web/src/utils/testUtils.tsx
  chaoscenter/web/src/views/ErrorCheck/__tests__/ErrorCheck.test.tsx
  chaoscenter/web/src/views/Overview/Overview.tsx
  chaoscenter/web/src/views/Overview/__tests__/Overview.test.tsx
  chaoscenter/web/src/views/ResetPassword/__tests__/ResetPassword.test.tsx
Labels: kind/unit-test, LFX-MENTORSHIP

#4249 feat: Test cases for chaosHub views
  chaoscenter/web/src/views/ChaosFault/__tests__/ChaosFault.test.tsx
  chaoscenter/web/src/views/ChaosHub/__tests__/ChaosHub.test.tsx
  chaoscenter/web/src/views/ChaosHubMenu/__tests__/ChoasHubMenu.test.tsx
Labels: kind/unit-test, LFX-MENTORSHIP

#4307 Tests: added tests for ChaosCenter web views
  chaoscenter/web/src/views/AccountDetailsChange/__tests__/AccountDetailsChange.test.tsx
  chaoscenter/web/src/views/AccountPasswordChange/__tests__/AccountPassword.test.tsx
  chaoscenter/web/src/views/CreateNewUser/__tests__/CreateNewUser.test.tsx
Labels: kind/unit-test, LFX-MENTORSHIP
