Repository litmuschaos/litmus, pull requests merged in 2023-09, with the labels that each got.

#4138 [ChaosCenter]: Implement api token CRUD logic & frontend view
  chaoscenter/authentication/api/handlers/rest/misc_handlers.go
  chaoscenter/authentication/api/handlers/rest/project_handler.go
  chaoscenter/authentication/api/handlers/rest/user_handlers.go
  chaoscenter/authentication/api/main.go
  chaoscenter/authentication/api/routes/user_router.go
  chaoscenter/authentication/pkg/entities/session.go
  chaoscenter/authentication/pkg/services/application_service.go
  chaoscenter/authentication/pkg/services/session_service.go
  chaoscenter/authentication/pkg/session/api_token_repository.go
  chaoscenter/authentication/pkg/session/revoked_token_repository.go
  chaoscenter/authentication/pkg/utils/configs.go
  chaoscenter/graphql/server/pkg/authorization/middleware.go
  chaoscenter/web/src/api/LitmusAPIProvider.tsx
  chaoscenter/web/src/api/auth/hooks/useCreateApiTokenMutation.ts
  chaoscenter/web/src/api/auth/hooks/useGetApiTokensQuery.ts
  chaoscenter/web/src/api/auth/hooks/useRemoveApiTokenMutation.ts
  chaoscenter/web/src/api/auth/index.ts
  chaoscenter/web/src/api/auth/schemas/ApiToken.ts
  chaoscenter/web/src/api/auth/schemas/CreateApiTokenResponse.ts
  chaoscenter/web/src/api/auth/schemas/GetApiTokensResponse.ts
  chaoscenter/web/src/api/auth/schemas/RemoveApiTokenResponse.ts
  chaoscenter/web/src/components/SettingsWrapper/SettingsWrapper.module.scss
  chaoscenter/web/src/components/SettingsWrapper/SettingsWrapper.tsx
  chaoscenter/web/src/controllers/AccountSettingsOverviewProjects/AccountSettingsOverviewProjects.tsx
  chaoscenter/web/src/controllers/CreateNewToken/CreateNewToken.tsx
  chaoscenter/web/src/controllers/CreateNewToken/index.ts
  chaoscenter/web/src/controllers/DeleteApiToken/DeleteApiToken.tsx
  chaoscenter/web/src/controllers/DeleteApiToken/index.ts
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/AccountSettingsOverview/AccountSettingsOverview.tsx
  chaoscenter/web/src/views/ApiTokens/ApiTokens.module.scss
  chaoscenter/web/src/views/ApiTokens/ApiTokens.module.scss.d.ts
  chaoscenter/web/src/views/ApiTokens/ApiTokens.tsx
  chaoscenter/web/src/views/ApiTokens/index.ts
  chaoscenter/web/src/views/CreateNewToken/CreateNewToken.tsx
  chaoscenter/web/src/views/CreateNewToken/index.ts
  chaoscenter/web/src/views/DeleteApiToken/DeleteApiToken.tsx
  chaoscenter/web/src/views/DeleteApiToken/index.ts
  mkdocs/docs/auth/v3.0.0/auth-api.json
Labels: language/go, kind/feature, READY-FOR-REVIEW, area/chaoscenter, language/ts

#4155 feat: Updated SideBar Component
  chaoscenter/web/src/components/MainNav/MainNav.module.scss
  chaoscenter/web/src/components/MainNav/MainNav.module.scss.d.ts
  chaoscenter/web/src/components/MainNav/MainNav.tsx
  chaoscenter/web/src/components/SettingsWrapper/SettingsWrapper.module.scss
  chaoscenter/web/src/components/SettingsWrapper/SettingsWrapper.tsx
  chaoscenter/web/src/components/SideNav/SideNav.module.scss
  chaoscenter/web/src/components/SideNav/SideNav.module.scss.d.ts
  chaoscenter/web/src/components/SideNav/SideNav.tsx
Labels: litmus3.0.0

#4159 Update the code architecture to Interface model for Environment pkg
  chaoscenter/graphql/server/graph/environment.resolvers.go
  chaoscenter/graphql/server/graph/resolver.go
  chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go
  chaoscenter/graphql/server/pkg/database/mongodb/environments/operations.go
  chaoscenter/graphql/server/pkg/environment/handler/handler.go
Labels: LFX-MENTORSHIP

#4162 Added util to update page title and added empty data check on environment page
  chaoscenter/web/src/app/App.tsx
  chaoscenter/web/src/components/ProjectCard/ProjectCard.tsx
  chaoscenter/web/src/components/SideNav/SideNav.module.scss
  chaoscenter/web/src/components/SideNav/SideNav.tsx
  chaoscenter/web/src/context/AppStoreContext.tsx
  chaoscenter/web/src/controllers/APITokens/APITokens.tsx
  chaoscenter/web/src/controllers/APITokens/index.ts
  chaoscenter/web/src/controllers/AccountSettingsOverviewProjects/AccountSettingsOverviewProjects.tsx
  chaoscenter/web/src/controllers/CreateNewToken/CreateNewToken.tsx
  chaoscenter/web/src/controllers/DeleteApiToken/DeleteApiToken.tsx
  chaoscenter/web/src/controllers/InviteNewMembers/types.ts
  chaoscenter/web/src/controllers/ProjectSelector/ProjectSelector.tsx
  chaoscenter/web/src/hooks/index.ts
  chaoscenter/web/src/hooks/useDeepCompareEffect.ts
  chaoscenter/web/src/hooks/useDocumentTitle.ts
  chaoscenter/web/src/routes/RouteDefinitions.ts
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/AccountSettings/AccountSettings.module.scss
  chaoscenter/web/src/views/AccountSettings/AccountSettings.tsx
  chaoscenter/web/src/views/AccountSettingsOverview/AccountSettingsOverview.tsx
  chaoscenter/web/src/views/AccountSettingsUserManagement/AccountSettingsUserManagement.tsx
  chaoscenter/web/src/views/ApiTokens/ApiTokens.tsx
  chaoscenter/web/src/views/ChaosHubMenu/ChaosHubMenu.tsx
  chaoscenter/web/src/views/ChaosHubs/ChaosHubs.tsx
  chaoscenter/web/src/views/ChaosProbes/ChaosProbes.tsx
  chaoscenter/web/src/views/CreateNewUser/CreateNewUser.tsx
  chaoscenter/web/src/views/Environments/EnvironmentList/EnvironmentsList.tsx
  chaoscenter/web/src/views/ExperimentCreationSelectFault/ExperimentCreationSelectFault.tsx
  chaoscenter/web/src/views/ExperimentDashboardV2/ExperimentDashboardV2.tsx
  chaoscenter/web/src/views/Gitops/Gitops.tsx
  chaoscenter/web/src/views/ImageRegistry/ImageRegistry.tsx
  chaoscenter/web/src/views/InviteNewMembers/InviteNewMemberListColumns.tsx
  chaoscenter/web/src/views/Overview/Overview.tsx
  chaoscenter/web/src/views/ProjectMembers/ActiveMembersListColumns.tsx
  chaoscenter/web/src/views/ProjectMembers/PendingMembersTable.tsx
  chaoscenter/web/src/views/ProjectMembers/ProjectMembers.tsx
Labels: litmus3.0.0

#4170 fix: Updated `Account Settings` and `Infrastructure` pages
  chaoscenter/web/src/components/SettingsWrapper/SettingsWrapper.tsx
  chaoscenter/web/src/controllers/Environments/EditEnvironment.tsx
  chaoscenter/web/src/controllers/Environments/Environment.tsx
  chaoscenter/web/src/controllers/KubernetesChaosInfrastructure/KubernetesChaosInfrastructure.tsx
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/Environments/EnvironmentList/CreateEnvironment.tsx
  chaoscenter/web/src/views/Environments/EnvironmentList/EnvironmentsList.tsx
  chaoscenter/web/src/views/Environments/EnvironmentList/EnvironmentsTableMenu.tsx
  chaoscenter/web/src/views/KubernetesChaosInfrastructure/KubernetesChaosInfrastructure.tsx
  chaoscenter/web/src/views/KubernetesChaosInfrastructureCreationModal/KubernetesChaosInfrastructureCreationModal.tsx
  chaoscenter/web/src/views/KubernetesChaosInfrastructureCreationModal/KubernetesChaosInfrastructureStepWizardConfiguration.tsx
  chaoscenter/web/src/views/ProjectsJoined/ProjectsJoined.module.scss
  chaoscenter/web/src/views/UserCreatedProjects/UserCreatedProjects.module.scss
  chaoscenter/web/src/views/UserCreatedProjects/UserCreatedProjects.tsx
Labels: litmus3.0.0

#4173 fix: Fixed UI issues found in teaming page
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/InviteNewMembers/InviteNewMemberListColumns.tsx
  chaoscenter/web/src/views/InviteNewMembers/InviteNewMemberTable.module.scss
  chaoscenter/web/src/views/InviteNewMembers/InviteNewMemberTable.module.scss.d.ts
  chaoscenter/web/src/views/InviteNewMembers/InviteNewMembers.tsx
  chaoscenter/web/src/views/InviteNewMembers/InviteUsersTable.tsx
  chaoscenter/web/src/views/ProjectMembers/PendingMembersTable.tsx
  chaoscenter/web/src/views/ProjectMembers/ProjectMember.module.scss
  chaoscenter/web/src/views/ProjectMembers/ProjectMember.module.scss.d.ts
Labels: litmus3.0.0

#4179 fix: Updated config to fix favicon
  chaoscenter/web/config/webpack.common.js
  chaoscenter/web/config/webpack.dev.js
  chaoscenter/web/package.json
  chaoscenter/web/src/index.html
  chaoscenter/web/yarn.lock
Labels: litmus3.0.0

#4182 fix: Fixed issues with refetch on ChaosHub, Environment and Probe screens
  chaoscenter/graphql/server/pkg/gitops/service.go
  chaoscenter/web/src/context/AppStoreContext.tsx
  chaoscenter/web/src/controllers/AddHubModalWizard/AddHubModalWizard.tsx
  chaoscenter/web/src/controllers/Environments/Environment.tsx
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/ChaosHubs/AddHubModal.tsx
  chaoscenter/web/src/views/ChaosProbes/ChaosProbesTableMenu.tsx
  chaoscenter/web/src/views/Environments/EnvironmentList/EnvironmentsList.tsx
  chaoscenter/web/src/views/KubernetesChaosInfrastructureCreationModal/KubernetesChaosInfrastructureStepWizardConfiguration.tsx
Labels: litmus3.0.0

#4191 fix: Fixed issue where create/edit environment API was being called twice
  chaoscenter/web/src/views/Environments/EnvironmentList/CreateEnvironment.tsx
Labels: litmus3.0.0

#4177 [chore]: Show an error popup when a user enters an invalid info
  chaoscenter/web/src/controllers/CreateNewToken/CreateNewToken.tsx
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/AccountPasswordChange/AccountPasswordChange.tsx
  chaoscenter/web/src/views/Environments/EnvironmentList/CreateEnvironment.tsx
Labels: litmus3.0.0
