Repository litmuschaos/litmus, pull requests merged in 2023-10, with the labels that each got.

#4205 fix: update ChaosEngine crd manifest file in graphql server
  chaoscenter/graphql/server/manifests/cluster/2a_litmus_crds.yaml
Labels: litmus3.0.0

#4127 Fix isRegistered check in GetK8sInfraYaml(ChaosCenter/graphql)
  chaoscenter/graphql/server/pkg/chaos_infrastructure/infra_utils.go
Labels: READY TO MERGE

#4137 Test/chaos experiments: Tests for handlers and services
  chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler_test.go
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/chaos_engine.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/chaos_schedule.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/cron_workflow.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/workflow.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/wrong_type.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/ops/service.go
  chaoscenter/graphql/server/pkg/chaos_experiment/ops/service_test.go
  chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler_test.go
  chaoscenter/graphql/server/pkg/chaos_experiment_run/model/mocks/service.go
  chaoscenter/graphql/server/pkg/chaos_experiment_run/service_test.go
  chaoscenter/graphql/server/pkg/database/mongodb/chaos_experiment/operations.go
  chaoscenter/graphql/server/pkg/gitops/model/mocks/service.go
Labels: language/go, kind/unit-test, LFX-MENTORSHIP, READY-FOR-REVIEW

#4186 Added some text occurrences in UI
  chaoscenter/web/src/components/InputSlider/InputSlider.tsx
  chaoscenter/web/src/components/YAMLBuilder/YamlBuilder.module.scss.d.ts
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/AddHubModalWizard/AddHubModalWizard.tsx
  chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.tsx
  chaoscenter/web/src/views/EditHubModalWizard/EditHubModalWizard.tsx
  chaoscenter/web/src/views/Environments/EnvironmentList/EnvironmentsTableMenu.tsx
  chaoscenter/web/src/views/ExperimentAdvancedTuningOptions/ExperimentAdvancedTuningOptions.tsx
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/AddProbeStepWizard/ProbeDetailsStep.tsx
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/AddProbeStepWizard/ProbeOverviewStep.tsx
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/AddProbeStepWizard/ProbePropertiesStep.tsx
  chaoscenter/web/src/views/KubernetesChaosInfrastructure/KubernetesChaosInfrastructure.tsx
  chaoscenter/web/src/views/KubernetesChaosInfrastructureCreationModal/KubernetesChaosInfrastructureStepWizardConfiguration.tsx
  chaoscenter/web/src/views/StudioSchedule/StudioSchedule.tsx
Labels: good first issue, READY-FOR-REVIEW, area/chaoscenter

#4226 [DOC] Added 'CRs' as an acronym for 'custom resources'
  README.md
Labels: kind/docs, good first issue

#4223 Add: Litmus Enhancement Proposals directory
  proposals/README.md
  proposals/TEMPLATE.md
  proposals/backstage-plugin.md
  proposals/images/backstage-plugin-content.png
  proposals/images/backstage-plugin-overview.png
  proposals/images/backstage-plugin-settings.png
Labels: kind/docs
