Repository litmuschaos/litmus, pull requests merged in 2024-02, with the labels that each got.

#4366 feat: Automatically generate probes when creating a chaos experiment using a YAML file.
  chaoscenter/graphql/server/graph/probe.resolvers.go
  chaoscenter/graphql/server/graph/resolver.go
  chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go
  chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler_test.go
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/chaos_engine.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/chaos_schedule.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/cron_workflow.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/service.go
  chaoscenter/graphql/server/pkg/chaos_experiment/model/mocks/workflow.yaml
  chaoscenter/graphql/server/pkg/chaos_experiment/ops/service.go
  chaoscenter/graphql/server/pkg/chaos_experiment/ops/service_test.go
  chaoscenter/graphql/server/pkg/chaos_experiment_run/model/mocks/service.go
  chaoscenter/graphql/server/pkg/gitops/service.go
  chaoscenter/graphql/server/pkg/probe/handler/handler.go
  chaoscenter/graphql/server/pkg/probe/utils/utils.go
  chaoscenter/web/src/api/ReactQueryProvider.tsx
  chaoscenter/web/src/utils/testUtils.tsx
  chaoscenter/web/src/views/ChaosStudio/ChaosStudio.tsx
  chaoscenter/web/src/views/Overview/Overview.tsx
  chaoscenter/web/src/views/Overview/__tests__/Overview.test.tsx
  chaoscenter/web/src/views/ResetPassword/__tests__/ResetPassword.test.tsx
Labels: area/chaoscenter, area/resilience-probes

#4393 Adds projectID in listInfras gql response
  chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go
Labels: backend

#4394 chore: Remove conditions for zero case
  chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go
Labels: backend

#4431 chore: [CHAOS-3808]: Resilience probe modal toggle reseting to default bugfix
  chaoscenter/graphql/server/pkg/database/mongodb/probe/schema.go
  chaoscenter/web/src/controllers/AddProbeModalWizard/AddProbeModalWizard.tsx
  chaoscenter/web/src/controllers/ChaosProbes/types.ts
  chaoscenter/web/src/controllers/UpdateProbeModalWizard/UpdateProbeModalWizard.tsx
  chaoscenter/web/src/strings/strings.en.yaml
  chaoscenter/web/src/strings/types.ts
  chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.module.scss
  chaoscenter/web/src/views/AddProbeModalWizard/AddProbeModalWizard.tsx
  chaoscenter/web/src/views/ChaosProbes/ChaosProbeTable.tsx
  chaoscenter/web/src/views/ChaosProbes/ChaosProbesTableMenu.tsx
  chaoscenter/web/src/views/ChaosProbes/UpdateProbeModal.tsx
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/ExperimentCreationFaultConfiguration.tsx
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/MenuCell.tsx
  chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/Probes.tsx
Labels: front-end-issue, area/resilience-probes

#4387 [Proposal] : Litmusctl Probe CRUD Commands
  proposals/litmusctl-probe.md
Labels: kind/enhancement
