Repository litmuschaos/litmus, pull requests merged in 2024-11, with the labels that each got.

#4860 Proposal: New Chaos Fault for AWS RDS Instance
  proposals/images/rds-fault-scenario.png
  proposals/rds-instance-chaos-fault.md
Labels: mentorship-kr

#4812 [Proposal] Support DocumentDB by replacing certain MongoDB operations
  proposals/replace-mongoDB-features.md
Labels: READY TO MERGE, mentorship-kr

#4939 Update recent videos in README
  README.md
Labels: good first issue

#4791 type(docs): Update GraphQL document (support 3.11.0)
  mkdocs/docs/experiments/api/contents.md
  mkdocs/docs/graphql/v3.10.0/api.html
  mkdocs/docs/graphql/v3.10.0/config.yml
  mkdocs/docs/graphql/v3.10.0/custom-theme/stylesheets/custom.scss
  mkdocs/docs/graphql/v3.10.0/error_response_guide.md
  mkdocs/docs/graphql/v3.10.0/images/favicon.png
  mkdocs/docs/graphql/v3.10.0/images/logo.png
  mkdocs/docs/graphql/v3.10.0/javascripts/spectaql.min.js
  mkdocs/docs/graphql/v3.10.0/stylesheets/spectaql.min.css
  mkdocs/docs/graphql/v3.10.x/api.html
  mkdocs/docs/graphql/v3.10.x/config.yml
  mkdocs/docs/graphql/v3.10.x/custom-theme/stylesheets/custom.scss
  mkdocs/docs/graphql/v3.10.x/error_response_guide.md
  mkdocs/docs/graphql/v3.10.x/images/favicon.png
  mkdocs/docs/graphql/v3.10.x/images/logo.png
  mkdocs/docs/graphql/v3.10.x/javascripts/spectaql.min.js
  mkdocs/docs/graphql/v3.10.x/stylesheets/spectaql.min.css
  mkdocs/docs/graphql/v3.11.0/api.html
  mkdocs/docs/graphql/v3.11.0/config.yml
  mkdocs/docs/graphql/v3.11.0/custom-theme/stylesheets/custom.scss
  mkdocs/docs/graphql/v3.11.0/error_response_guide.md
  mkdocs/docs/graphql/v3.11.0/images/favicon.png
  mkdocs/docs/graphql/v3.11.0/images/logo.png
  mkdocs/docs/graphql/v3.11.0/javascripts/spectaql.min.js
  mkdocs/docs/graphql/v3.11.0/stylesheets/spectaql.min.css
  mkdocs/docs/graphql/v3.11.x/api.html
  mkdocs/docs/graphql/v3.11.x/config.yml
  mkdocs/docs/graphql/v3.11.x/custom-theme/stylesheets/custom.scss
  mkdocs/docs/graphql/v3.11.x/error_response_guide.md
  mkdocs/docs/graphql/v3.11.x/images/favicon.png
  mkdocs/docs/graphql/v3.11.x/images/logo.png
  mkdocs/docs/graphql/v3.11.x/javascripts/spectaql.min.js
  mkdocs/docs/graphql/v3.11.x/stylesheets/spectaql.min.css
  mkdocs/docs/graphql/v3.9.0/api.html
  mkdocs/docs/graphql/v3.9.0/config.yml
  mkdocs/docs/graphql/v3.9.0/custom-theme/stylesheets/custom.scss
  mkdocs/docs/graphql/v3.9.0/error_response_guide.md
  mkdocs/docs/graphql/v3.9.0/images/favicon.png
  mkdocs/docs/graphql/v3.9.0/images/logo.png
  mkdocs/docs/graphql/v3.9.0/javascripts/spectaql.min.js
  mkdocs/docs/graphql/v3.9.0/stylesheets/spectaql.min.css
Labels: kind/docs, READY TO MERGE, mentorship-kr

#4684 Proposal: Distributed tracing for chaos experiments
  proposals/distributed-tracing-for-chaos-experiments.md
  proposals/images/distributed-tracing-demo-arch.png
  proposals/images/distributed-tracing-example.png
Labels: need-approvers-review

#4858 feat: add otel-demo tutorial
  monitoring/README.md
  monitoring/tutorials/README.md
  monitoring/tutorials/otel-demo/README.md
  monitoring/tutorials/otel-demo/cart-service/README.md
  monitoring/tutorials/otel-demo/cart-service/cart-service-pod-network-latency.yml
  monitoring/tutorials/otel-demo/chaos-exporter-dashboard.json
  monitoring/tutorials/otel-demo/custom_otel_demo_values.yml
  monitoring/tutorials/otel-demo/recommendation-service/README.md
  monitoring/tutorials/otel-demo/recommendation-service/recommendation-service-pod-delete.yml
  monitoring/tutorials/otel-demo/screenshots/cart_service_pod_network_latency_experiment_result_dashboard.png
  monitoring/tutorials/otel-demo/screenshots/cartservice_spanmetrics.png
  monitoring/tutorials/otel-demo/screenshots/frontend_spanmetrics.png
  monitoring/tutorials/otel-demo/screenshots/otel_demo_tutorial_architecture.png
  monitoring/tutorials/otel-demo/screenshots/recommendation_service_pod_delete_experiment_result_dashboard.png
Labels: mentorship-kr, need-approvers-review

#4871 [Proposal] Support a LitmusChaos Java SDK
  proposals/java-sdk.md
Labels: mentorship-kr, need-approvers-review

#4931 Add slice initialization to avoid null response
  chaoscenter/authentication/pkg/project/repository.go
  chaoscenter/authentication/pkg/session/api_token_repository.go
  chaoscenter/authentication/pkg/user/repository.go
Labels: mentorship-kr, need-approvers-review

#4956 Update recent videos in README-ko
  translations/README-ko.md
Labels: good first issue
