Repository litmuschaos/litmus, pull requests merged in 2024-10, with the labels that each got.

#4915 fix: Add Git Username env variable #4315
  chaoscenter/graphql/server/pkg/chaoshub/ops/gitops.go
  chaoscenter/graphql/server/pkg/gitops/gitops.go
  chaoscenter/graphql/server/utils/variables.go
Labels: good first issue

#4919 Fix typo
  translations/README-ko.md
Labels: good first issue, READY TO MERGE

#4876 bugfix: CIFuzz fail due to timeout on FuzzReadExperimentFile
  chaoscenter/graphql/server/pkg/chaos_experiment_run/fuzz_tests/service_fuzz_test.go
  chaoscenter/graphql/server/pkg/chaoshub/handler/handler_fuzz_test.go
Labels: mentorship-kr

#4895 Remove invalid links in README.md
  README.md
Labels: good first issue

#4905 Add error msg to the log on UpdateChaosExperiment
  chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go
Labels: good first issue, mentorship-kr

#4927 Fix condition not returning error during initial login
  chaoscenter/authentication/api/handlers/rest/project_handler.go
  chaoscenter/authentication/api/handlers/rest/user_handlers.go
Labels: mentorship-kr
