Repository litmuschaos/litmus, pull requests merged in 2024-08, with the labels that each got.

#4781 Update README-ko.md file
  translations/README-ko.md
Labels: good first issue, READY TO MERGE, mentorship-kr

#4820 [Security] Added 'eq' operation when querying entitiy
  chaoscenter/authentication/pkg/project/repository.go
  chaoscenter/authentication/pkg/session/revoked_token_repository.go
  chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go
  chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go
  chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go
  chaoscenter/graphql/server/pkg/chaoshub/service.go
  chaoscenter/graphql/server/pkg/environment/handler/handler.go
  chaoscenter/graphql/server/pkg/probe/handler/handler.go
Labels: mentorship-kr

#4797 feat: Change Connect Hub button to display a loading state
  chaoscenter/web/src/views/AddHubModalWizard/AddHubModalWizard.tsx
Labels: front-end-issue, mentorship-kr

#4810 [Security] Refactor gitMutex key naming in chaoscenter/graphql/server/pkg/gitops/git-lock.go
  chaoscenter/graphql/server/pkg/gitops/git-lock.go
Labels: mentorship-kr

#4825 Version up github action workflow that is working with node12 or node16 that is deprecated
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/push.yml
Labels: mentorship-kr

#4778 Apply golang code review comments to `chaoscenter/graphql/server/server.go`
  chaoscenter/graphql/server/server.go
Labels: good first issue, mentorship-kr

#4811 Fix image links in README
  README.md
  translations/README-chn.md
  translations/README-es.md
  translations/README-fr.md
  translations/README-ge.md
  translations/README-hi.md
  translations/README-ja.md
  translations/README-ko.md
  translations/README-pt-br.md
  translations/README-ru.md
Labels: mentorship-kr

#4762 fix: Improved documentation with spelling and grammar corrections in install.md
  mkdocs/docs/experiments/faq/install.md
Labels: good first issue

#4832 improvement in pagination component
  chaoscenter/web/src/controllers/Environments/Environment.tsx
Labels: front-end-issue

#4838 fix: Correct swagger.json file versions
  mkdocs/docs/auth/v3.0.0/auth-api.json
  mkdocs/docs/auth/v3.9.0/auth-api.json
Labels: mentorship-kr
